### ISSUE TITLE
Add option to package artifacts generated by scala-cli

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#10]
The idea is that rather than using 3-party script use scala-cli to package scala-cli. Initially, we aim at Ubuntu #9, Windows #7  and MacOs (brew) #8

A good source of inspiration can be a [sbt-native-packager](https://github.com/sbt/sbt-native-packager) - if possible we can reuse code from there

**Comment by alexarchambault** [comment]
About this, as the CLI isn't built by itself (as it has several modules, tests, …), we settled on the following:
- add those packaging capabilities to the `package` command of the CLI, using sbt-native-packager as an inspiration
- move those packaging capabilities to a separate library
- use this library from the build of the CLI itself to package it (which should be straightforward from mill, by adding a `import $ivy` in `build.sc`, and adding tasts using the library from there)

@lwronski started working on this already (on the first point at least).

**Comment by lwronski** [comment]
For now, we support installation scala-cli for various operating system:

- Windows
  - Msi
- Linux
  - Apt
  - Yum
  - Snap
- MacOS
  - brew
  - pkg
