### ISSUE TITLE
"./mill --repl" fails again (as of b1e8f0b6)

### ISSUE THREAD

**Issue by mtk** [VirtusLab/scala-cli#1015]
**Version(s)**
git commit b1e8f0b6

**Describe the bug**
"./mill --repl" fails with a repeated error message.

**To Reproduce**
just issue "./mill --repl".

**Expected behaviour**
should have been placed in an ammonite repl with build objects available.

**Comment by lwronski** [comment]
Hi @mtk, thanks for reporting 
Can you attach logs from `./mill --repl` command?

**Comment by mtk** [comment]
tried it again after b43b016c and the problem was gone.  sorry for the
false alarm!
/mark

**Comment by lwronski** [comment]
Good to hear, so I close issue
