### ISSUE TITLE
add uninstall instructions and uninstall command

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#1039]
**Version(s)**

0.1.5

**Describe the bug**

There is no information on https://scala-cli.virtuslab.org/install  how to uninstall scala-cli.

And there is no command `scala-cli uninstall` or similar.

**Expected behaviour**
It would be nice to get scala-cli to explain how it can be uninstalled. This is useful e.g. when you want to change the way scala-cli is installed (from sdkman to cs etc) and also if you have a really old version and want to install it from scratch.

**Comment by wleczny** [comment]
Uninstall instructions and `uninstall` command have been added in [#1122](https://github.com/VirtusLab/scala-cli/pull/1122) - it will be available in `v0.1.10`. Thanks for reporting.

**Comment by bjornregnell** [comment]
Great news! Many thanks for all your efforts for the community!
