### ISSUE TITLE
`setup-ide` command shouldn't hardcode version in the path when scala-cli is installed with homebrew

### ISSUE THREAD

**Issue by Kordyjan** [VirtusLab/scala-cli#1048]
**Version(s)**

`0.1.4` and newer

**Describe the bug**

Whenever I run `scala-cli setup-ide .` it creates `.bsp/scala-cli.json` file containing path with hardcoded version, eg.  `/usr/local/Cellar/scala-cli/0.1.5/bin/scala-cli`. Later, when homebrew updates scala-cli it removes entire `0.1.5` directory. That in order, results in metals throwing `No such file or directory` exception and generally not working.

**To Reproduce**
- Install scala-cli with homebrew.
- Run `scala-cli setup-ide .`

**Expected behaviour**
The path should point to the symlink (`/usr/local/bin/scala-cli` in my case)

**Comment by lwronski** [comment]
Hi @Kordyjan, thanks for reporting,
from the next version `0.1.7`, the path to Scala CLI should point to the symlink.
