### ISSUE TITLE
Move the Java parsing logic to a separate binary

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#1064]
Our logic for parsing the main class name in [JavaParser](https://github.com/VirtusLab/scala-cli/blob/main/modules/javaparse/src/main/scala/scala/build/internal/JavaParser.scala#L14) is bringing in too many classes to the native image along with the dotty compiler dependency, causing our windows native image generation builds [fail on our CI](https://github.com/VirtusLab/scala-cli/runs/6696993237?check_suite_focus=true#step:6:1148) due to lack of memory. 

We should extract it to a separate binary, similar to how [signing](https://github.com/scala-cli/scala-cli-signing) & [Scala.js linking](https://github.com/scala-cli/scala-js-cli-native-image) are.

**Comment by lwronski** [comment]
Closed #1064 via #1068
