### ISSUE TITLE
Automatically infer colons in dependency strings with new syntax

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1078]
It'd be nice to experiment in Scala CLI with a new syntax for dependency strings, so that users don't have to worry about the number of `:` in them. That syntax could look like
```text
org.scalameta:munit 0.7.29
```
(single `:` between organization and name, space between name and version)

We could experiment with a parser for that in Scala CLI, using the `coursier.Complete` API in a first time to list available names and pick the best one.

**Comment by Gedochao** [comment]
We don't seem to have the capacity to work on this anytime soon.
If we ever deem it as crucially important, we can get back to it.
