### ISSUE TITLE
Default fonts in some website pages

### ISSUE THREAD

**Issue by kubukoz** [VirtusLab/scala-cli#1081]
Seems like some fonts aren't loaded properly and default to Segoe UI.

System: macOS (Monterey)
Browser: firefox

a)

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/894884/172381083-5a1e8ee5-05b2-41df-a9b1-d050627de0fc.png">

b)

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/894884/172381219-b26c6b80-0869-479e-8bee-faad86ffb8ba.png">

c)

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/894884/172381351-9447efd0-f258-4284-a1c3-4a0ee1c80633.png">

d)

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/894884/172381408-9437ca9d-8405-485a-9e3f-0c0d9d08a2de.png">

(probably more outside the main page)

**Comment by tgodzik** [comment]
I don't really see a lot of difference and since investigating this might take some times I'd rather close it for the time being (and since we never really did look into it, it probably is not a big issue). If anyone want to take a look themselves do let us know!

**Comment by kubukoz** [comment]
that's fine, it's not a blocker by any means :)

**Comment by kubukoz** [comment]
although if you have a moment, can you reopen and close again but not as "completed"? (you should get a dropdown)
