### ISSUE TITLE
Packaging a simple Java app with --jvm 8 --server=false fails

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1091]
Repro:
```bash
$ cat > Test.java << EOF
public class Test {
  public static void main(String[] args) {
    System.out.println("Test");
  }
}
EOF

$ scala-cli compile --jvm 8 --server=false Test.java
javac: invalid flag: --release
Usage: javac <options> <source files>
use -help for a list of possible options
Compilation failed
```

**Comment by alexarchambault** [comment]
I think this could be fixed by returning a sensible value [here](https://github.com/VirtusLab/scala-cli/blob/e46b73b26327a2889ae6df70c348d0938708a32c/modules/build/src/main/scala/scala/build/compiler/SimpleScalaCompiler.scala#L23).

**Comment by prolativ** [comment]
I'm getting a similar error but it's not specific to packaging in my case
Given a scala file, e.g.
```scala
// Tmp.scala

object Foo
```
when on JVM 8
```shell
$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```
compiling the file with specific scala version and disabled server causes a crash, e.g.
```shell
$ scala-cli compile Tmp.scala -S 3.1.1 --server=false
8 is not a valid choice for -release
  scalac -help  gives more information
Compilation failed
```

I'm using scala-cli v0.1.14

**Comment by tgodzik** [comment]
We should not add the -release flag for Java as this can be handled by the forked compiler in Bloop. We just need to make sure that proper Java is set in the json configuration.
