### ISSUE TITLE
Missing libsodium.dll on windows

### ISSUE THREAD

**Issue by NirvanaNrv** [VirtusLab/scala-cli#1114]
**Version(s)**

At least 0.1.7 and 0.1.8, the later tested both using coursier and the msi installer, on Windows.

**Describe the bug**

System error on launch, about missing libsodium.dll .

**To Reproduce**

On Windows (10), install, launch, say, `scala-cli version`, and notice the system popup.

**Expected behaviour**
Do not complain about libsodium.dll .

I added libsodium.dll which I found browsing github, and I get through then.

**Comment by alexarchambault** [comment]
@NirvanaNrv Can you try again with the launcher that can be downloaded from the artifacts of [this run](https://github.com/VirtusLab/scala-cli/actions/runs/2510221960) (at the bottom of the page, click ["launchers"](https://github.com/VirtusLab/scala-cli/suites/6965122612/artifacts/272078028) - you need to be logged on GitHub for it to work IIRC). Unzip it, unzip `scala-cli-x86_64-pc-win32.zip` from it, and use that. This ought to fix this, I think.

**Comment by alexarchambault** [comment]
Ok, I reproduced that, and it seems https://github.com/VirtusLab/scala-cli/pull/1115 doesn't fix it 🤔
