### ISSUE TITLE
Subsequent compilations with compiler debugging flags doesn't work.

### ISSUE THREAD

**Issue by rochala** [VirtusLab/scala-cli#1131]
**Version(s)**

0.1.8

**Describe the bug**

Running `scala-cli compile --scalac-option -Yprint-pos-syms -Xprint:typer Test.scala -S 3.2.0-RC1`
Multiple times does not print trees in subsequent launches. Probably due to some caching which shouldn't work in that case.

**To Reproduce**

Prepare any Scala file and run:
`scala-cli compile --scalac-option -Yprint-pos-syms -Xprint:typer Test.scala -S 3.2.0-RC1`

**Expected behaviour**
Print trees again especially as I explicitly provide `compile` command instead of just running the app.

**Comment by alexarchambault** [comment]
It seems that's somehow expected, and not specific to Scala CLI. On subsequent compile calls, nothing gets recompiled thanks to incremental compilation, so no tree is printed. We get the same thing from sbt for example:
```text
sbt
[info] welcome to sbt 1.6.2 (AdoptOpenJDK Java 11.0.9.1)
[info] loading project definition from ./project
[info] loading settings for project tmp from build.sbt ...
[info] set current project to tmp (in build file:./)
[info] sbt server started at local://~/.sbt/1.0/server/2c03047191bbb9a53e81/sock
[info] started sbt server
sbt:tmp> compile
[info] compiling 1 Scala source to ./target/scala-3.2.0-RC1/classes ...
[info] [[syntax trees at end of                     typer]] // ./src/main/scala/Foo.scala
[info] package <empty> {
[info]   final lazy module val Foo: Foo = new Foo()@@(Foo=
[info]     ./src/main/scala/Foo.scala:<0..0>
[info]   )
[info]   final module class Foo() extends Object() { this: Foo.type =>
[info]     def main(
[info]       args: Array[String]@@(args=
[info]         ./src/main/scala/Foo.scala:<24..24>
[info]       )
[info]     ): Unit = println("Helloz")@@(main=
[info]       ./src/main/scala/Foo.scala:<19..19>
[info]     )
[info]   }@@(Foo$=
[info]     ./src/main/scala/Foo.scala:<7..7>
[info]   )
[info] }
[success] Total time: 6 s, completed 27 juin 2022 à 14:14:16
sbt:tmp> compile
[success] Total time: 0 s, completed 27 juin 2022 à 14:14:18
```

**Comment by alexarchambault** [comment]
As a workaround, disabling Bloop use with `--server=false` disables incremental compilation too, and makes Scala CLI print the tree upon every call.

**Comment by lwronski** [comment]
Or users can run `clean` command and then re-run scala files:

```
scala-cli clean .
scala-cli compile --scalac-option -Yprint-pos-syms -Xprint:typer Test.scala -S 3.2.0-RC1
```
