### ISSUE TITLE
Proper packaging for Linux and Mac OS

### ISSUE THREAD

**Issue by odisseus** [VirtusLab/scala-cli#115]
In order to install Scala CLI, the web site suggests downloading a shell script and piping it into a shell interpreter. This is a shame.

Here's one reason why this practice, though popular, should be considered harmful:
https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

I believe we should use package management tools wherever possible. Let's make installation great again!

Here's a list of package systems that are in my opinion worth supporting, in order of decreasing importance:
* [Homebrew](https://brew.sh/)
* [Sdkman](https://sdkman.io/)
* [Snap](https://snapcraft.io/)
* RPM
* DEB
* [Pacman](https://wiki.archlinux.org/title/Pacman)

**Comment by odisseus** [comment]
Never mind. I should have read the documentation more carefully.

**Comment by alexarchambault** [comment]
We don't have snap and pacman support yet… It'd be interesting to support those too @lwronski.

**Comment by alexarchambault** [comment]
sdkman support would be great too. Seems it amounts to adding a file such as [this one](https://github.com/sdkman/sdkman-db-migrations/blob/master/src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala).
