### ISSUE TITLE
Fmt command should create config with Scalafmt version if not found 

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#1160]
**Version(s)**

`0.1.9`

**Describe the bug**

`scala-cli fmt .` throws errors if version not found in `.scalafmt.conf` file:
```
Scalafmt requires explicitly specified version.
To configure the scalafmt version add the following line into .scalafmt.conf:
    version = 3.5.8 
```

**Expected behaviour**

Scala CLI should create configuration for Scalafmt which contains version

**Comment by wleczny** [comment]
There are 3 possible cases for `scala-cli fmt .`:
1. `.scalafmt.conf` is not found in the **current** or in the project's **root** directory.
2. `.scalafmt.conf` is found in the **current** or in the project's **root** directory, but doesn't have specified version.
3. `.scalafmt.conf` is found in the **current** or in the project's **root** directory and it has specified version.

- In the **first** case `scala-cli` will create `.scalafmt.conf` file with specified `version` in **workspace** directory. This file will be used to run `fmt` command and will be deleted afterwards.
- In the **second** case `scala-cli` will copy the found `.scalafmt.conf` file to **workspace** directory and will overwrite it's contents to specify `version`. Newly created file will be used to run `fmt` command and will be deleted afterwards.
- If the **third** case occurs, `scala-cli` will use the found `.scalafmt.conf` file to run `fmt` command.


Moreover, user will be able to pass `--persist-scalafmt-conf` option to `fmt` command. Passing it once will enable overwriting existing `.scalafmt.conf` files in the future. If it happens`scala-cli fmt .` will behave as follows:
 - In the **first** case `scala-cli` will create `.scalafmt.conf` file with specified `version` in **current** directory. This file will be used to run `fmt` command.
- In the **second** case `scala-cli` will overwrite the found's `.scalafmt.conf` file contents to specify `version`. This file will be used to run `fmt` command.
- If the **third** case occurs, `scala-cli` will use the found `.scalafmt.conf` file to run `fmt` command.

**Comment by mpkocher** [comment]
I believe this would be a useful ergonomic improvement and would avoid tripping up new users.
