### ISSUE TITLE
Add publishing to Maven repositories capabilities

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#12]
coursier has nascent publishing capabilities. These could be used for that, but these need some clean-up / updates before. In particular, it doesn't support "bundle uploads" to Sonatype repositories, that makes publishing there more reliable and that sbt-sonatype uses by default.

**Comment by sjrd** [comment]
I think this is out of scope of the scala-cli. If you need publishing, it means you're writing a library, and chances are you'll need a bunch of other things: a MiMa setup, cross-building, perhaps multiple platforms, etc., etc. In past discussions we mentioned several times that this was probably where the scope of scala-cli stopped, and where a build tool becomes not only necessary, but actually desirable.

**Comment by alexarchambault** [comment]
@sjrd I opened https://github.com/VirtuslabRnD/scala-cli/issues/22 to discuss library building support. I think I mentioned that support in various meetings already. MiMA, publishing, and cross-Scala version and platform seem definitely in reach to me.

**Comment by ckipp01** [comment]
While I originally would have also thought this to be a bit out-of-scope, I'm quickly finding that I'm already reaching for this. In terms of micro-libraries, being able to have a `scala-cli publish` command would be amazing. I see this was originally added in the 0.2.0 milestone, but is this still on the radar and planned? Or is it indeed out of scope of scala-cli?

**Comment by jvican** [comment]
Wanted to chime in to say that this would come in handy. One of my main personal use cases for this tool is to create simple, standalone libraries and publish them easily. In my mind, scala-cli should optimize to be the best single module build tool there is out there. Whenever I want multi module builds, I'll reach for bazel, sbt, mill or gradle.

**Comment by alexarchambault** [comment]
https://github.com/VirtusLab/scala-cli/pull/926 should fix that very soon.
