### ISSUE TITLE
Ammonite imports don't work in REPL

### ISSUE THREAD

**Issue by odisseus** [VirtusLab/scala-cli#120]
```
$ cat abc.sc 
import $ivy.`org.scalaz::scalaz-core:7.3.5`, scalaz._, Scalaz._
val x = (Option(1) |@| Option(2))(_ + _)
println(x)
$ scala-cli -S 2.12 abc.sc 
Some(3)
```
```
$ scala-cli repl -S 2.12
Welcome to Scala 2.12.14 (OpenJDK 64-Bit Server VM, Java 11.0.11).
Type in expressions for evaluation. Or try :help.

scala> import $ivy.`org.scalaz::scalaz-core:7.3.5`
<console>:11: error: not found: value $ivy
       import $ivy.`org.scalaz::scalaz-core:7.3.5`
```
```
$ scala-cli about
Scala CLI version 0.0.1 (v0.0.1)
```

**Comment by romanowski** [comment]
@alexarchambault @lwronski I spoke with @odisseus and he is missing the ability to dynamically load a library inside repl without dropping state in the memory (if that is possible). We need to discuss where this issues fits in our plans.

**Comment by DrGrognon** [comment]
For what it's worth (maybe it's obvious ^^) I tried using 
```
$ scala-cli repl --amm
@ import $ivy.`org.scalaz::scalaz-core:7.3.5`
```
Worked like a charm ! So mixing repl you got the better of each world :laughing:

**Comment by MaciejG604** [comment]
Support for `$ivy` and `$dep` ammonite imports has been removed. (See #1678) So this issue doesn't apply anymore.
