### ISSUE TITLE
Not recognizing removed resources

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#1209]
**Version(s)**
0.1.10

**Describe the bug**
When making use of the `resourceDir` using directive scala-cli doesn't correctly recognize if a resource has been removed.

**To Reproduce**

You can reproduce this with a workspace like so:

```
❯ tree
.
├── resources
│  └── examples
└── Test.scala
```
Inside of `Test.scala` have:

```scala
//> using scala "3.1.3"
//> using resourceDir "./resources"
import java.nio.file.Files
import java.nio.file.Paths
import scala.jdk.CollectionConverters._


@main def Test() =
  val uri = this.getClass().getResource("/" + "examples").toURI()
  val files = Files.list(Paths.get(uri)).toList().asScala.toSeq
  files.foreach(println)
```

If you run `scala-cli run Test.scala` the first time it will do nothing because there is no files in `examples`. Then do the following:

1. Add a `test1` inside of `examples`.
2. `scala-cli run Test.scala`
See the following:

```
❯ scli run Test.scala
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test1
```

3. Remove this file and run it again. See that it still is picking up `test1`.
```
❯ scli run Test.scala
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test1
```

4. Now add another file, `test2` inside of your resources
5. Run it again

```
❯ scli run Test.scala
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test1
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test2
```

6. Remove `test2`
7. Run it again
```
❯ scli run Test.scala
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test1
/Users/ckipp/Documents/scratch-workspace/resource-issue/.scala-build/project_f4b6a53bd1_f4b6a53bd1-c940269026/classes/main/examples/test2
```

Notice that it still thinks there are two files in your resources when you have none.

**Expected behaviour**
I'd expect this to recognize that there are changes in the resources dir and not pick up stale resources.

**Comment by lwronski** [comment]
@ckipp01 Thanks for reporting, it should be fixed in Scala CLI `0.1.14` by https://github.com/VirtusLab/scala-cli/pull/812.

```
$ tree
.
├── Test.scala
└── resources
    └── examples
        └── test1

2 directories, 2 files
$ scala-cli run Test.scala      
/private/tmp/scala-demo/.scala-build/project_00db7c197a_00db7c197a-26a550cfa0/classes/main/examples/test1
```
Remove this file and run it again.
```
$ rm resources/examples/test1 
$ scala-cli run Test.scala 
```
Add another file test2.
```
$ touch resources/examples/test2
$ scala-cli run Test.scala      
/private/tmp/scala-demo/.scala-build/project_00db7c197a_00db7c197a-26a550cfa0/classes/main/examples/test2
```
