### ISSUE TITLE
`--jvm` flag

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#1214]
**Is your feature request related to a problem? Please describe.**
Sometimes I have a script with `//> using platform "js"` but I would like quickly run it on JVM to compare behavior (I work a lot on cross-compiling libraries to have identical cross-platform semantics).

**Describe the solution you'd like**
There are already flags `--js` and `--native`, so it seems fitting to have `--jvm`.

**Describe alternatives you've considered**
I could not specify the platform in a directive, and always pass by command-line. But directives are very convenient :)

**Comment by wleczny** [comment]
As of `v0.1.15` it will be possible to set platform via `--platform` option:
```
scala-cli Foo.scala --platform jvm
```

In order to use it now, use nightly version of Scala CLI:
```
scala-cli --cli-version nightly Foo.scala --platform jvm
```
