### ISSUE TITLE
Add version of Scala to the output of `scala-cli --version`

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#1250]
**Is your feature request related to a problem? Please describe.**

Getting the version of the launcher is important mainly for advanced users; beginners would expect to see a version of Scala used.

See more in the @julienrf comment: https://github.com/scala/improvement-proposals/pull/46#discussion_r943420835

**Describe the solution you'd like**
When running `scala-cli --version` the default version of Scala is printed as well as the version of the launcher. With a provided argument (e.g. `scala-cli --version .`), the version of Scala as configured in the argument should be provided.

**Describe alternatives you've considered**
A dedicated command/argument to print Scala version.

**Comment by bjornregnell** [comment]
Good! 
And it would be helpful and good UX / DX if all these worked:
```
scala-cli -v
scala-cli --version
scala-cli -version
scala-cli version
```
(but not as critical as with all variants of `scala-cli help`, as the help command hopefully explains how to use the version command...)

**Comment by lwronski** [comment]
If we change behaviours of command `scala-cli --version`, it needs to be updated logic in `update` command, because there we run `scala-cli --version` command to find out which version of Scala Cli is already installed.
