### ISSUE TITLE
Publish documentation issues

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1280]
Per @prolativ 

4) There was a misleading comment in the docs about whether to use `central` or `central-s01` as the repository but now I can't find the same guide page I followed while doing the publish
5) there was a mismatch in naming between the documentation and the actually implemented cli options: `publish.vcs` vs `publish.versionControl`

**Comment by MaciejG604** [comment]
I think the question of `central` or `central-s01` boils down to where your account has been created according to [this](https://central.sonatype.org/news/20210223_new-users-on-s01/)

**Comment by prolativ** [comment]
As far as I remember the problem was that the docs suggested that `central-s01` should be used for new repositories. The point here is that it's actually not about the time of creation of a repository but of the account.
