### ISSUE TITLE
Better overall CLI UX

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#13]
For now, individual commands use [case-app](https://github.com/alexarchambault/case-app) to parse arguments, and picking commands is [manual](https://github.com/VirtuslabRnD/scala-cli/blob/762a173948f7086efdff87d25f9b2b008fc74796/modules/cli/src/main/scala/scala/cli/ScalaCli.scala#L13-L28).

Ideally, we'd like to have:
- comprehensive and colorful usage and help messages, both for listing commands and for individual commands
- completions for option names and option values

[case-app](https://github.com/alexarchambault/case-app) lacks support for completions, his usage and help messages are poorly formatted and have no colors, and its commands API is complex.

[moped](https://github.com/scalameta/moped) could have been a candidate for that, but for a few cons:
- it has many dependencies (JSON stuff, …)
- no colors in help messages

We also don't have a need for many of its features (testkit, conversion to / from JSON / HOCON / …)

**Comment by carueda** [comment]
I have found https://github.com/scallop/scallop very DX friendly (I have a pretty sophisticated cli application using it, unfortunately not open-sourced yet).  Although with no colors per se, it's not difficult to add them as the help output options are highly customizable in scallop.

**Comment by lwronski** [comment]
> For now, individual commands use case-app to parse arguments, and picking commands is manual.
 
picking commands is now [automatic](https://github.com/VirtusLab/scala-cli/blob/c9fd39e6b41fc07e2250ab8d64735f1b4120f0ad/modules/cli/src/main/scala/scala/cli/ScalaCli.scala#L19).
 
> completions for option names and option values

From v2.1.0-M3 case-app support completions for `bash` and `zsh.

> comprehensive and colorful usage and help messages, both for listing commands and for individual commands

Fixed in #286. It seems to me that coloring is also supported by the case-app.

**Comment by tgodzik** [comment]
It seems we can close it for now, we have a separate issue for fish completions.
