### ISSUE TITLE
Scala CLI help should provide a way to display help from compiler, REPL and other undelaying tools

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#1308]
**Is your feature request related to a problem? Please describe.**

Scala CLI is intended to be a replacement for many tools like compiler, REPL and scalafmt. That is why we should allow our users a way to inspect the help from underlying tools as well. Also a help message for each such tool should mention about different such options.

**Describe the solution you'd like**

A dedicated flag e.g. `--help-repl` or `--help-scalac` to display a help from underlying tool.

**Comment by Gedochao** [comment]
@romanowski We already have a flag for viewing help from the compiler: `--scalac-help`
```bash
▶ scala-cli --scalac-help
Usage: scalac <options> <source files>
where possible standard options include:
     -Dproperty=value  Pass -Dproperty=value directly to the runtime system.
             -J<flag>  Pass <flag> directly to the runtime system.
                   -P  Pass an option to a plugin, e.g. -P:<plugin>:<opt>
                   -V  Print a synopsis of verbose options.
                   -W  Print a synopsis of warning options.
               -Wconf  Configure compiler warnings.
              -Werror  Fail the compilation if there are any warnings.
                   -X  Print a synopsis of advanced options.
                   -Y  Print a synopsis of private options.
       (...)
```
I can add `--help-scalac` as an alias, if necessary.

**Comment by romanowski** [comment]
Ah, you are right. However, `scala-cli compile --help` does not suggest that it should be used so maybe we just need to add just this.
