### ISSUE TITLE
Documentation should explain the differences in using `shebang` command vs. using scala-cli directly in the shebangs

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#1309]
This is especially important for our SIP

**Comment by SethTisue** [comment]
Perhaps this is an opportunity to also consider the naming of `shebang`? It seems like obscure terminology to me. Maybe `script`?

**Comment by Gedochao** [comment]
> Can we do better than `shebang` on the name? It seems like obscure jargon to me

(answering https://github.com/VirtusLab/scala-cli/pull/1740#issuecomment-1372469594)
@SethTisue any suggestions for an alias?

I actually don't think it's that obscure of a jargon...
The current `shebang` sub-command has 2 main use cases:
- to be used in the `shebang` header, as per [the Unix standard](https://en.wikipedia.org/wiki/Shebang_(Unix)), for which the name seems appropriate;
- to be used from the command line with legacy syntax backwards compatible with the old `scala` runner.

Although I believe we'll be keeping the `shebang` name, as the former usecase is the main one, I think we could potentially have an alias to make it easier to guess the second one... provided that we can think of a good name for it, of course.
Would something like `run-legacy` do the trick? feels verbose to me...

Also, I wonder if an alias is even necessary... if a user cares about backwards compatibility in this context when migrating from the old `scala` runner to Scala CLI, then it's probably fair to assume he's a rare specimen of a power user. Which means he should probably be okay with obscurely named sub-commands...

We don't want to promote using `shebang` from the command line for regular users, they should just learn the `run` syntax.
