### ISSUE TITLE
Add //> using jvm "…" directive

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1337]
**Is your feature request related to a problem? Please describe.**
Users can ask for a custom JVM on the command line, like `scala-cli --jvm 11 foo.sc`. Yet there's no corresponding using directive.

**Describe the solution you'd like**
Directives such as these should be accepted by Scala CLI:
```scala
//> using jvm "11"
//> using jvm "graalvm-java17:22.2.0"
```

**Comment by alexarchambault** [comment]
Should be a matter of setting [`jvmIdOpt`](https://github.com/VirtusLab/scala-cli/blob/0d09ebf5fd369074090c9e431c43af318b07293a/modules/options/src/main/scala/scala/build/options/JavaOptions.scala#L20) in the `BuildOptions` provided by the directive.

**Comment by lwronski** [comment]
Fixed by #1539.
