### ISSUE TITLE
`cs` required in PATH

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#136]
`./mill -i show cli.nativeImage` requires `cs` (coursier) to be available in `PATH`

**Comment by alexarchambault** [comment]
Indeed. Maybe we should add that to the developer doc (which is the README for now).

**Comment by alexarchambault** [comment]
I just mentioned that in the README: https://github.com/VirtuslabRnD/scala-cli/commit/d324ee94766bbbf585cab6304e4044dd9d117cd5.

**Comment by tpasternak** [comment]
Thank you!
