### ISSUE TITLE
scala-cli always attempts to download JDK 17 when starting a repl unless --bloop-jvm system is specified.

### ISSUE THREAD

**Issue by milessabin** [VirtusLab/scala-cli#1379]
**Version(s)**
0.1.14

**Describe the bug**
When starting a repl scala-cli always attempts to download JDK 17 unless `--bloop-jvm system` is specified.

**To Reproduce**
On Arch Linux, with the system JDK configured to something other than JDK 17
```
miles@tarski:~% archlinux-java status
Available Java environments:
  java-11-graalvm (default)
  java-11-openjdk
  java-18-jdk
  java-8-openjdk
miles@tarski:~% scala-cli repl                                                                                                          
Downloading JVM temurin:17
^Ctps://github.com/adoptium/temurin17-binaries/releases/download/jdk-17%2B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz
```
Specifying the Bloop JVM explicitly gives the expect behaviour,
```
miles@tarski:~% scala-cli repl --bloop-jvm system
Welcome to Scala 3.2.0 (11.0.16, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala>
```

**Expected behaviour**
Either scala-cli shouldn't attempt to download a JDK in the default case, or there should be a configuration option to force Bloop to use the system JDK by default.

**Comment by lwronski** [comment]
@milessabin Thanks for reporting, 

Scala CLI uses bloop which requires java 17 or higher to start.  If you pass `--bloop-jvm system`, scala-cli search java >= 17 on PATH and if not found, just download it. 

I checked deeper you case. Firstly scala-cli compile source by `bloop`, and then run `repl` with compiled stuff. Therefore, scala-cli try to download java 17 to start bloop. 

In your case, is not possible to use system JDK by default, because bloop doesn't work with JAVA 11. If you install java 17 on PATH, scala-cli should work without trying to download java 17.

**Comment by milessabin** [comment]
@lwronski Bloop very definitely _does_ work with JDK11 ... it's running for me right now on the same machine supporting nvim-metals,
```
miles@tarski:~% ps lax | grep bloop
0  1000 1923123       1  20   0 15049296 4111076 futex_ Sl pts/0   13:27 /usr/lib/jvm/java-11-graalvm/bin/java -Xss4m -XX:MaxInlineLevel=20 -XX:+UseParallelGC -classpath /home/miles/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/1.5.3/bloop-frontend_2.12-1.5.3.jar:...

... lots snipped ...

...:/home/miles/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.jar bloop.Server 8212
```

**Comment by lwronski** [comment]
@milessabin  
Now, scala-cli uses fork bloop - https://github.com/scala-cli/bloop-core, which drop support for Java < 17.

**Comment by romanowski** [comment]
@milessabin We are using forked bloop to use named pipes rather than just opening ports to listen for the connection, and for this we need JVM 17. Why we are using it? One reason is that Scala CLI is aimed at education, so may be used in environments where multiple users will use scala-cli on the same host. Moreover, we are using ZGC in the bloop server to release unused memory back to OS and it was introduced in JDK 11 but was stabilized later

**Comment by milessabin** [comment]
OK, this makes sense.

However I would still like to be able to use scala-cli with a recent enough system installed JDK, even if it's not on my path. I have JDK 18 installed, so it seems like ought to be able to do this,
```
export PATH=/usr/lib/jvm/java-18-jdk/bin:$PATH ; scala-cli repl
```
but in this case scala-cli still attempts to download JDK 17.

**Comment by milessabin** [comment]
It looks like this,
```
export JAVA_HOME=/usr/lib/jvm/java-18-jdk/ ; scala-cli repl
```
does actually work.

I'm not sure the ergonomics are great, but I think it's acceptable as a workaround. I would prefer some way of persistently configuring a JDK for Bloop to use.

**Comment by romanowski** [comment]
In latest release `scala-cli --jvm 18` (`repl` is optional without arguments) starts repl with java 18:


```
> scala-cli --jvm 18

Downloading JVM 18

Downloading Scala 3.2.0 compiler
Welcome to Scala 3.2.0 (18.0.2.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                
scala> System.getProperty("java.version")
val res0: String = 18.0.2.1                               
```

**Comment by milessabin** [comment]
Yes, but only if that JDK is on the path. If it's installed, but not on the path then setting `JAVA_HOME` is still required.

**Comment by lwronski** [comment]
`scala-cli` won't be able to detect java installed if `JAVA_HOME` not exits on the`PATH`. User may have multiple versions of java installed, and it is up to the user to specify which `java` version should be used in Scala CLI.

You can specify manually `javaHome` parametry to jest java home directory:
```scala-cli Hello.scala --java-home OpenJDK11U-jdk_x64/jdk-11.0.11+9/Contents/Home/  ```

Is it good enough for you? @milessabin

**Comment by milessabin** [comment]
> Is it good enough for you? @milessabin

Yes, that's just fine.
