### ISSUE TITLE
Add fmt command

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#14]
Using scalafmt either:
- purely dynamically, downloading it upon launch and running it by spawning a JVM
- purely statically, by depending on it and including it in our native binaries
- a mix of both: default to a static embedded version, but allow for other version dynamically (although formatting would be slower)

**Comment by tgodzik** [comment]
I think the way we do it in Metals might be reused https://github.com/scalameta/metals/blob/03704c17b5397bd8feb4771d0bedf9a6dfe0a660/metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala

Though for sure native binaries would be faster.

**Comment by alexarchambault** [comment]
So https://github.com/VirtuslabRnD/scala-cli/pull/138 adds an `fmt` sub-command. It does neither of the solutions listed above. It gets native scalafmt launchers from [this repository](https://github.com/alexarchambault/scalafmt-native-image), and runs those. Its all native (just like the static way above), but we don't embed scalafmt itself in Scala CLI (just like the dynamic way above), so we get the best of both worlds ^^
