### ISSUE TITLE
There are many Winodws installation

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#1442]
![image](https://user-images.githubusercontent.com/501740/195081573-d9a58232-2d14-415c-b2bd-e0f19f29a652.png)

**Comment by lwronski** [comment]
@He-Pin Thanks for reporting, it should be fixed from `0.1.16`. When you install scala-cli `0.1.16` with `msi` installer, it should automatically remove only the previous version of scala-cli `0.1.15`. 

Unfortunately, the new installer won't be able to remove all previous versions, so users should remove earlier versions manually. 

I hope this solution meets your expectations.
