### ISSUE TITLE
When using process substitution or -e, Scala CLI shouldn't create .scala-build in the current directory

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1459]
**Version(s)**
`0.1.16`

**Describe the bug**
Running commands such as
```bash
$ scala-cli <(echo 'println("Hello")')
$ scala-cli -e 'println("Hello")'
```
creates a `.scala-build` directory, and uses it to compile the provided input. Scala CLI should rather use a directory under the home directory for that purpose.

**Comment by Gedochao** [comment]
Btw. this is only the case if no inputs are passed alongside `-e 'println("Hello")` or `_`.
What I mean is, the following two cases should still create `.scala-build` as normal:
```
$ scala-cli -e 'println(Messages.hello)' Messages.scala
$ echo 'println(Messages.hello)' | scala-cli _.sc Messages.scala
```

I believe if a subset of the following consists of all the passed sources, then `.scala-build` indeed shouldn't be created:
- snippets (`-e`, `--scala-snippet`, `--java-snippet`)
- piped sources (`_.scala`, `_.java`, `_.sc`)
- process substitution
- remote sources (i.e. GitHub gists)

We need the `.scala-build` directory locally only if those are combined with actual on-disk inputs.

**Comment by Gedochao** [comment]
> Scala CLI should rather use a directory under the home directory for that purpose.

Maybe a temporary directory would be better than `home`?

**Comment by lwronski** [comment]
> > Scala CLI should rather use a directory under the home directory for that purpose.
> 
> Maybe a temporary directory would be better than `home`?

Yes, using the `tmp` directory seems like a good idea, or we could use `Directories.cacheDir`. We should analyze which option is best.
