### ISSUE TITLE
Running function `Paths.get("")` in Metals return path with `.scala-build`

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#1483]
**Version(s)**
0.1.16

**Describe the bug**
When I running method from command line: `java.nio.file.Paths.get("").toAbsolutePath()`
it returns `$PWD`, but running from Metals return `$PWD/.scala-build`

**To Reproduce**
Command line:
```
$ scala-demo cat Hello.scala
@main def test =
    println(java.nio.file.Paths.get("").toAbsolutePath())
$ scala-demo scala-cli Hello.scala 
Compiling project (Scala 3.2.0, JVM)
Compiled project (Scala 3.2.0, JVM)
/private/tmp/scala-demo
```

Metals:
<img width="572" alt="Screenshot 2022-10-21 at 08 42 22" src="https://user-images.githubusercontent.com/46607934/197130278-8ca8c995-c59d-4f9a-8b4a-cdc6afa1efe4.png">

**Expected behaviour**
Running `Hello.scala` from Metals should return `$PWD`

**Comment by bishabosha** [comment]
as I like to use code lenses in VS Code I come across this issue often, leading me to introduce hacks like using `com.lihaoyi::sourcecode:0.3.0` to get the directory of the source file

**Comment by lwronski** [comment]
It was already fixed in bloop https://github.com/scalacenter/bloop/pull/1947. It should be fixed in the next version of Scala CLI.
