### ISSUE TITLE
Too many hyphens in some prompted options (zsh)

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#149]
Repro:
1. `scala-cli install completions --rc-file ./zsh --shell zsh`
2. `source ./zsh`
3. Type `scala-cli compile -[TAB]`

Expected:
A lot of options, including `--language`

Acual:
A lot of options, including `---language` (one extra hyphen)

**Comment by tpasternak** [comment]
More convenient repro:

`./mill cli complete zsh-v1 2 compile - | rg language`

**Comment by tpasternak** [comment]
I think it's quite important so I can look at this @alexarchambault @romanowski @lwronski

**Comment by kubukoz** [comment]
In 0.0.7 after `scala-cli compile --`, I'm getting even:

```
----p -- Add scalac option
----v -- Add scalac option
```

as well as `---language`. (in zsh)
