### ISSUE TITLE
There should be a way to get the path of the currently running script from scala

### ISSUE THREAD

**Issue by benwbooth** [VirtusLab/scala-cli#1506]
It would be great if there was a system property called "scala.script.path" or something like that, which would set the full script path when running in shebang mode. Sometimes it's useful to be able to figure out where the script is located.

**Comment by lwronski** [comment]
@benwbooth Thanks for reporting. If you need to retrieve the path of the currently running script, you can use the scriptPath method, which returns the path. You can find more information about it [here](https://scala-cli.virtuslab.org/docs/guides/scripts/#the-name-of-script).
