### ISSUE TITLE
Add using directive for target JVM

### ISSUE THREAD

**Issue by markehammons** [VirtusLab/scala-cli#1510]
**Is your feature request related to a problem? Please describe.**
I'd like to post the following code as an example program for my project using scala-cli:

```scala
using lib "fr.hammons::slinc-runtime:0.1.1-72-1cedff"
using `jvm` "19"
using `java-opt` "--enable-native-access=ALL-UNNAMED"

import fr.hammons.slinc.runtime.{*,given}

case class div_t(quot: CInt, rem: CInt) derives Struct

object MyLib derives Library:
  def abs(i: CInt): CInt = Library.binding
  def div(numer: CInt, denom: CInt): div_t = Library.binding

@main def program =
  println(MyLib.abs(-5)) // prints 5
  println(MyLib.div(5,2)) // prints div_t(2,1)
```

The jvm directive would be helpful because the option set here is java 19 specific.

**Describe the solution you'd like**
Allow the already existing jvm download feature to be applied via a using directive.

**Comment by lrytz** [comment]
duplicate of https://github.com/VirtusLab/scala-cli/issues/1337

**Comment by lwronski** [comment]
Thanks for reporting, it should be added in the next version of Scala CLI `0.1.17`.
