### ISSUE TITLE
java-style -Dproperty=value system properties

### ISSUE THREAD

**Issue by lrytz** [VirtusLab/scala-cli#1526]
For compatibility with existing `scala` scripts, could scala-cli support the `-Dproperty=value`-style command-line option?

**Comment by Gedochao** [comment]
This basically comes down to adding an alias for `--java-opt` (as per [our docs](https://scala-cli.virtuslab.org/docs/commands/run#jvm-options)), similarly to [how he handle some of the Scala compiler options](https://scala-cli.virtuslab.org/docs/commands/compile#compiler-options-recognised-even-when-passed-without--o).
