### ISSUE TITLE
munit 1.0.0-M6 hangs forever with scala-cli test

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1577]
**Version(s)**
0.1.17

**Describe the bug**
When I run `scala-cli test math.test.scala` that was written with munit 1.0.0-M6 then the process hangs (forever?)

**To Reproduce**
put this code in `math.test.scala`

```scala
//> using lib "org.scalameta::munit:1.0.0-M6"

class MathSuite extends munit.FunSuite:
  test("addition") {
    assert(1 + 1 == 2)
  }

  test("multiplication") {
    assert(3 * 7 == 21)
  }
```

```bash
scala-cli test math.test.scala
Compiling project (test, Scala 3.2.0, JVM)
Compiled project (test, Scala 3.2.0, JVM)
MathSuite:
  + addition 0.01s
  + multiplication 0.001s
# shell hangs here
```

**Expected behaviour**
exit scala-cli after test completes, I do not have this issue with munit 0.7.29

**Comment by bishabosha** [comment]
also reported in https://github.com/scalameta/munit/issues/540

**Comment by alexarchambault** [comment]
To me, this should be a wontfix on the Scala CLI side. munit shouldn't [spawn non-daemon threads](https://github.com/scalameta/munit/blob/a16b465873aea769825162d9faa6e12d5fe78d7d/munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala#L15) when it (apparently) doesn't need to.

**Comment by lwronski** [comment]
@bishabosha  Thanks for reporting in Scala CLI. It helps us to fix it in `munit` by https://github.com/scalameta/munit/pull/606.

It should work from the next release of `munit`.
