### ISSUE TITLE
Support syntax highlight for multiline using directives

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#1578]
**Is your feature request related to a problem? Please describe.**
Currently, https://github.com/scala/vscode-scala-syntax supports highlighting single line using directives, however that breaks when using multiline ones.

**Describe the solution you'd like**
Add support to vscode-scala-syntax for multiline using directives, it should enable it in vscode as well as in github.

**Describe alternatives you've considered**
No highlighting or using semantic highlighting

**Additional context**
Previous PR https://github.com/scala/vscode-scala-syntax/pull/237

**Comment by lwronski** [comment]
I will close it because it is no longer valid. Using directives now is a simple key-value without multiline support.
