### ISSUE TITLE
Support building native executables with GraalVM from Docker

### ISSUE THREAD

**Issue by baldram** [VirtusLab/scala-cli#1580]
**Version(s)**

All versions up to 0.1.17.

**Describe the bug**

The Scala CLI should offer the possibility of building native executables with GraalVM from Docker. 
It doesn't work. There are no notes on limitations in the documentation, so it's not intended.

An attempt to build the executable using `package --native-image` from Docker (using the official Scala CLI image) ends with the following error:
```sh
Error: java.lang.Exception: coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm-java17:22.2.0 not found in index: JVM graalvm-java17 not found
For more details, please see '/.scala-build/stacktraces/1668497549-12188833530046492836.log'
```

**To Reproduce**

This works:
```sh
docker run -v $(pwd)/Hello.scala:/Hello.scala virtuslab/scala-cli package --assembly /Hello.scala
```

This **does not** work:
```sh
docker run -v $(pwd)/Hello.scala:/Hello.scala virtuslab/scala-cli package --native-image /Hello.scala
```

**Expected behaviour**

The Scala CLI should offer the possibility of building native executables with GraalVM from Docker. 
This allows, for instance, creating the Linux executable from Mac. The [main Docker image](https://github.com/VirtusLab/scala-cli/blob/main/.github/scripts/docker/ScalaCliDockerFile) shall support it.

**Additional notes**

The GraalVM Native Image has prerequisites regarding packages:  gcc, glibc-devel, zlib-devel, libstdc++-static.
I succeeded with the ubuntu:20.04 as a container basis. Probably the Alpine might have some more missing pieces.

**Comment by lwronski** [comment]
@baldram Thanks for reporting this issue. As we discussed on Scalar, I made some changes to our Docker image with `scala-cli`. We now use the `docker:slim-stable` as base image, which allows users to generate a GraalVM image from Docker.

I will soon update docs on how to package your code using `scala-cli` docker image. Additionally, I will do some research on how to share the cache when packing code in docker, in order to avoid downloading a lot of dependencies every time the `package` command is run in Docker.

**Comment by baldram** [comment]
> I made some changes to our Docker image 

@lwronski Amazing! So fast.

>  I will do some research on how to share the cache when packing code in docker,

Probably you already got there. There is a [solution](https://docs.docker.com/build/cache/#use-the-dedicated-run-cache) that it's possible to use a dedicated `RUN` cache in the Docker file to prevent the dependencies from being pulled from the internet all the time. Maybe it will be helpful.

**Comment by baldram** [comment]
@lwronski It seems there is still an issue with this functionality. Is the base image updated? I got an error `Unrecognized directive: dep`.

I used this guide: https://github.com/VirtusLab/scala-cli/blob/main/website/docs/release_notes.md#added-support-for-packaging-native-images-from-docker

The following command does not work: <br>
```console
docker run -v $(pwd)/MyApp.scala:/MyApp.scala virtuslab/scala-cli package --native-image /MyApp.scala
```

Would you please have a look? Should I raise a new issue?

```console
❯ docker run -v $(pwd)/MyApp.scala:/MyApp.scala virtuslab/scala-cli package --native-image /MyApp.scala
Checking https://github.com/coursier/jvm-index/raw/master/index.json
Checked https://github.com/coursier/jvm-index/raw/master/index.json
Downloading https://github.com/coursier/jvm-index/raw/master/index.json
Downloaded https://github.com/coursier/jvm-index/raw/master/index.json
Starting compilation server
[error] ./MyApp.scala:4:16: Unrecognized directive: dep with values: com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5, com.amazonaws:aws-lambda-java-core:1.2.2, com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0
[error] //> using dep "com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./MyApp.scala:5:16: Unrecognized directive: dep with values: com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5, com.amazonaws:aws-lambda-java-core:1.2.2, com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0
[error] //> using dep "com.amazonaws:aws-lambda-java-core:1.2.2"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./MyApp.scala:6:16: Unrecognized directive: dep with values: com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5, com.amazonaws:aws-lambda-java-core:1.2.2, com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0
[error] //> using dep "com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./MyApp.scala:7:16: Unrecognized directive: dep with values: com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5, com.amazonaws:aws-lambda-java-core:1.2.2, com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0
[error] //> using dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./MyApp.scala:8:16: Unrecognized directive: dep with values: com.github.lambdaspot:aws-lambda-scala-bridge:0.1.5, com.amazonaws:aws-lambda-java-core:1.2.2, com.amazonaws:aws-lambda-java-runtime-interface-client:2.3.2, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core:2.23.0, com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0
[error] //> using dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros:2.23.0"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] ./MyApp.scala:2:16: Unrecognized directive: jvm with values: 17
[error] //> using jvm "17"
[error]                ^^
```

**Comment by baldram** [comment]
I also tried to replace all directives `dep` to `lib` as this image seems to use outdated version of Scala-CLI.<br>
The directive for `jvm` seems to be not available too. So I used command line option. Now, the following problem.

```console
❯ docker run -v $(pwd)/MyApp.scala:/MyApp.scala virtuslab/scala-cli package --native-image /MyApp.scala --jvm "graalvm-java17:22.3.2"
Checking https://github.com/coursier/jvm-index/raw/master/index.json
Checked https://github.com/coursier/jvm-index/raw/master/index.json
Downloading https://github.com/coursier/jvm-index/raw/master/index.json
Downloaded https://github.com/coursier/jvm-index/raw/master/index.json
Error: java.lang.Exception: coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm-java17:22.3.2 not found in index: JVM graalvm-java17 not found
For more details, please see '/.scala-build/stacktraces/1683051880-9954037271595949526.log'
```

**Comment by baldram** [comment]
🤦 OMG I did pull wrong. So it works. @lwronski 
Nah, don't worry 'bout it. Nothing to see here.! 🤣
