### ISSUE TITLE
Convert to sbt / mill project

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#16]
We'd like to allow to convert `scala` projects to full-fledged sbt or mill projects, if users end up needing their capabilities at some point.

**Comment by alexarchambault** [comment]
Partly done in https://github.com/VirtuslabRnD/scala-cli/pull/130 (this is still lacking Mill support, and some options need to be taken into account too - left as `TODO` in the code).

**Comment by kubukoz** [comment]
Not sure if this was missed, the sbt export renders code that doesn't parse:

```
libraryDependencies ++= Seq(
  "io.circe" %% "circe-generic" % "0.14.1"
  "io.circe" %% "circe-parser" % "0.14.1"
 )
```

(missing commas between Seq elements)
