### ISSUE TITLE
Windows MSI installer artefact is unsigned, prevents installation

### ISSUE THREAD

**Issue by nemoo** [VirtusLab/scala-cli#1607]
**Version(s)**
0.1.17

**Describe the bug**
When trying to install the Windows scala-cli msi downloaded from https://scala-cli.virtuslab.org/install, Windows Defender on Windows 10 reports that the creator of the software is unknown and prevents an installation. 

**To Reproduce**
Try to install the Windows scala-cli msi downloaded from https://scala-cli.virtuslab.org/install

**Expected behaviour**
A windows application MSI should be signed and should be installable without problems. Unsigned MSIs look kind of fishy.

**Comment by lwronski** [comment]
Thanks for reporting @nemoo. Right, our Scala CLI release procedure should be extended to signing the MSI installer.

And now you should be able to install scala-cli `0.1.17` via MSI installer with Windows Defender enabled. A few days ago I sent the MSI installer for verification by Microsoft and it was signed today.

**Comment by nemoo** [comment]
Thanks! Just tried it, the signed 0.1.17 version works! I suggest we leave this issue open until the release procedure is updated for future releases.
