### ISSUE TITLE
scala-cli with private gitlab repos

### ISSUE THREAD

**Issue by TomTriple** [VirtusLab/scala-cli#1629]
Sadly I can not use scala-cli as I need to pull/push artifacts against private, self-hosted gitlab repos. In the case of using SBT there's a plugin available [sbt-gitlab](https://github.com/gilcloud/sbt-gitlab) which set the needed **custom http header for authentication** with gitlab. I think the best solution would be to patch coursier as we could get rid of the plugin for SBT and at the same time we could use scala-cli.

**Comment by pme123** [comment]
I had to stay with ammonite, as there is support for private repositories - see https://stackoverflow.com/questions/74498839/how-to-use-a-private-repo-with-enviroment-variables-in-a-scala-cli-script

**Comment by MaciejG604** [comment]
Coursier already supports passing credentials to repositories via its API, which can be used regardless of Scala CLI.

Here's a part of the WIP documentation about this:

-----------------
Repository authentication is also supported and there are a couple ways of using it:
- specifying credentials for each host in `COURSIER_CREDENTIALS` environment variable or in the `coursier.credentials` java property,
    the supported format in this case is `host-address username:password`, e.g. `my_domain.com MyUserName:myPasswOrd`
- adding config entries for each host, this can be done using `scala-cli --power config repositories.credentials host _username_ _password_`,
    username and password values should follow the [password option format](https://scala-cli.virtuslab.org/docs/reference/password-options), e.g. 
```bash ignore
  scala-cli --power config repositories.credentials maven.pkg.github.com value:PrivateToken env:GH_TOKEN
```
----------------


After consideration Scala CLI will not support any credential interpolation in the repository addresses as proposed in #2363. Considering that one could then embed reading of arbitrary user's env vars or files, which later would be sent to an unverified web address it has been deemed unsafe.
