### ISSUE TITLE
frustrating warning for using target.platform "scala-js" directive 

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1632]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I would like to have some files compile only when Scala.js is picked as a target, however when I put using directives (`//> using target.platform "scala-js"`) in that file, I get a warning to put the using directive in `project.scala`, but I don't want to do that because I don't want the whole project to be scala-js.

Concretely for directories structured like:

```
- src
  - file1.scala (compiles any platform)
  - file2.scala (scala.js only)
- project.scala
```

**Describe the solution you'd like**
not see these warnings for files with a different target, or suggest a way to scope files for target platforms in `project.scala`

**Describe alternatives you've considered**
perhaps having directories that are scoped to specific platforms?

**Additional context**
N/A

**Comment by Gedochao** [comment]
I have mixed feelings about silencing  these warnings for files with a different target, as it's difficult to tell if putting the directives in a separate input was intentional from the perspective of one compilation.
We'd remedy your frustration, while someone else would potentially miss a stray directive.

I like the idea of adding a way to scope inputs based on platform, I think it may be worth looking into...

Meanwhile, a bandaid idea - would a way to silence those particular warnings be sufficient for now? I'm thinking a flag like `--scattered-using-directives`, or maybe even a global config with `scala-cli config scattered-using-directives true`.

**Comment by alexarchambault** [comment]
The warning should take platform / Scala version / scope filtering into account.

We have the same issue when adding dependencies in the main scope in `foo.scala` and some more in the test scope in `foo.test.scala` say. We shouldn't get a warning in that case either.

**Comment by alexarchambault** [comment]
It's a bug to me.

**Comment by Gedochao** [comment]
I agree it's a bug in the context of compilation scopes. Although in that context, it could be useful to have a centralised file for directives in the `test` scope as well, like `project.test.scala`...

~~However, I'm not so sure in the context of the target platform.
Let's say we have the following structure:~~
```text
.
├── Js.scala
├── Jvm.scala
└── project.scala
```
~~and let's say `Js.scala` has the `//> using target.platform "scala-js"` directive, while dependencies etc. are in `project.scala`.
`Jvm.scala` is launched with `scala-cli project.scala Jvm.scala`
while `Js.scala` is launched with `scala-cli project.scala Js.scala`
As things are, we'll show a warning about directives being scattered for the latter - and IMO that's the correct behaviour.
We have no way of knowing there are 2 platforms being invoked here with a different subset of inputs.
by ignoring the directive in `Js.scala` we'll introduce confusion - how is the user to know why this particular directive isn't advised to be moved to `project.scala`?
I know it's a bit of a niche use-case, but I'd advocate having consistent behaviours here.~~

~~IMO as things are, we should either advise to use 2 different `project.scala` files:~~
```text
.
├── jvm
│   ├── Jvm.scala
│   └── project.scala
├── scala-js
│   ├── Js.scala
│   └── project.scala
└── shared
    └── SharedCode.scala

```
 ~~(which could also be passed as explicit inputs from different paths)~~
 
 ~~Or even simpler: to override the platform from the command line (i.e. with `--platform scala-js` and `--platform jvm`)~~
 
 ~~So for me, it's not a bug in that context...~~

EDIT: I just realised we're talking about `//> using target.platform "scala-js"` and not `//> using platform "scala-js"`. My bad.
Yeah, agreed, it's a bug.

**Comment by lbialy** [comment]
Hi, I'm using scala-cli in a sort-of submoduled project. It boils down to this folder structure:
```
.
├── src
│   ├── main
│   │   └── project.scala
│   └── test
│       └── project.scala
├── cats
│   └── project.scala
└── zio
    └── project.scala
```

Additionally, cats and zio "modules" have the following directive in their `project.scala` file:
```
//> using file "../src" 
```

This setup allows me to emulate separate integration modules for cats and zio without migrating to mill or sbt and is fine for my project right now.

I am however massively bothered by the `Using directives detected in multiple files. It is recommended to keep them centralized in the /Users/lbialy/Projects/this-particular-project/src/main/scala/project.scala file.` warning, I have in fact 21 copies of it. I am using Metals and this warning makes this particular IDE very sluggish. I am aware that Metals does not support multi-BSP and therefore the only way to make things work correctly for me is to run:

```
scala-cli setup-ide .
scala-cli setup-ide src
scala-cli setup-ide cats
scala-cli setup-ide zio
```

With this Metals works quite ok and or at least it did until this warning was added. I might check out Intellij's multi-bsp feature but wanted to raport this use case too.
