### ISSUE TITLE
Hinting update to pre-release version

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#1633]
**Version(s)**
0.1.18

**Describe the bug**
```
[hint] ./test.scala:2:16: co.fs2::fs2-core:3.4.0 is outdated, update to 3.5-1c0be5c
[hint]      co.fs2::fs2-core:3.4.0 -> co.fs2::fs2-core:3.5-1c0be5c
[hint] //> using lib "co.fs2::fs2-core:3.4.0"
[hint]  
```

**To Reproduce**
```
//> using lib "co.fs2::fs2-core:3.4.0"
```

**Expected behaviour**

scala-cli should not suggest updates to pre-release versions. More concretely, scala-cli should not suggest updates that Scala Steward would not propose.

**Comment by lwronski** [comment]
@armanbilge Thanks for the reporting, from the next release Scala CLI should suggest only update to the stable version.

Fixed by #1634
