### ISSUE TITLE
Support jars as inputs

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#1641]
**Is your feature request related to a problem? Please describe.**
The current syntax for handling jars with Scala CLI is slightly verbose.
```bash
▶ scala-cli --classpath sample.jar --main-class Main
Hello
```
It'd be convenient to be able to skip the `--classpath` option and pass a jar straight up as an input.

**Describe the solution you'd like**
Add support like:
```bash
▶ scala-cli sample.jar
Hello
```

**Comment by lwronski** [comment]
I am closing this issue as a duplicate of https://github.com/VirtusLab/scala-cli/issues/752.

**Comment by Gedochao** [comment]
Actually, #752 is very similar, but isn't strictly a duplicate, as it suggests running jars passed as an argument to the `--jar` option...
I'm reopening this and closing #752 instead.
