### ISSUE TITLE
Confusing path shown in --usage output

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#1662]
**Version(s)**

0.1.18 installed via `cs install scala-experimental`

**Describe the bug**

When `scala` shows the “usage” instructions it shows a confusing path for the `scala` executable itself:

~~~ text
$ scala test --usage
Usage: /home/julien/.local/share/coursier/bin/.scala.aux test [options]
~~~

**To Reproduce**

- Install `scala` via `cs install scala-experimental`
- Run `scala test --usage`

**Expected behaviour**

~~~ text
$ scala test --usage
Usage: scala test [options]
~~~

**Comment by julienrf** [comment]
I wonder if that problem would go away after we actually replace the `scala` Coursier app with the content of the `scala-experimental` app?

**Comment by tgodzik** [comment]
I think the issue is related to the fast that we use the name of the current executable, which is actually the .aux file. This was fixed for completions so might be the same issue.
