### ISSUE TITLE
Ammonite imports are available in `scala` SIP command.

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1678]
**Version(s)**
0.1.18

**Describe the bug**
I can use ammonite imports when scala-cli is run under the SIP `scala` command mode

**To Reproduce**
```scala
import $ivy.`org.jsoup:jsoup:1.13.1`

import org.jsoup.Jsoup

@main def foo(url: String) = 
  Jsoup.connect(url).get()
```
compile above with `scala` command

**Expected behaviour**
no special handling for `import $ivy` and `import $dep`

**Comment by tgodzik** [comment]
Thanks for reporting! Should we drop ammonite imports altogether? It's always better to have one way of doing things. We could do 0.2.0 with that change

**Comment by julienrf** [comment]
I agree that we should not support ammonite imports. Maybe we could have a scalafix rule that would migrate from ammonite to scala-cli?

**Comment by tgodzik** [comment]
We could have a warning plus actionable diagnostics for the 0.2.x version. What does everyone else think?

**Comment by julienrf** [comment]
I don’t think this is useful for the `scala` command, but maybe that’s the simplest way for `scala` and `scala-cli` to converge?

**Comment by MaciejG604** [comment]
After further discussion support for `$ivy` and `$dep` ammonite imports has been removed.
