### ISSUE TITLE
Documentation video marked as corrupt on firefox

### ISSUE THREAD

**Issue by francisdb** [VirtusLab/scala-cli#1685]
Not sure why, this seems to work correctly on chrome

https://scala-cli.virtuslab.org/img/scala-cli-getting-started-1.mp4

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/161305/207611521-91b0a453-747d-45c0-8a9b-8525146387ad.png">

The console shows:

>Media resource https://scala-cli.virtuslab.org/img/scala-cli-getting-started-1.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.

Related post on mozilla support
https://support.mozilla.org/en-US/questions/1316956

**Comment by lwronski** [comment]
Fixed by #1904.
