### ISSUE TITLE
reduce download of artifacts?

### ISSUE THREAD

**Issue by bblfish** [VirtusLab/scala-cli#1708]
**Is your feature request related to a problem? Please describe.**
I want to use scala-cli to test the scala compiler. But doing that downloads a huge number
of files. See https://github.com/bblfish/DottyIssue16247/actions/runs/3734059610/jobs/6335649515

**Describe the solution you'd like**

An argument for github actions situation.

**Describe alternatives you've considered**
We could use `jdk-man` apparently. 
https://discord.com/channels/632642981228314653/632841743435563028/1054463858837815357

**Additional context**
https://github.com/bblfish/DottyIssue16247/actions/runs/3734059610/jobs/6335649515

**Comment by tgodzik** [comment]
Thanks for reporting! I am not sure I understand, those files are needed for running the script, is that not the case?

You can use coursier action with cache to help out, which would mean that some jars would be cached between runs.

**Comment by tgodzik** [comment]
After looking again it seems that the cache was not saved because the job failed and actually in your case we should save it since  the job is expected to fail.

**Comment by tgodzik** [comment]
It's seems we define it here https://github.com/coursier/cache-action/blob/main/action.yml#L125

Maybe we could add a a parameter to work around it and always safe for cases like this?

**Comment by tgodzik** [comment]
It might be possible to override it or you could fork the action for your own purpose with the post action always running.

Closing this as there is nothing we can do in ScalaCli to reduce the number of files downloaded
