### ISSUE TITLE
Enable globally turning off warnings about `using` directives in multiple files

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#1747]
We should add a global configuration enabling users to silence the warning about migrating directives to `project.scala`.  It should be settable with the `config` sub-command.

So something like:
```bash
scala-cli config ignore-directives-in-multiple-files true
```

Ticket motivated by a comment by @lbialy in https://github.com/VirtusLab/scala-cli/issues/1632#issuecomment-1369764141

**Comment by SethTisue** [comment]
what am I doing wrong...?

```
% scala-cli --version
Scala CLI version: 0.2.0
Scala version (default): 3.2.2
% scala-cli config ignore-directives-in-multiple-files true
Error: unrecognized key ignore-directives-in-multiple-files
```

**Comment by tgodzik** [comment]
It should be `suppress-warning.directives-in-multiple-files`
