### ISSUE TITLE
Scala CLI should support specifying dependency exclusions

### ISSUE THREAD

**Issue by rdsr** [VirtusLab/scala-cli#1751]
**Is your feature request related to a problem? Please describe.**
Many a times a transitive dependency is pulled which needs to be excluded. 

**Describe the solution you'd like**
A way to exclude a transitive dependency, similar to other build tools - Gradle, Mill, SBT. Granted Scal-cli is not a build tool, but this functionality is a necessity to adding dependencies correctly

**Comment by lwronski** [comment]
Hi @rdsr, Thanks for reporting 

 I have checked what `Coursier` options are available and found something that may be sufficient. `Coursier` has a special syntax for excluding modules:

- `exclude=org%%name` - for Scala modules
- `exclude=org%name` - for Java modules

So I prepared short demo to show, how use it:

```
➜  cat Main.scala
//> using scala 2.13

object Main extends App {
  println("Hello")
}
➜  scala-cli compile Main.scala --print-class-path --dep "com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%%sourcecode"
/private/tmp/scala-demo/.scala-build/project_61c0c5090f-74c94e0a10/classes/main:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.8.1/pprint_2.13-0.8.1.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.4.0/fansi_2.13-0.4.0.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar
```

For example, we may want to `exclude` the sourcecode dependency:

```
➜ scala-cli compile Main.scala --print-class-path --dep "com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%%sourcecode"
/private/tmp/scala-demo/.scala-build/project_a89c113365-74c94e0a10/classes/main:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.8.1/pprint_2.13-0.8.1.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.4.0/fansi_2.13-0.4.0.jar
```

I will keep this issue open because the functionality must be documented.

**Comment by rdsr** [comment]
Thanks @lwronski . A minor point about the separator for org and name is now different for dependency (:) and exclusion (%)
