### ISSUE TITLE
Specify classifiers in using lib directives

### ISSUE THREAD

**Issue by sbrunk** [VirtusLab/scala-cli#1752]
I'm working with machine learning training scripts, and `scala-cli` would be a great fit for writing them. These scripts require  native libraries though, which are packaged as jars with classifiers, as they are os and arch dependent. They can also be available in different variants like CPU and GPU, again expressed through different classifiers.

In sbt for instance, it's possible to add a classifier to a dependency in the following way:

```scala
 "org.bytedeco"   % "pytorch"    % "1.12.1-1.5.8" classifier "linux-x86_64"
 "org.bytedeco"   % "pytorch"    % "1.12.1-1.5.8" classifier "linux-x86_64-gpu"
```

I'd like to be able to express dependencies with classifiers inside a `using lib` directive, to be able to work with these kinds of libraries from scala-cli.

**Comment by lwronski** [comment]
Hi @rdsr, Thanks for reporting

`Coursier` has a special syntax for classifiers: `classifier=`. Unfortunately, it isn't currently documented.

So I prepared short demo to show, how use it:

```
➜  scala-demo scala-cli compile Main.scala --print-class-path --dep "org.bytedeco:pytorch:1.12.1-1.5.8,classifier=linux-x86_64" 
Downloading 2 dependencies
Compiling project (Scala 2.13.10, JVM)
Compiled project (Scala 2.13.10, JVM)
/private/tmp/scala-demo/.scala-build/project_a3e3069be7-74c94e0a10/classes/main:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/bytedeco/pytorch/1.12.1-1.5.8/pytorch-1.12.1-1.5.8-linux-x86_64.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.8/javacpp-1.5.8.jar:
/Users/lwronski/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/bytedeco/openblas/0.3.21-1.5.8/openblas-0.3.21-1.5.8.jar
```

I will keep this issue open because the functionality must be documented.

**Comment by sbrunk** [comment]
Thanks @lwronski!
