### ISSUE TITLE
Export information about the project

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#1791]
**Is your feature request related to a problem? Please describe.**
This has been raised in numerous places:
- https://github.com/VirtusLab/scala-cli/discussions/1005
- https://github.com/VirtusLab/scala-cli/issues/1722#issuecomment-1384182072
- Scala Steward could use information about the dependencies

**Describe the solution you'd like**
Have an export subcommand that would dump information in the json format for other tools to consume.

```
scala-cli export --json
```

Not sure about the exact format and what data we would need but at the minimum we should support a list of dependencies.

**Describe alternatives you've considered**
We could potentially copy over the json used for Bloop and analyse it.

**Comment by fthomas** [comment]
> what data we would need

For Scala Steward a list of dependencies and resolvers would be sufficient. A dependency should include at least this data:
```json
{
  "groupId": "com.lihaoyi",
  "artifactId": {
    "name": "os-lib",
    "fullName": "os-lib_2.13"
  },
  "version": "0.7.8"
}
```
While resolvers should include at least this data:
```hocon
  "MavenRepository": { // or IvyRepository
    "location": "https://repo1.maven.org/maven2/",
    "user": null,    // for usage in coursier.core.Authentication#user
    "password": null // for usage in coursier.core.Authentication#passwordOpt
    "headers": []    // for usage in coursier.core.Authentication#httpHeaders
  }
```

**Comment by tgodzik** [comment]
I think it would be good to work on that since it shouldn't be a lot of additional work and Scala Steward is a vital tool for many developers.

**Comment by MaciejG604** [comment]
@fthomas What kind of resolvers are needed? Should we also list local repositories and Coursier's defaults?

**Comment by fthomas** [comment]
The export should include all resolvers used by Scala CLI to resolve dependencies. If that includes Coursier's default resolvers and local resolvers, they should be included too.

For the use case @ckipp01 described in https://github.com/VirtusLab/scala-cli/discussions/1005#discussion-4066074, I think it would also make sense to include all resolvers including the default ones.
