### ISSUE TITLE
mill task system integration

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#18]
The `build` module can be used a a library to build projects. It would be interesting to define a `mill.define.Module` relying on it to build Java and Scala projects. All options would be configured through mill tasks, and actual compilation / packaging / etc. would be triggered from mill tasks.

That would allow to (hopefully seamlessly) transition from `scala`-build projects to more complex, possibly multi-modules, projects built through mill.

**Comment by sjrd** [comment]
Same question as in #17: what will that bring to users?

> That would allow to (hopefully seamlessly) transition from `scala`-build projects to more complex, possibly multi-modules, projects built through mill.

It seems this is the goal of #16.

**Comment by alexarchambault** [comment]
> what will that bring to users?

More stable transition from `scala`-managed project to mill-managed ones. From a user's perspective, that would also expose a more unified interface for building Scala: same options, arranged the same way, handled by the same toolchain under-the-hood. That would limit discrepancies between `scala` and mill somehow.

**Comment by alexarchambault** [comment]
I'm not saying this is high priority… (Same for https://github.com/VirtuslabRnD/scala-cli/issues/16. It's pretty low-priority as of now to me.) I opened https://github.com/VirtuslabRnD/scala-cli/issues/16 and this issue mainly to see if there's some interest.

**Comment by tgodzik** [comment]
I don't think we want to work on that currently. I will close it, we can reopen if any new initiative is taken in this area.
