### ISSUE TITLE
Quiet flag even suppresses compilation errors

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#1800]
The following seems undesirable. Suppose I have a shebang script that doesn't compile:

`foo.sc`:

```scala
#!/usr/local/bin/env -S scala-cli shebang --quiet
gjkhfhjkgfkjgfhjkghfgjk
```

because `--quiet` is present, when I run it I just get:

```
% ./foo.sc
Compilation failed
```

(Perhaps the fix for #701 was over-broad?)

**Comment by lwronski** [comment]
@SethTisue Thanks for reporting, it should be fixed in the next release of `scala-cli`.

**Comment by SethTisue** [comment]
awesome, thank you!
