### ISSUE TITLE
using toolkit "latest" makes a warning

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1809]
**Version(s)**
1.20.0

**Describe the bug**
If I put the directive `using toolkit "latest"` then I get a warning that "toolkit is outdated" :)

e.g.
```
[hint] ./myls/ls.scala:1:20: "toolkit is outdated, update to 0.1.4"
[hint]      toolkit latest.release -> 0.1.4
[hint] //> using toolkit "latest"
[hint]                    ^^^^^^
```

**To Reproduce**

`scala-cli ls.scala` command with the following snippet as contents of `ls.scala`:

```scala
//> using toolkit "latest"

@main def ls =
  os.list(os.pwd).foreach(println)
```

**Expected behaviour**
no warning

**Comment by lwronski** [comment]
@bishabosha Thanks for reporting, it should be fixed in the next release of `scala-cli`.
