### ISSUE TITLE
Incorrect message about outdated dep

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#1820]
**Version(s)**
v0.1.20

**Describe the bug**
scala-cli tells me there is a newer version of a dep, but the dep it's recommending is older.

**To Reproduce**
```
//> using scala "2.13.10"
//> using lib "io.get-coursier::coursier:2.1.0-RC5"

import coursier._

object Main extends App {}
```

```
❯ scli run Main.scala
Compiling project (Scala 2.13.10, JVM)
Compiled project (Scala 2.13.10, JVM)
[hint] ./Main.scala:2:16: "coursier is outdated, update to 2.0.16"
[hint]      coursier 2.1.0-RC5 -> io.get-coursier::coursier:2.0.16
[hint] //> using lib "io.get-coursier::coursier:2.1.0-RC5"
[hint]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behaviour**
I wouldn't expect it to recommend an older version than I'm using.

**Comment by lwronski** [comment]
@ckipp01 Thanks for your reporting, it should be fixed from the next version of `scala-cli`. It was already fixed in #1813
