### ISSUE TITLE
Noisy warning when multiple scripts with different directives are kept in the same directory

### ISSUE THREAD

**Issue by carlosedp** [VirtusLab/scala-cli#1828]
**Version(s)**
Scala CLI version: 0.1.20
Scala version (default): 3.2.2

Metals Java: 17.0.5 from GraalVM Community located at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-darwin-amd64-22.3.0.tar.gz/graalvm-ce-java17-22.3.0/Contents/Home
Metals Server version: 0.11.10+99-71c40a3b-SNAPSHOT

**Describe the bug**

Having a folder with multiple scala-cli scripts generated the message below when using scala-cli BSP in VSCode with Metals:

![image](https://user-images.githubusercontent.com/20382/216364886-6e97ebd2-e860-480e-a54c-255cd2318eb1.png)

There should be a way to silence or disable this since it might be a common use-case to have different scripts in the same dir that doesn't share the same directives.

Reference to a Metals issue discussing multiple script directory: https://github.com/scalameta/metals/issues/4481

**To Reproduce**
Have multiple scripts in the same directory each with it's own directives.

**Expected behaviour**
Not show this error or suggestion or a way to silence this.

**Comment by carlosedp** [comment]
Thanks @tgodzik ... do you know if this flag will be enabled by default on Metals? If not, will it be configurable?

**Comment by tgodzik** [comment]
It will be confugrable in scala-cli. @MaciejG604 what will be the exact command to do it?
