### ISSUE TITLE
Scala-cli warns of outdated library when actually using the newly released version

### ISSUE THREAD

**Issue by carlosedp** [VirtusLab/scala-cli#1836]
**Version(s)**
Please provide the version(s) of Scala CLI that is affected by this bug

```
❯ scli version
Scala CLI version: 0.1.20
Scala version (default): 3.2.2
```

**Describe the bug**
ZIO has just been updated to 2.0.7 (at the time of opening the issue). I've bumped the version and scala-cli started warning about not using the latest version pointing to the previous version as the newer.

```
❯ scli zioplay1.scala
[hint] ./zioplay1.scala:2:16: "zio is outdated, update to 2.0.6"
[hint]      zio 2.0.7 -> dev.zio::zio:2.0.6
[hint] //> using lib "dev.zio::zio:2.0.7"
[hint]                ^^^^^^^^^^^^^^^^^^
```

Maybe scala-cli is not checking for versions at the same repositories like Maven Central or caching the data.

**To Reproduce**
At time of opening, this happens when using zio 2.0.7.

**Expected behaviour**
No notification since latest version is already in use.

**Comment by alterationx10** [comment]
The same issue happened to me with a library I had just published/updated (to Sonatype OSSRH), a little less than 2 days ago.

<img width="583" alt="Screenshot 2023-02-05 at 9 55 04 PM" src="https://user-images.githubusercontent.com/149476/217309119-235e7d1f-65a5-4c35-ac5b-310cb778df29.png">

I checked again today, and it properly knows that `0.0.2` is the latest, and recommends `0.0.1` => `0.0.2`

**Comment by tgodzik** [comment]
Looks like we are not checking if the version is actually higher :thinking: Might have soemthing to do with coursier cache.

**Comment by lwronski** [comment]
@carlosedp @alterationx10 Thanks for reporting, it should be fixed in https://github.com/VirtusLab/scala-cli/pull/1813. 

> Looks like we are not checking if the version is actually higher 🤔 Might have soemthing to do with coursier cache.

In this case, the list of available versions should be refreshed after 24 hours. You can change this time by passing  `--ttl 0s` to Scala CLI.
