### ISSUE TITLE
allow to run a snippet when invoking the REPL

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#1854]
**Version(s)**
$ scala-cli version
Scala CLI version: 0.1.20
Scala version (default): 3.2.2

**Describe the bug**
Running a provided --script-snippet or --scala-snippet at the start of a repl session should work. (It works fine for run.)

**To Reproduce**
```
$ scala-cli repl --script-snippet 'println("hello")'
Compiling project (Scala 3.2.2, JVM)
Compiled project (Scala 3.2.2, JVM)
Welcome to Scala 3.2.2 (17.0.4.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                       
scala> 
```
Nothing is printed above, but it works for run:
```
$ scala-cli run --script-snippet 'println("hello")'
Compiling project (Scala 3.2.2, JVM)
Compiled project (Scala 3.2.2, JVM)
hello

```
**Expected behaviour**
The repl session should start by interpreting the snippet.

Use case: This can be used to e.g. import my own things to a repl session:
```
$ scala-cli repl . --script-snippet 'import mypack.*'
Welcome to Scala 3.2.2 (17.0.4.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                       
scala> MyThing  // should be visible here as mypack is imported by the snippet
```

**Comment by Gedochao** [comment]
Okay, so `--script-snippet` doesn't work as you assume for the `repl` sub-command.
There is a separate ticket for actually running something at the beginning of `repl` being invoked: #604

However, as pointed out in https://github.com/VirtusLab/scala-cli/issues/604#issuecomment-1083006861, there is a workaround for Scala 3 in the `export` syntax.

So I believe you can achieve what you want like this:
```bash
▶ scala-cli --scala-snippet 'object ToExport { def hello: String = "Hello" }; export ToExport.*'
# Compiling project (Scala 3.2.2, JVM)
# Compiled project (Scala 3.2.2, JVM)
# Welcome to Scala 3.2.2 (17.0.5, Java OpenJDK 64-Bit Server VM).
# Type in expressions for evaluation. Or try :help. 
                                                                                                                                                      
scala> hello
# val res0: String = Hello
```

Now, `--script-snippet` actually does work correctly for the `repl`. 
However, that doesn't mean it's run in the repl, but simply added to the classpath (consistently with how `--scala-snippet` and other `-*-snippet` options work).

```bash
▶ scala-cli repl --script-snippet 'println("Hello")'
Compiling project (Scala 3.2.2, JVM)
Compiled project (Scala 3.2.2, JVM)
Welcome to Scala 3.2.2 (17.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                       
scala> snippet_sc.main(Array.empty)
Hello
```

**Comment by bjornregnell** [comment]
Aha. Thanks. So I was not really understanding this from the docs...

The use case of allowing things to be visible from your top-level package etc when firing up the repl is quite nice to have. 

Perhaps include ỳour nice workaround above in docs at least? But export does not work for packages, only objects...

**Comment by bjornregnell** [comment]
So if it's a feature and not a bug then the docs should be updated and eagerly looking forward to https://github.com/VirtusLab/scala-cli/issues/604 :)

**Comment by Gedochao** [comment]
I wonder if the `export` syntax shouldn't be expanded to cover exporting top level packages, rather than working around it with Scala CLI...
well, regardless how it'll be handled, let's track it under #604, I'm closing this as duplicate
