### ISSUE TITLE
Allow packaging a Scala.js library with no main method

### ISSUE THREAD

**Issue by davesmith00000** [VirtusLab/scala-cli#1870]
Apologies if this already exists or there is an open issue already. I had a good look around but couldn't find anything.

**Is your feature request related to a problem? Please describe.**
When packaging Scala.js libraries that will be used or initialised by JavaScript calling an exported function, the requirement to provide a main method is undesirable.

**Describe the solution you'd like**
Provide a flag/directive to the Scala.js packager to ignore the requirement for a main method, similar to the scala.js sbt setting: `scalaJSUseMainModuleInitializer := false`.

**Describe alternatives you've considered**
I'm trying out using a blank `@main def main: Unit = ()` function as a workaround. Not ideal but it might do the job for now.

**Additional context**
In my case, an [Indigo](https://indigoengine.io/) game is run by JavaScript calling a `launch(...)` method where you can supply arguments like which element the game should attach itself too, and config flags and so on. No main method required.

**Comment by lwronski** [comment]
Thanks for reporting @davesmith00000, Do you expect something like this snippet:
```
$ cat Hello.scala
import scala.scalajs.js.annotation._

@JSExportTopLevel("Hello")
object Hello:
  @JSExport
  def helloWorld: String = "Hello World"

```

can it be packed by `scala-cli`:

```
$ scala-cli package Hello.scala --js 
Compiling project (Scala 3.2.2, Scala.js)
Compiled project (Scala 3.2.2, Scala.js)
Wrote /Users/lwronski/projects/scala-cli/Hello.js, run it with
  node ./Hello.js
```

and generate the file `Hello.js`, which contains the exported function `helloWorld`:
```
Object.defineProperty($c_LHello$.prototype, "helloWorld", {
  "get": (function() {
    return "Hello World"
  }),
  "configurable": true
});
```

Is this good enough for you? Is this what you mean?

**Comment by davesmith00000** [comment]
That looks like the sort of thing I meant, I'll try it out later and report back - thanks!

**Comment by armanbilge** [comment]
@lwronski the JS file should also contain `Hello = $m_LHello$();`, corresponding to `@JSExportTopLevel("Hello")`. Otherwise, that looks correct to me 👍

**Comment by lwronski** [comment]
I need to open a PR with my changes, and then it will be available in the `nightly` version.

Before implementing the fix, I would like to receive confirmation that it resolves your issue. I am not familiar with Scala.js, which is why I am asking.

@armanbilge Right, Hello.js contains `Hello = $m_LHello$();`.

**Comment by davesmith00000** [comment]
Hi,

So, I don't know how to get the nightly version but with `1.0.0-RC1`, I don't get the same behaviour as you, with the example you provided. It doesn't even get as far as reporting that it has written a JS file (and indeed, it hasn't created one):

```
scala-cli --power package Hello.scala --js
Starting compilation server
Downloading compilation server 1.5.6-sc-4
Downloading Scala.js CLI
Compiling project (Scala 3.2.2, Scala.js)
Compiled project (Scala 3.2.2, Scala.js)
[error]  No main class found
```

Exit code `1`.

Is there any other information I can provide for you? Am I doing something wrong?

**Comment by davesmith00000** [comment]
Maybe I misunderstood. In your first message I thought you were saying that it should work already, which is why I tested it, but I looked over the PR and maybe you meant it will work now in the nightly version?

Also I liked how you did that test in the PR, wondering if I can steal your approach! 😁

**Comment by lwronski** [comment]
> So, I don't know how to get the nightly version but with `1.0.0-RC1`

If you want to run the `nightly` version, you should pass the `--cli-version` parameter:

```
scala-cli --cli-version nightly --power package Hello.scala --js
```

> Maybe I misunderstood. In your first message I thought you were saying that it should work already, which is why I tested it, but I looked over the PR and maybe you meant it will work now in the nightly version?
 
Yes. For now it works only with the nightly version, but from the next release it will be available in the stable version as well.

> Also I liked how you did that test in the PR, wondering if I can steal your approach! 😁

sure, I don't mind if you steal this approach 😁

**Comment by davesmith00000** [comment]
Thank you kindly @lwronski, can confirm that works correctly as long as you also include `--js-module-kind common`. :+1:
