### ISSUE TITLE
Typo in using directive makes following directives ignored

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/scala-cli#1888]
**Version(s)**
0.2.0

**Describe the bug**
A typo in `using` in a using directive breaks the parser so that all the directives in the following lines are ignored.

**To Reproduce**
Try to compile the following code:
```scala
//> usnig dep "com.lihaoyi::pprint:0.7.0"
//> using scala "2.13.10"

object Test {
  val symbol = 'abc
}
```

```//> using scala "2.13.10"``` is ignored and the default scala version is used instead of `2.13.10`

**Expected behaviour**

At least the directive with the typo should be ignored and the remaining directives should be parsed correctly.
Additionally we could emit a warning for the typo itself.

**Comment by Gedochao** [comment]
Duplicate of #1636, should be tracked there.
