### ISSUE TITLE
Scala.js 1.13.0 is not supported

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#1893]
**Version(s)**

```
$ scala-cli --version
Scala CLI version: 0.2.0
Scala version (default): 3.2.2
```

**Describe the bug**

```scala
//> using platform "js"
//> using jsVersion "1.13.0"

@main def main = ()
```

```
[error]  Error downloading io.github.alexarchambault.tmp:scalajscli-1.13.0_2.13:1.1.3-sc1
  not found: /home/gitpod/.ivy2/local/io.github.alexarchambault.tmp/scalajscli-1.13.0_2.13/1.1.3-sc1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/io/github/alexarchambault/tmp/scalajscli-1.13.0_2.13/1.1.3-sc1/scalajscli-1.13.0_2.13-1.1.3-sc1.pom
  not found: /home/gitpod/.cache/scalacli/local-repo/v0.2.0/io.github.alexarchambault.tmp/scalajscli-1.13.0_2.13/1.1.3-sc1/ivys/ivy.xml
  No fallback URL found
```

**Expected behaviour**

Scala.js 1.13.0 was released more than a month ago and many published libraries have upgraded to it, so they are now impossible to use with scala-cli. How can the process be improved so that scala-cli does not fall so behind again?

**Comment by lwronski** [comment]
@armanbilge Thank for reporting. 

In order to prevent similar bugs in the future, we have made some changes to the versioning of `scalajs-cli`. From Scala CLI `0.2.1`, it will be possible to use newer versions of Scala.js without updating `scala-cli`.
