### ISSUE TITLE
Add `new` command?

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#19]
To create sources with skeletons of simple apps for cats-effect, zio, various testing frameworks, etc.

**Comment by sjrd** [comment]
Can we reuse [giter8](https://github.com/foundweekends/giter8) infrastructure for this, or is it tight to sbt?

**Comment by tgodzik** [comment]
It's not, we can easily run it without sbt like [we do in Metals](https://github.com/scalameta/metals/blob/03704c17b5397bd8feb4771d0bedf9a6dfe0a660/metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala).

**Comment by alexarchambault** [comment]
The idea would be to
- depend on [giter8](https://github.com/foundweekends/giter8) from Scala CLI
- add a new command called `new`, calling giter8 methods to generate a new project
- create simple templates for Scala CLI (see [this one](https://github.com/scala/scala-seed.g8) for an example of a giter8 template, and [the examples](https://github.com/VirtuslabRnD/scala-cli/tree/45f926a95ce09d51070b12e6b2bc9a3f16b23b35/examples) for inspiration, maybe the Scala CLI could have a shell script or bat script to package it for example)

**Comment by SethTisue** [comment]
It was noted on Discord that a user looking for a `new` command might simply be unaware that `touch foo.scala; scala-cli setup-ide .` is sufficient to get going with.
