### ISSUE TITLE
Request inclusion of https://s01.oss.sonatype.org in sonatype:snapshots

### ISSUE THREAD

**Issue by jackkoenig** [VirtusLab/scala-cli#1902]
**Is your feature request related to a problem? Please describe.**

Sonatype accounts created after Feb 2021 are required to use https://s01.oss.sonatype.org which is not searched as part of `sonatype:snapshots`.

**Describe the solution you'd like**

Would it be possible to include https://s01.oss.sonatype.org as a default search location when specifying `using repository "sonatype:snapshots"`?

**Describe alternatives you've considered**

We can, of course, continue using the full repository path: `using repository "https://s01.oss.sonatype.org/content/repositories/snapshots"`, it just seems to me that this is going to be a common repository choice for people going forward.

**Additional context**

**Comment by MaciejG604** [comment]
@jackkoenig It's also possible to use `//> using repository "sonatype-s01:snapshots"`, but maybe searching these two could be the default with `sonatype:snapshots`.

**Comment by jackkoenig** [comment]
>  It's also possible to use //> using repository "sonatype-s01:snapshots",

That is better at least!

> but maybe searching these two could be the default with sonatype:snapshots.

I do still think that `sonatype:snapshots` should search both. It's not like regular sonatype vs. sonatype-s01 is a choice that anyone wanted to make--it's purely a function of when the organization got their sonatype account. I am not certain of this but that even implies to me that organization collisions are impossible--unclear if that is true though.
