### ISSUE TITLE
Create a directive to exclude specific transitive dependencies

### ISSUE THREAD

**Issue by carlosedp** [VirtusLab/scala-cli#1918]
**Is your feature request related to a problem? Please describe.**
I had a problem in a project where Mill/SBT were resolving a wrong transitive dependency. With Mill/SBT we can exclude this dep in the build file.

Ref: https://github.com/vitaliihonta/zio-temporal/issues/29

**Describe the solution you'd like**

Create a directive (or a flag in the specific directive) to exclude some transitive dependencies like: https://com-lihaoyi.github.io/mill/mill/Library_Dependencies.html#_excluding_transitive_dependencies

Maybe something like:

```
//> using lib.exclude "("$com.google.protobuf:protobuf-java")"
```

**Describe alternatives you've considered**

I don't know a solution to this in scala-cli

**Comment by Gedochao** [comment]
This can already be achieved with the `exclude` parameter in the `//> using dep` directive.
The syntax looks like this:
```scala
//> using dep "org::name:version,exclude=org%%name"
```

So for example, to exclude `sourcecode` from `pprint`:
```scala
//> using dep "com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%%sourcecode"
```

The relevant docs have already been added in #1892 and should appear on the docs website after the next release (#1908)
For now, you can temporarily refer here: 
https://github.com/VirtusLab/scala-cli/blob/main/website/docs/guides/dependencies.md

**Comment by carlosedp** [comment]
Oh, nice... my bad I didn't find this before opening the issue.
Thanks Piotr!
