### ISSUE TITLE
scala-cli native image doesn't support Json-RPC `/cancelRequest`

### ISSUE THREAD

**Issue by rochala** [VirtusLab/scala-cli#1923]
**Version(s)**
Latest nightly dd17c7e

**Describe the bug**
Currently scala-cli doesn't support cancellation of tasks, to be more precise `/cancelRequest` is never read by the server.

**To Reproduce**
Try to cancel any request, e.g. compilation via BSP with scala-cli native image, and see that no request was ever received / read by the server.
 
**Expected behaviour**
The request should be read and handled properly, as it is for scala-cli JVM version

**Comment by Gedochao** [comment]
Seems to be already covered on Scala CLI's side.
