### ISSUE TITLE
Scalafmt silently fails

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#193]
https://github.com/VirtusLab/scala-cli/runs/3824783177

**Comment by alexarchambault** [comment]
That's because of https://github.com/VirtusLab/scala-cli/pull/171 I think. I added some scalafix config in `.scalafmt.conf`.

Weird that scalafmt silently fails this way though. It's the same thing when adding some Scala 3 files, without specific dialect adjustments.
