### ISSUE TITLE
Provide way to get "the name of this script" (like $0 in Bash)

### ISSUE THREAD

**Issue by jackkoenig** [VirtusLab/scala-cli#1937]
**Is your feature request related to a problem? Please describe.**

The basic problem is wanting to print a "usage message" whenever someone misuses a scala-cli script. I'm looking for the equivalent of `$0` in the following bash script:
```bash
$ cat t/script.sh 
#!/usr/bin/env bash

if [[ "$#" -ne 1 ]]; then
  echo "Requires exactly 1 argument!"
  echo "Usage: $0 <file>"
fi

$ ./t/script.sh 
Requires exactly 1 argument!
Usage: ./t/script.sh <file>
```

**Describe the solution you'd like**

I don't really care what the API is, just something that gets the current script name. I think there is subtly in making sure that the path given is relative to the current working directory of the shell invoking the script, and also making it easy to just get the script name (without directory) if desired as well.

**Describe alternatives you've considered**

I could elide the name of the script in "Usage" messages but I think it would look more professional and be more useful to have it.

**Additional context**

Discussed a little with @lwronski on Scala Discord

**Comment by lihaoyi** [comment]
Sounds like you want [`sourcecode.File()` or `sourcecode.FileName()`](https://github.com/com-lihaoyi/sourcecode#overview)?

**Comment by jackkoenig** [comment]
Good suggestion @lihaoyi! That does provide a decent solution. Full example:
```scala
//> using scala "2.13.10"
//> using lib "com.lihaoyi::sourcecode:0.3.0"

if (args.length != 1) {
  val usage =
    s"""Requires exactly 1 argument!
       |Usage: ${sourcecode.FileName()} <file>
     """.stripMargin
  System.err.println(usage)
  System.exit(1)
}

println(args.toList)
```

Unfortunately `File()` doesn't work so well with `.sc`, it gives the path to desugared Scala file: `/Users/jackk/work/scala-cli-experiment/.scala-build/project_73fee2a559-63c91e59d6/src_generated/main/script.scala`

But at least `FileName` gives a reasonable solution for the time being.

I still think it would be best if Scala-cli were to:
1. Have this as a built-in just for discoverability reasons, super useful for scripting
2. Make it work for `.sc` files
3. Have some built-in sugar to provide relative paths, ideally this could be automatically derived from how the user actually invoked the Script, whether it be as an argument to `scala-cli` or using a shebang

**Comment by lwronski** [comment]
@jackkoenig Thanks for reporting, I think it should be handled in `scala-cli`, and it is not too difficult to implement a solution.

I think, it can be added new `def` [here](https://github.com/VirtusLab/scala-cli/blob/14155cd00a481e48d6533fd09d979f44e561817c/modules/build/src/main/scala/scala/build/internal/CustomCodeWrapper.scala#L57). And the name of file is available [here](https://github.com/VirtusLab/scala-cli/blob/14155cd00a481e48d6533fd09d979f44e561817c/modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala#L74).
