### ISSUE TITLE
Switch from Scala String + comma separated values syntax to whitespace delimited list 

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1954]
**Is your feature request related to a problem? Please describe.**
To improve the ability to copy-paste snippets, such as compiler options.

**Describe the solution you'd like**
implement changes in the directives parser so that 
```scala
//> using options "-Xasync", "-Xfatal-warnings"
```
can be written as
```scala
//> using options -Xasync -Xfatal-warnings
```
Quotes can still be used for when a value needs to include whitespace, with the same escape characters for scala strings.

Here is a larger example:
```scala
//> using scala 3.2.2
//> using toolkit latest
//> using options -Xfatal-warnings -Yexplicit-nulls -Ysafe-init -source:future
//> using dep com.lihaoyi::cask:0.9.0
//> using some.key "I have spaces"
```

We do not anticipate issues in adapting [scala/vscode-scala-syntax](https://github.com/scala/vscode-scala-syntax) to support the new syntax. Additionally, values are still of `string` type.

**Describe alternatives you've considered**
no alternative considered.

**Additional context**
Since directives will not become scala syntax, there is no need to reuse the same rules as the scala parser.

_Discussed at the Scala Tooling Summit March 2023_

**Comment by sjrd** [comment]
Bringing some additional associated spec that we discussed:

* For any value that does not immediately start with a `"`:
  * They cannot contain any `"` until the next whitespace
  * All other characters, including backslash, are taking *verbatim*.
* For values that start with a `"`:
  * They follow Scala syntax for single-line single-quoted strings
  * Including backslash-based escapes

**Comment by bjornregnell** [comment]
This is a very nice simplification for newcomers!
