### ISSUE TITLE
Change TextEdit to WorkspaceEdit for actionable diagnostics

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#1957]
**Is your feature request related to a problem? Please describe.**
There is an ongoing work around the compiler to introduce actionable diagnostics and the consensus is that WorkspaceEdit from LSP spec would be much more powerful.

**Describe the solution you'd like**
Change TextEdit to WorkspaceEdit and also make a fallback mechanism in Metals.

**Comment by gabro** [comment]
since we're at it, it would also be good to nest it under a key like `workspaceEdit` instead of have it at the top level

**Comment by ckipp01** [comment]
Just a heads up so I don't step on anyone's toes. I'm working on this right now.

**Comment by tgodzik** [comment]
This is now fixed! Thanks @ckipp01
