### ISSUE TITLE
introduce a `exclude` file directive

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#1960]
**Is your feature request related to a problem? Please describe.**
Having a way to signal that a file should not be treated as part of the wider directory, so that it can be skipped when compiling a directory.

_related issues for multiple .scala files in a directory:_
- what if you want them to be part of the same project
- what if you want each one to be independent
- what if you want to do some of both
- what about subdirectories

**Describe the solution you'd like**
- Introduce a `//> using standalone` directive.
- Scala CLI should treat a standalone file as a standalone project, and not part of its enclosing directory.
- Scala CLI should skip standalone files when compiling a directory.
- A standalone file can still use definitions from other files with the `//> using file` directive.
- forbid `// using file` in non-standalone files
- `scala compile foo.scala`, where `foo.scala` is not standalone, implies compiling the parent directory as a scala-cli project

**Describe alternatives you've considered**
N/A

**Additional context**

original quote from @sjrd
> Introduce a //> using standalone directive. It would indicate that a .scala file is a standalone project, as opposed to being part of the project of its enclosing directory. When compiling/running such a file, only that file gets compiled and run (possibly with using file imports that it contains). It would not be affected by any other file in the same directory. Shebang may imply standalone.
>
>When compiling/running a file that is not standalone, we always compile the project defined by its enclosing directory. That project contains all non-standalone files in the directory and subdirectories. For running, we run the main method contained in the specified file (so there can be multiple entry points, each with its main method, that use common utils in the same project). using file imports would be forbidden in non-standalone files, since they already, automatically have access to all other non-standalone files in the same directory.
>
>Trying to compile/run a file that is not in the intended root of the project would always consider that file parent's directory as the root. So that would typically not compile or otherwise not do the "right" thing, whatever may be considered "right" for that scenario.

_Discussed at the Scala Tooling Summit March 2023_

**Comment by Gedochao** [comment]
This shouldn't be done via a `using` directive, since it applies to a single file, similar to the (currently experimental and potentially to be deprecated) `using target.*` directives.
Also, we don't consider this strictly necessary, since this can be easily worked around (i.e. by putting stuff in separate directories).

Since this change might be controversial, I'd recommend proposing this as a SIP.

**Comment by tgodzik** [comment]
After some further discussions and an additional problem statement by @Kordyjan we think a better solution is to have an `exclude` directive, which could be defined for example in `project.scala`. 

Examples:
```
//> using exclude *.sc
//> using exclude examples/
//> using exclude examples/*.sc
```

Having a standalone directive would mean we would need to put it in every single file we would want to exclude.

Opinions? Would that be satisfactory?

**Comment by Kordyjan** [comment]
There are two important questions:
- should `*.sc` be excluded by default? (IMO they should)
- how do `using file` and `using exclude` should interact?

What should happen if a user writes directives like this:

```scala
//> using exclude examples
//> using file examples/necessary
//> using exclude *.data.scala
```

Should the file `examples/necessary/some.data.scala` be included in the compilation or not?

**Comment by tgodzik** [comment]
> should *.sc be excluded by default? (IMO they should)

I don't think it should unless a lot of users find this an issue.

> how do using file and using exclude should interact?

That is a good questions, maybe `file` should have precedence over exclude? So we in this case:
We include everything in `examples/necessary/` while excluding everting else in examples and any other `*.data.scala` file.

If you only want to include that single file you can do `//> using file examples/necessary/some.data.scala` instead of `//> using file examples/necessary/`

**Comment by tgodzik** [comment]
Or alternatively we don't allow `file` and `exclude` in a single scope. The logic here might never be clear to a user.

**Comment by lwronski** [comment]
> Or alternatively we don't allow file and exclude in a single scope. The logic here might never be clear to a user.

I would prefer the idea of precedence `file` over `exclude` directive.

**Comment by mbovel** [comment]
> * should `*.sc` be excluded by default? (IMO they should)

I think that would make sense to me. If I have a set of scripts in a folder (for example `download.sc` and `process.sc`), I want them to be independent by default; be separate targets and not influence other targets.

**Comment by Gedochao** [comment]
> > * should `*.sc` be excluded by default? (IMO they should)
> 
> I think that would make sense to me. If I have a set of scripts in a folder (for example `download.sc` and `process.sc`), I want them to be independent by default; be separate targets and not influence other targets.

Hey, we'd rather not do that, as we want it to still be possible to run a folder containing a script.
Excluding `*.sc` would make it necessary to pass a script explicitly as an input to run it.
