### ISSUE TITLE
Some tests are not being executed

### ISSUE THREAD

**Issue by KuceraMartin** [VirtusLab/scala-cli#1976]
**Problem:**
On the latest master, when I run `./mill 'build-module.test' 'scala.build.options.*'`, I would expect the [ConfigMonoidTest](https://github.com/VirtusLab/scala-cli/blob/main/modules/options/src/test/scala/scala/build/options/ConfigMonoidTest.scala) to be executed but it is not.

**Solution:**
Either move `ConfigMonoidTest` from `modules/options/src/test/scala/scala/build/options` to `modules/build/src/test/scala/scala/build/options`, or setup tests so that files in the former directory will also get executed. (I am not sure which is the preferred option)

**Comment by lwronski** [comment]
Hi @KuceraMartin, thanks for reporting. To run unit tests for the `options` module, run the following command:

```
./mill 'options.test' 'scala.build.options.*'
```

To run unit tests for a different module, set `module_name` to the module name:

```
./mill '{module_name}.test' '*'
```

**Comment by KuceraMartin** [comment]
@lwronski Thanks for the explanation and for updating the docs.

Unfortunately, it seems to me that the tests are also not getting executed when running `./mill -i unitTests` which is how unit tests are run here on the CI. In https://github.com/VirtusLab/scala-cli/pull/1963 I intentionally tried to leave one failing test and even on the CI it only started failing after I moved the file to the `build` module.

I think it would be good to either fix this on the CI or to move the `ConfigMonoidTest` to the build module.

**Comment by lwronski** [comment]
> Unfortunately, it seems to me that the tests are also not getting executed when running ./mill -i unitTests which is how unit tests are run here on the CI. In https://github.com/VirtusLab/scala-cli/pull/1963 I intentionally tried to leave one failing test and even on the CI it only started failing after I moved the file to the build module.

Yes, you are right - good catch! I will reopen this issue
