### ISSUE TITLE
Add `update` command

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#20]
Allowing to bump dependencies in one's `scala` project.

Ideally, it would support the same kind of magic as [scala-steward](https://github.com/scala-steward-org/scala-steward), with scalafix rules for some version bumps, updating the names of some dependencies when needed, etc.

**Comment by sjrd** [comment]
scala-steward is pretty advanced, especially when fix rules are involved. Can we use/reuse it for this purpose?

**Comment by alexarchambault** [comment]
> Can we use/reuse it for this purpose?

That's how I would envision it.

**Comment by alexarchambault** [comment]
To add to the initial description, this command would allow:
- to update projects not pushed to GitHub
- to setup GitHub actions to update private projects (we'd need to have options to open GitHub issues for that)

**Comment by Gedochao** [comment]
This should be handled in #1791, closing this ticket
