### ISSUE TITLE
Slow for repeat run x.scala

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#2010]
![image](https://user-images.githubusercontent.com/501740/230186511-cb6c3259-91db-4a2b-860a-c20b93ead789.png)

I think the second run should be faster if the file is not changed.

**Comment by Gedochao** [comment]
Seems like a duplicate of #1807, let's track the issue there.
Also, make sure you run the newest version, there's been some performance fixes included in `v1.0.0-RC1` which should make it a bit better. (refer to https://github.com/VirtusLab/scala-cli/pull/1939)

**Comment by He-Pin** [comment]
@Gedochao I am using the latest 1.0.0-RC1
