### ISSUE TITLE
Scoop still have the old version of scala-cli 0.2.1

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#2011]
![image](https://user-images.githubusercontent.com/501740/230274059-6726c3a4-3620-4a06-b2fa-2d8434869309.png)

**Comment by lwronski** [comment]
@He-Pin Thanks for reporting, can you try to install scala-cli running the following command:
```
scoop install scala-cli@1.0.0-RC1
```

does it work?

**Comment by He-Pin** [comment]
it works, thanks @lwronski
