### ISSUE TITLE
First-class support for "alternative" toolkits

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#2018]
**Is your feature request related to a problem? Please describe.**

Inspired by the [Scala Toolkit](https://github.com/scala/toolkit), we have created a [Typelevel Toolkit](https://typelevel.org/toolkit/). cc @toniogela

**Describe the solution you'd like**

```
//> using toolkit "typelevel:latest"
```

Or something similarly simple e.g.:
```
//> using kit "typelevel:latest"
```

**Describe alternatives you've considered**

Currently we are doing:

```
//> using lib "org.typelevel::toolkit::0.0.3"
```

**Comment by tgodzik** [comment]
I think probably `//> using toolkit "typelevel:latest"` would be best. It shouldn't add too much on top of the main toolkit.
