### ISSUE TITLE
Specification differs from implementation

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#2048]
**Version(s)**

1.0.0-RC1

**Describe the bug**

The [specification of using directives](https://docs.scala-lang.org/sips/scala-cli.html#using-directives) mentions the following syntax:

~~~ scala
//> using target { platform "jvm"; scope "test" }
~~~

However, it has been decided to not support that syntax.

**Expected behaviour**

The specification should be updated to reflect what has been decided.

**Comment by tgodzik** [comment]
Looks like this is correctly documented now.

**Comment by julienrf** [comment]
I don’t think this issue is solved, I still see the following in the [spec](https://docs.scala-lang.org/sips/scala-cli.html#using-directives):

![image](https://github.com/VirtusLab/scala-cli/assets/332812/4da96745-ee01-479d-91fa-784d1c448722)

**Comment by tgodzik** [comment]
Ach, forgot that the spec was on on our website. Sorry about that

**Comment by lwronski** [comment]
Fixed in https://github.com/scala/improvement-proposals/pull/64.
