### ISSUE TITLE
Multi-line comment syntax is still supported for directives

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#2049]
**Version(s)**

1.0.0-RC1

**Describe the bug**

It seems #1932 did not remove the support of multi-line directives:

~~~ scala
/*> using
  option "-Xfatal-warning"
*/
~~~

This code still compiles.

**Expected behaviour**

An error should be reported to the user, indicating what is the correct syntax to use.

Related: #2048 which also shows directives using multi-line comments.

**Comment by tgodzik** [comment]
Thanks for reporting! I am actively working on that.
