### ISSUE TITLE
Missing 'v1' tag for VirtusLab/scala-cli-setup

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#2050]
**Describe the bug**
VirtusLab/scala-cli-setup has `v1.0.0-RC1` and `v1.0` tags, but no `v1`

**Expected behaviour**
VirtusLab/scala-cli-setup should have a `v1` tag, updated upon each new v1.x releases, so that users can use it like
```yml
- uses: VirtusLab/scala-cli-setup@v1
```

**Comment by lwronski** [comment]
@alexarchambault Thanks for reporting.

`v1` tag is available now for `scala-cli-setup` github actions at https://github.com/VirtusLab/scala-cli-setup/tree/v1.
