### ISSUE TITLE
Using toolkit should add toolkit-test dependecy for test scope

### ISSUE THREAD

**Issue by szymon-rd** [VirtusLab/scala-cli#2060]
Issue in Toolkit repo: https://github.com/scala/toolkit/issues/13
Using the toolkit directive (`using toolkit ...`) should add a dependency on `toolkit-test` artifact in the test scope.
The same behavior should be present for the command line option.

**Comment by tgodzik** [comment]
Thanks for reporting! So the toolkit artifact no longer depends on toolkit test? munit dependency is completely separate?

**Comment by szymon-rd** [comment]
Yes. The munit is only in the Toolkit-test now.

**Comment by Gedochao** [comment]
Okay, so here's what we want to do:

```scala
//> using toolkit latest
```
The standard `using toolkit` directive will only include the standard `toolkit`, no `toolkit-test`.

```scala
//> using test.toolkit latest
```
The current test-scope `using test.toolkit` directive will include the `toolkit-test` dependency for the test scope.

Additionally, including the standard `using toolkit` directive in a test-scope source will include both `toolkit` and `toolkit-test` (in test-scope only).

cc @szymon-rd

**Comment by szymon-rd** [comment]
@Gedochao  I believe it could be a bit confusing. As I understand the syntax `test.xyz`, it sets the setting for a scope. I feel like making the behavior of a directive dependent on the scope could be a bit misleading, or are there any other cases like that?  Also, it adds additional complexity, as it makes it possible to run into an unexpected case (using only toolkit-test in test scope). I think that in virtually all cases when one would want to use toolkit, he would either:
 - Want to use the toolkit in main scope and toolkit with toolkit-test in test scope.
 - Use toolkit with toolkit-test in test scope, but no toolkit in the main scope.

In no cases, would one want to use only `toolkit-test` in the test scope, without the `toolkit`.

Therefore, I propose that:
```
//> using toolkit latest
```
 - When in a file in the main scope: Would add toolkit to the main scope, and toolkit-test to test scope (with toolkit from main)
 - When in a file in test scope: Would add toolkit and toolkit-test to test scope

```
//> using test.toolkit latest
```
 - Adds toolkit and toolkit-test to test scope

I think this combination makes the usage the simplest and minimizes confusion.

**Comment by tgodzik** [comment]
> In no cases, would one want to use only toolkit-test in the test scope, without the toolkit.

Ach I thought that toolkit-test depends on toolkit, that changes things a bit.

**Comment by armanbilge** [comment]
> Ach I thought that toolkit-test depends on toolkit, that changes things a bit.

Yeah, I also wondered if that should be the case, but I couldn't think of any justification for it, besides that it probably wouldn't hurt.

**Comment by szymon-rd** [comment]
I think that the best approach would be to make the integrations work in a way that it doesn't matter, if nothing is sacrificed by that. (It removes one requirement from toolkits specification). Right now the toolkit-test doesn't depend on toolkit, but it may in the future.

**Comment by tgodzik** [comment]
Ok so if test-toolkit doesn't depend on toolkit the we should do as suggested by @szymon-rd .

Any other opinions?
