### ISSUE TITLE
Better error message when you forget a `,` with using directives

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#2075]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but just a general situation that I think could cause some confusion. Let's for example say you have the following using directive:

```scala
//> using options "-no-indent" "-rewrite"
```
If you try this, you'll get the following:

```
Diagnostics:
Expected new line after the using directive, in the line; but found string literal: -rewrite
```

When you pause and think about it, the message _sort of_ make sense since it's thinking you're done with your using directives and expects a new line, but in reality, you just forgot a `,`.

**Describe the solution you'd like**
I think to avoid any confusion with the above, it'd be great to just detect this. It should be easy enough to know that you just processed a valid value and then you're encountering another string, but forgot the `,`. So an error like this would maybe be clearer:

```
Diagnostics:
Detected another valid scalacOption, "-rewrite".  If you're trying to use this you probably forgot a "," between your values.
```

_Even better_, scala-cli can just suggest a fix for this with an actionable diagnostic!

**Describe alternatives you've considered**
Just taking a second to understand the error and adding a `,`.

**Comment by SethTisue** [comment]
https://github.com/VirtusLab/using_directives/pull/51 will allow omitting commas

**Comment by ckipp01** [comment]
> [VirtusLab/using_directives#51](https://github.com/VirtusLab/using_directives/pull/51) will allow omitting commas

Ahhhh, I missed that! I'll go ahead and close this then. Thanks @SethTisue

**Comment by tgodzik** [comment]
This has just been merged, so upcoming RC2 will support omiting comas and quotes.
