### ISSUE TITLE
Missing `using` directive for handling source jars

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#2097]
**Version(s)**
`Scala CLI version: 1.0.0-RC1`

**Describe the bug**

When using `//> using jar` directives to add a local jar into a project it seems that those jars aren't included when you look at the BSP communication about the `buildTarget.data`. This can be problematic as Metals at times will look there for certain things.

**To Reproduce**
You'll need something like this:

```scala
//> using scala "3.3.0-RC5"
//> using jvm "17"
//> using jar "./lib/core.jar"

@main def run() = println("hi")
```

You'll also need to create a `lib/` dir and stick a jar in there or just make a `core.jar` dummy. If you then look at the `bsp.trace.json` file if you're using Metals or trace the BSP communication in some other way you'll see this:

```
[Trace - 05:12:47 pm] Received response 'workspace/buildTargets - (2)' in 8ms
Result: {
  "targets": [
    ... I removed the test target as it isn't relevant
    {
      "id": {
        "uri": "file:/Users/ckipp/Documents/scala-workspace/generative/.scala-build/?id\u003dproject_a67e43e310"
      },
      "displayName": "project_a67e43e310",
      "baseDirectory": "file:///Users/ckipp/Documents/scala-workspace/generative/.scala-build/",
      "tags": [...],
      "languageIds": [...],
      "dependencies": [],
      "capabilities": {...},
      "dataKind": "scala",
      "data": {
        "scalaOrganization": "org.scala-lang",
        "scalaVersion": "3.3.0-RC5",
        "scalaBinaryVersion": "3.3",
        "platform": 1,
        "jars": [
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.0-RC5/scala3-compiler_3-3.3.0-RC5.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.0-RC5/scala3-interfaces-3.3.0-RC5.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.0-RC5/scala3-library_3-3.3.0-RC5.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.0-RC5/tasty-core_3-3.3.0-RC5.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.4.0-scala-1/scala-asm-9.4.0-scala-1.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar",
          "file:///Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar"
        ],
        "jvmBuildTarget": {
          "javaHome": "file:///Users/ckipp/.sdkman/candidates/java/17.0.5-tem/"
        }
      }
    }
  ]
}
Error: null
```

Notice that in `data.jars` you don't see the `core.jar` I'd expect to see.

**Expected behaviour**
I'd expect that jars added in this way are reported in `data.jars`.

**Comment by Gedochao** [comment]
@ckipp01 it seems that `workspace/buildTargets`' `data.jars` only contains the compiler classpath... I don't think the custom jar should go there.
However, what did you need this for?

is this about the source jar issue you [mentioned on Discord](https://discord.com/channels/632150470000902164/901153021638082660/1104787179919646740)?

I think source jars should be passed with the `--extra-source-jar` option.
It seems there should be a corresponding `using` directive, but there isn't.
I can add it, just making sure that's the root of the problem here.

**Comment by ckipp01** [comment]
🤔 hm, then I guess I misunderstood the `data.jars`. The use case I have is that I'm using the processing library, which doesn't publish their jars, so you have to download it, unzip it, and grab the jars yourself. So this ends up giving me some using directives like this:

```
//> using scala "3.3.0-RC5"
//> using jvm "17"
//> using jar "./lib/core.jar"
//> using jar "./lib/core-sources.jar"
```

However, no navigation works for the core jar, which I _assumed_ was because Metals wasn't forwarded the information about the `core-sources` jar. But maybe that was a false assumption.

**Comment by tgodzik** [comment]
> However, no navigation works for the core jar, which I assumed was because Metals wasn't forwarded the information about the core-sources jar. But maybe that was a false assumption.

That's a correct assumption, the problem is however that we don't return the source jar in the `DependencySourcesResult`, so we need to add the source jar to `resolution` section instead
