### ISSUE TITLE
mdoc-like `.md` support

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#21]

**Comment by romanowski** [comment]
@BarkingBad was prototyping something similar for scaladoc for migration of documentation from dotty website

**Comment by lwronski** [comment]
Duplication of https://github.com/VirtusLab/scala-cli/issues/1231

**Comment by hugo-vrijswijk** [comment]
@lwronski Would it be reasonable to reopen this? The markdown support in #1231 relates to running markdown files. While the main use-case of mdoc is having typechecked documentation. I don't know if the two are related on a technical level, but from a user point of view they are different. I also couldn't find any other open issue to track it.

Considering one of Scala CLI's strengths is how easy it is to make CLI apps or smaller-sized applications, I think typechecked documentation still falls within the scope and is very useful for open-source repos wanting to provide a typechecked readme.
