### ISSUE TITLE
Support for `BuildInfo`

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#2106]
**Is your feature request related to a problem? Please describe.**
Discussed in https://github.com/VirtusLab/scala-cli/discussions/2051

<div type='discussions-op-text'>

<sup>Originally posted by **ckipp01** April 23, 2023</sup>
I have a use case where I'm building a CLI app. A lot of times with apps like this you want to make sure you can display the version of the app via a command, and many times the value of that version is persisted utilizing a form of `BuildInfo` where based on git, or something else a file is generated and used for compilation. Is there any way to mimic something like this with `scala-cli`? All the solutions I'm coming up with request running `scala-cli` to generate a file first, and then running it again on your main project to utilize that created file. However, it'd be great if this could just be done in a single step somehow. Any ideas?</div>

**Describe the solution you'd like**
We could have a directive/command-line option exposing `BuildInfo` data in the project.
```scala
//> using build.info
```

**Describe alternatives you've considered**
This could potentially also be delivered through code generators. (see #610)

**Additional context**
See the discussions in #2051 and #610.

**Comment by Gedochao** [comment]
cc @ckipp01

**Comment by ckipp01** [comment]
👍🏼 thanks for creating this @Gedochao. At least for my specific use case just having
```scala
//> using build.info
```
Wouldn't be enough since it wouldn't really know where to pull the version from. So having #610 would also be necessary to somehow grab the version and store it in the actual build info.
