### ISSUE TITLE
Allow to use object as a script wrapper

### ISSUE THREAD

**Issue by dacr** [VirtusLab/scala-cli#2117]
**Version(s)**
Only from 1.0.0-RC2, everything is fine with previous releases.

**Describe the bug**
The script compile, then a `*** RUN ABORTED***` message is printed
![image](https://github.com/VirtusLab/scala-cli/assets/381901/610f3bf5-f26a-44f4-ab46-7343d45c7842).

*(Of course I could use the new `test.dep` and `scl test myscript.sc` approach but it should run as before the old way)*

**To Reproduce**
- KO script : 
  - https://gist.github.com/dacr/fa515384be730103dbd37e7b3815b58f  
```scala
// ---------------------
//> using scala  "3.2.2"
//> using dep "org.scalatest::scalatest:3.2.15"
// ---------------------

import org.scalatest.*, flatspec.*, matchers.*

class PiTest extends AnyFlatSpec with should.Matchers {
  "pi calculus" should "return a precise enough pi value" in {
    math.Pi shouldBe 3.14158d +- 0.001d
  }
}
org.scalatest.tools.Runner.main(Array("-oDF", "-s", classOf[PiTest].getName))
```
- OK script : 
  - https://gist.github.com/dacr/78bb969a26d7394900396fd8ebd0142b

**Expected behaviour**
running fine without this error message and with this output : 
![image](https://github.com/VirtusLab/scala-cli/assets/381901/e1b5fd12-6f50-4c14-9d95-90ce7f4ce781)

**Comment by dacr** [comment]
In the KO script, if I change the way the test is started, it runs as expected : 
```scala
//org.scalatest.tools.Runner.main(Array("-oDF", "-s", classOf[PiTest].getName))
(new PiTest).execute()
```
![image](https://github.com/VirtusLab/scala-cli/assets/381901/b3d0e838-aecc-4de7-aaee-7bfb0d14bee9)

**Comment by dacr** [comment]
This has probably a link with the classOf Operation, If I use the REPL I get : 
```
$ scl --dep "org.scalatest::scalatest:3.2.15"
Welcome to Scala 3.2.2 (17.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                                                                                                                                       
scala> import org.scalatest.*, flatspec.*, matchers.*
     | 
                                                                                                                                                                                                                                                                                       
scala> class PiTest extends AnyFlatSpec with should.Matchers {
     |   "pi calculus" should "return a precise enough pi value" in {
     |     math.Pi shouldBe 3.14158d +- 0.001d
     |   }
     | }
     | 
// defined class PiTest
                                                                                                                                                                                                                                                                                       
scala> (new PiTest).execute()
rs$line$2$PiTest:
pi calculus
- should return a precise enough pi value
                                                                                                                                                                                                                                                                                       
scala> org.scalatest.tools.Runner.main(Array("-oDF", "-s", classOf[PiTest].getName))
*** RUN ABORTED ***
  java.lang.ClassNotFoundException: rs$line$2$PiTest
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
```

So using the REPL we can see that we got `RUN ABORTED` because of a ClassNotFoundException issue.

May be a classloader issue ? wrong parent classloader ? Something scalatest is doing that is no longer compatible with the new behavior of scala-cli ?

**Comment by dacr** [comment]
For your information I've automated the execution of most of my scripts using scala-cli, and with the latest release the failure has increased quite a lot : 
![image](https://github.com/VirtusLab/scala-cli/assets/381901/70e3fcb9-1f74-44e9-9e1d-f982363a16d0)

results : 
- 1.0.0-RC1 : 19 scripts KO *(which requires some work at my side)*
- 1.0.0-RC2 : 58 scripts KO, amount them
  - 36 `RUN ABORTED` message
    - all of them are using the `org.scalatest.tools.Runner.main(Array("-oDF", "-s", classOf[TestClass].getName))` :)

So the good news is that 264 scala-cli scripts are running fine, and I didn't see any other issue related to the scala-cli 1.0.0-RC2, all new failures are only related to the `RUN ABORTED` message.

Depending on your feedback on this issue, I'll keep them as they are or rewrite them to use the `test.dep` and `scala-cli test xxx.sc`. 

I'll make more checks next week as I've some other specialized scripts I'm using at work...

**Comment by Gedochao** [comment]
It seems that the reason for this issue is the new script wrapper for Scala 3 scripts introduced in #2033.
The following replicates the problem on earlier versions:

`Main.scala`
```scala
//> using scala  "3.2.2"
//> using dep "org.scalatest::scalatest:3.2.16"

import org.scalatest.*, flatspec.*, matchers.*

class Outer {
  class PiTest extends AnyFlatSpec with should.Matchers {
    "pi calculus" should "return a precise enough pi value" in {
      math.Pi shouldBe 3.14158d +- 0.001d
    }
  }
}

object Main extends App {
  org.scalatest.tools.Runner.main(Array("-oDF", "-s", classOf[Outer#PiTest].getName))
}
```

The problem seems to be the loading of the inner class.

```bash
scala-cli --cli-version 1.0.0-RC1 Main.scala
# *** RUN ABORTED ***
```

Needs further investigation on how can we address this.
We need the new wrapper to avoid deadlocks in scripts (see #532 & #1933).

BTW. the example in the REPL (given in https://github.com/VirtusLab/scala-cli/issues/2117#issuecomment-1546627271) is actually replicable in  earlier versions of Scala CLI and may be a separate issue.

**Comment by tgodzik** [comment]
Ok, so it seems there is no way around it unless we go back to the old behaviour (but that has issues with deadlocks, so I think it's more problematic) or we provide an additional using directive to use object. Neither approach is great but I would stay with the current approach.

In the meantime, I would however suggest using a normal Scala file in this case, sorry about the inconvenience.

We can leave this open to see if more people need this fixed (please react with +1).

**Comment by SethTisue** [comment]
fwiw, I agree that these deadlocks are so common and so pernicious that it's worth prioritizing avoiding them, even if it means compromising a bit elsewhere. the deadlock-proneness of the Scala 2 REPL, before we similarly switched to class-based wrappers in Scala 2.13.2, was reported on scala/bug and elsewhere about a million times over the years, and it was often language newcomers reporting it and getting a bad impression of Scala

(for evidence, see https://github.com/scala/bug/issues/8119 and the various similar/duplicate tickets that are a link or two away)

cc @som-snytt

**Comment by som-snytt** [comment]
There is no obviously best semantics even for beginners. (Code is wrapped in a local block, or class (instance) initializer, or object initializer.) The last is definitely evil, or I meant to say, "pernicious." Also, Scala 2 did need a fix to drill down through instances of class wrappers to find values; I don't remember details.

Ideal would be to make all the regimes available, and also make it obvious which regime you're executing within.

I wonder if Scala 3 has considered making top-level `object` also exactly `lazy val` (in the package object). Then they could finally add `@static` for people who need the static (class) initialization.

I'm so grateful to everyone who is shouldering this cognitive burden now for the rest of us.

**Comment by MaciejG604** [comment]
You can now use `--object-wrapper` or `using objectWrapper` as a workaround for the mentioned problems.

**Comment by dacr** [comment]
Thanks for all, I've made all the necessary changes, and the results are good, the only remaining errors I have, are not related to scala-cli anymore, just some work in progress or networking issues : 
![image](https://github.com/VirtusLab/scala-cli/assets/381901/6c8c4af8-b829-4265-9362-b2755eda1dda)
