### ISSUE TITLE
Update to 1.0.0-RC2 triggers 'assertion failed: asTerm called on not-a-Term val <none>'

### ISSUE THREAD

**Issue by sbrunk** [VirtusLab/scala-cli#2128]
**Version(s)**
1.0.0-RC2

**Describe the bug**
After upgrading to `1.0.0-RC2` the script below fails to compile with the following error:
```
Error: Unexpected error when compiling project_8be8567734-de847ff703: 'assertion failed: asTerm called on not-a-Term val <none>'
```

System: Tried Ubuntu 23.04 and 22.04 so far

**To Reproduce**
```scala
//> using scala "3.2.2"
//> using jvm "17"
//> using lib "com.github.alexarchambault::case-app:2.1.0-M24"

import caseapp._

case class Options(
  domain: String = "development"
)

object BuildAndRegister extends CaseApp[Options] {
  override def run(options: Options, remainingArgs: RemainingArgs): Unit = {}
}
```

```bash
scala-cli compile script.sc
```

Note that the bug only appears to occur on Scala 3 in combination with a script:

```bash
scala-cli --cli-version 1.0.0-RC2 compile script.sc # error
scala-cli --cli-version 1.0.0-RC1 compile           # works
scala-cli compile --scala-version 2.13              # also works

mv script.sc script.scala
scala-cli compile script.sc # works
```

Also, if we remove the default arg in the options case class, it also works again:

```diff
case class Options(
-  domain: String = "development"
+ domain: String
)
```

I haven't been able to minimize the example further yet.

One hunch is that the new class based wrapping triggers something here as it happens only in scripts.

**Expected behaviour**
The script should compile like in earlier versions.

**Comment by Gedochao** [comment]
Probably related to #2117
I'd also bet it's because of the class wrapper, as suggested in the issue description (may need further investigation, though)

**Comment by MaciejG604** [comment]
A new flag and using directive were added for forcing the object wrapper in scripts. You can use `--object-wrapper` or `using objectWrapper` as a workaround for the mentioned problem.

**Comment by sbrunk** [comment]
Thanks for letting me know @MaciejG604
