### ISSUE TITLE
Dependency update code action corrupts dependency coordinates

### ISSUE THREAD

**Issue by keynmol** [VirtusLab/scala-cli#2131]
**Version(s)**

Built from 842ea6c368b9b12b1f2cfab407da85d0bffa8e2e

**Describe the bug**

When applying a code action for dependency update, coordinates are being broken, failing resolution

**To Reproduce**

You can see that `com` is turned into `ccom` and resolution fails.

![2023-05-22 13 00 12](https://github.com/VirtusLab/scala-cli/assets/1052965/892337dd-461e-4203-bbb4-06dca42f1bf4)

```scala
//> using lib com.softwaremill.sttp.tapir::tapir-core::1.3.0
//> using lib com.softwaremill.sttp.tapir::tapir-json-circe::1.3.0
//> using target.platform jvm, scala-native, scala-js

@main def hello = ???
```

**Expected behaviour**

Dependency coordinates are left the same, only version changed

**Comment by tgodzik** [comment]
Thanks for reporting! This might have something to do with the removoed quotes. Probably an off by one error @lwronski can you take a quick look?
