### ISSUE TITLE
Add Scala CLI to brew's `scala` installation

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#2146]
**Is your feature request related to a problem? Please describe.**
We need Scala CLI to be installed as part of the `scala` installation (under `scala`, replacing the old runner.

**Extra context**
- make sure `brew` upgrades to Scala CLI even though its version may be lower than the old `scala` runner's
- possibly could hack the `Ruby` script to install it with `cs` under the hood (?)
- worst case scenario we'll have to bump Scala CLI version to `v10.0.0`

**Comment by kiendang** [comment]
The brew version thing could be handled with [`version_scheme`](https://rubydoc.brew.sh/Formula#version_scheme%3D-class_method). See https://docs.brew.sh/Formula-Cookbook#version-scheme-changes.

**Comment by tgodzik** [comment]
> The brew version thing could be handled with [`version_scheme`](https://rubydoc.brew.sh/Formula#version_scheme%3D-class_method). See https://docs.brew.sh/Formula-Cookbook#version-scheme-changes.

Thanks! That looks like something we can use!

**Comment by MaciejG604** [comment]
Tracked under #2238
