### ISSUE TITLE
BSP + Fat JAR

### ISSUE THREAD

**Issue by Quafadas** [VirtusLab/scala-cli#2170]
**Is your feature request related to a problem? Please describe.**
Question: at $work, I cannot download zips, exe etc. Access to scala-cli is therefore through maven / fat JAR strategy as outlined in the docs.

Quodos, because that appears to work. My strategy was then to setup a .bat file, which calls the JAR, and put the .bat on path. Pretty sweet. 

bat file
```C:\temp\jdk-17.0.4\bin\java.exe -jar C:/temp/scala-cli/1.0.0/cliBootstrapped-1.0.0.jar %*```

This all worked way smoother than I expected - but running `scala-cli setup-ide .` subsequently struggled to recognise my (admittedly rather custom) setup. 

**Describe the solution you'd like**
An officially sanctioned strategy for working with metals - BSP with the fat jar strategy, i.e. under the assumption that one cannot download zip, exe or other files - all artefact resolution goes through maven.

**Describe alternatives you've considered**
Tampering with scala-cli.json to make it look something like this. 

```
  "argv": [
    "C:\\temp\\jdk-17.0.4\\bin\\java.exe",
    "-jar",
    "C:/temp/scala-cli/1.0.0/cliBootstrapped-1.0.0.jar",
    "bsp",
    "--json-options",
    "C:\\temp\\simple\\.scala-build\\ide-options-v2.json",
    "C:\\temp\\simple"
  ],
```

**Additional context**
I'm willing to assume, that this isn't a super common requirement, There appears to be a workaround, which I've outlined above, and I wouldn't therefore percieve this to be a super high priority. This issue was filed in response to this conversation on discord. 

https://discord.com/channels/632150470000902164/901153021638082660/1113069515404750908

**Comment by MaciejG604** [comment]
Hi @Quafadas, could you try renaming the downloaded fat jar to `cliBootstrapped-1.0.0.bat`? You should then be able to run it directly, and the `scala-cli.json` will work as expected with no changes.

**Comment by Quafadas** [comment]
@MaciejG604 thanks for the hint. From what I can tell, that should have worked. 

Unfortunately, I hit on a seperate snag in which I can't convince the computer to detect a non-ancient version of java by default. The strategy above solved that problem coincidentally, by specifying the JVM I waned it to use. 

In other words, I believe your solution worked, but I can't actually prove it. Apologies. If / when I manage to get round the secondary ancient java problem, I'll report back.

**Comment by MaciejG604** [comment]
Tested this solution on a Windows machine and it works, with the `cliBootstrapped-1.0.0.jar` renamed to `cliBootstrapped-1.0.0.bat` I managed to get BSP configured for IDE by simply running `./cliBootstrapped-1.0.0.bat setup-ide .`

With regards to the java version problem, I would say the workaround you have found is the only thing that can be done in this case.

@Quafadas shall we close this issue for now?

**Comment by Quafadas** [comment]
Thanks for looking, and I am sorry I couldn't test it further.  Agreed, that this should be closed for now.
