### ISSUE TITLE
Docs: How do you full link a Scala.js app when packaging?

### ISSUE THREAD

**Issue by davesmith00000** [VirtusLab/scala-cli#2184]
**Version(s)**
1.0.0, but may not be relevant.

**Describe what needs to be done and why**
Missing docs on how to package a Scala.js file file that has been compressed by the closure compiler.

**Additional context**
Equivalent to `sbt fullLinkJS`. I'm sure this is doable I just can't find any information on it. I can add the docs for you if you give me the incantation. :smile:

**Comment by tgodzik** [comment]
Does `scala-cli package --js-mode release` option work for you? That's what I found when doing ` scala package --help-js  `

**Comment by tgodzik** [comment]
We no have more self explanatory options
