### ISSUE TITLE
Should we automatically add extensions to package command results on Windows if `-o` is used?

### ISSUE THREAD

**Issue by MaciejG604** [VirtusLab/scala-cli#2186]
Since Windows interprets the file type using its extension, should we add them whenever the user calls the `package` function **that creates a runnable** file and the `-o` flag is given?
E.g.
```
scala-cli --power package Hello.scala -o hello
./hello
```

When I tested this snippet, after running the second line, the system asked me which program do I want to use to run the file `hello`. Using `-o hello.bat` instead worked.

Another thing:
```
scala-cli --power package Hello.scala --assembly
./hello.jar
```
This does not look like it runs the program from `Hello.scala`, probably due to the way `.jar` files are being used on Windows.

Any more feedback from active Windows users are very welcome!

**Comment by Gedochao** [comment]
Perhaps logging a warning would be enough? 
Since the user is passing the output explicitly with `-o`, it makes sense to follow that, but maybe warn that adding an extension may be a good idea...
