### ISSUE TITLE
Markdown sources filename cannot start with a number

### ISSUE THREAD

**Issue by JD557** [VirtusLab/scala-cli#2205]
**Version(s)**
1.0.1

**Describe the bug**

Trying to run a markdown source whose filename starts with a number fails.

**To Reproduce**

1. Create a file named `01-intro.md`
2. Add a code block, for example:

<pre>
# Introduction
    
Welcome to the tutorial!
    
```scala
println("foo")
```
</pre>

4. Run it with `scala-cli --power run 01-intro.md`

The result is:
```
[error] an identifier expected, but integer literal found
[error] object 01-intro_md { @annotation.nowarn("msg=pure expression does nothing") def main(args: Array[String]): Unit = { Scope; }
[error]        ^
```

**Expected behaviour**

The code should execute (for example, `01-intro.sc` works just fine)

**Comment by JD557** [comment]
I think this just needs something like

```diff
diff --git a/modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala b/modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala
index 56e6b843..874e242f 100644
--- a/modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala
+++ b/modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala
@@ -37,7 +37,7 @@ object MarkdownCodeWrapper {
     val (pkg, wrapper) = AmmUtil.pathToPackageWrapper(subPath)
     val maybePkgString =
       if pkg.isEmpty then None else Some(s"package ${AmmUtil.encodeScalaSourcePath(pkg)}")
-    val wrapperName = s"${wrapper.raw}_md"
+    val wrapperName = Name(s"${wrapper.raw}_md").backticked
     (
       wrapScalaCode(markdown.scriptCodeBlocks, wrapperName, maybePkgString),
       rawScalaCode(markdown.rawCodeBlocks),
```

Although I can't currently send a PR as I'm having some trouble compiling scala-cli on my machine.

Also, I'm not sure if `MarkdownCodeWrapper` should extend `CodeWrapper` 🤔

**Comment by lwronski** [comment]
Hi @JD557, thank you for reporting the issue and suggesting changes. I can proceed with these changes if you don't have the time to finish. Just let me know.

Regarding the problem with compiling `scala-cli`, can you please some logs?

**Comment by JD557** [comment]
> Regarding the problem with compiling scala-cli, can you please some logs?

I can, but there's nothing you can do to fix it. This is mostly on my end. 😅 

At first it was because I was an idiot and missed the "The Scala CLI sources ship with Mill launchers, so that Mill itself doesn't need to be installed on your system." part (I had the wrong version of mill)

But also, "Building Scala CLI requires JVM 17 to work properly." The problem is that I'm running Java 8 on my computer, to avoid problems with https://github.com/sbt/sbt/issues/7192. (I know there are ways to have multiple JVMs and maybe I could try Java 17 with mill, but my current setup is a bit of a mess right now... I need some time to clean it up).

So,when compiling, I get the expected errors:
```
D:\Projects\scala-cli\project\settings.sc:856: value readAllBytes is not a member of java.io.InputStream
      is.readAllBytes()
         ^
Compilation Failed
```
