### ISSUE TITLE
Add Scala CLI to packager manager `scala` installation. 

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#2212]
**Is your feature request related to a problem? Please describe.**
We need Scala CLI to be installed as part of the Scala installation, replacing the old runner and accessible via the `scala` command.

We need to investigate how to achieve this with the following package managers where `scala-cli` is already available:

- [x] `brew`-  Add Scala CLI to brew's scala installation https://github.com/VirtusLab/scala-cli/issues/2146
- [ ] `SDKMAN` 
- [ ] `Chocolatey`
- [ ] `Scoop`
- [ ] `Apt`
- [ ] `Dep`
- [ ]  `Yum`
- [ ]  `Rpm`
- [x]  `Coursier`

**Comment by lwronski** [comment]
- [x] `brew` - It can be achieved using the [version_scheme](https://rubydoc.brew.sh/Formula#version_scheme%3D-class_method) that was proposed in this [comment](https://github.com/VirtusLab/scala-cli/issues/2146#issuecomment-1561604325). Thanks @kiendang .
- [x] `Coursier` - when I replaced the [scala.json](https://github.com/coursier/apps/blob/main/apps/resources/scala.json) file locally and run the command:
```
 cs install --default-channels=false --channel apps/apps/resources    scala 
```
cs replaced the old `scala` runner with `scala-cli` under the `scala` alias.

**Comment by MaciejG604** [comment]
Tracked under https://github.com/VirtusLab/scala-cli/issues/2238
