### ISSUE TITLE
Dependency exclusion does not work as described in the docs

### ISSUE THREAD

**Issue by AvaPL** [VirtusLab/scala-cli#2214]
**Version(s)**
1.0.1

**Describe the bug**
The dependency exclusion does not work as described here: https://scala-cli.virtuslab.org/docs/guides/dependencies#excluding-transitive-dependencies.

**To Reproduce**
```
//> using dep com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%%sourcecode
//> using dep com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%sourcecode_3
```
gives
```
[error]  Error parsing dependency 'exclude=com.lihaoyi%%sourcecode': malformed module: exclude=com.lihaoyi%%sourcecode
[error]  Error parsing dependency 'exclude=com.lihaoyi%sourcecode_3': malformed module: exclude=com.lihaoyi%sourcecode_3
```

It can be fixed by using double quotes:
```
//> using dep "com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%%sourcecode"
//> using dep "com.lihaoyi::pprint:0.8.1,exclude=com.lihaoyi%sourcecode_3"
```

**Expected behaviour**
The docs should show the correct dependency exclusion syntax.

**Comment by lwronski** [comment]
@AvaPL, thank you for reporting. It was already fixed in docs in #2224 .
