### ISSUE TITLE
update incorrectly complains that Scala CLI was not installed by the installation script

### ISSUE THREAD

**Issue by philwalk** [VirtusLab/scala-cli#2237]
**Version(s)**
```bash
$ scala-cli -version
Scala CLI version: 1.0.1
Scala version (default): 3.3.0

$ uname -a
CYGWIN_NT-10.0-22621 d5 3.4.6-1.x86_64 2023-02-14 13:23 UTC x86_64 Cygwin
```
Same thing in `WSL Ubuntu`, installed via `sudo dpkg -i scala-cli.deb`
```bash
$ scala-cli update
Scala CLI was not installed by the installation script, please use your package manager to update scala-cli.
$ uname -a
Linux d5 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$

```
```CMD
C:\Windows\System32>systeminfo
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

**Describe the bug**
After downloading and installing the current release, `scala-cli update` incorrectly claims that it wasn't installed by the installation script.   Here's the session:
```bash
$ scala-cli update
Scala CLI was not installed by the installation script, please use your package manager to update scala-cli.
```
Here's the CMD session equivalent, showing that it's not related to the `cygwin` shell environment:
```CMD
C:\opt\ue>scala-cli -version
Scala CLI version: 1.0.1
Scala version (default): 3.3.0

C:\opt\ue>scala-cli update
Scala CLI was not installed by the installation script, please use your package manager to update scala-cli.
```

**To Reproduce**

- Download the installer
- install to default location
- issue command `scala-cli update`

**Expected behaviour**
The same experiment on an ubuntu system:
 After installing `scala-cli` and running the `update` command, I see this:
```bash
$ scala-cli update
Scala CLI is up-to-date
```

**Comment by lwronski** [comment]
Hi @philwalk, thank you for reporting. Unfortunately, the installation script is not available for Windows. It only works with Linux and macOS. For Windows, you can install scala-cli using alternative methods such as downloading the binary directly or using package managers.

If you have Linux/MacOs you can install scala-cli via instalator scripts in this way:
```
curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh
```


For Windows, you have the option to use a Windows package manager such as SDKMAN, Scoop, or Chocolatey to update Scala CLI.


I will still open this issue because we can improve the error message on Windows to provide clearer explanations.

**Comment by philwalk** [comment]
@lwronski 
That makes sense, although in WSL we shouldn't see the error, so perhaps we should keep this open for Windows/WSL.

**Comment by philwalk** [comment]
This is no longer a problem in my `WSL` system, so I will close it.   Here's what I see this morning:
```
(base) philwalk@d5:~$ scala-cli update
Scala CLI is up-to-date
(base) philwalk@d5:~$ scala-cli version
Scala CLI version: 1.0.6
Scala version (default): 3.3.1
(base) philwalk@d5:~$
```
