### ISSUE TITLE
actionable diagnostic rewrite for sbt dependency always overrides first line

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#2248]
**Version(s)**
1.0.1

**Describe the bug**
the diagnostic to rewrite sbt dependency syntax is always replacing the first line of the file with its rewrite

**To Reproduce**

- open foo.scala in vscode:

```
scala setup-ide .
code foo.scala
```

- paste this code in there

```scala
//> using scala 2.13
//> using dep "org.scalatra::scalatra:3.0.0-M4"
//> using dep "javax.servlet" % "javax.servlet-api" % "4.0.1"

package com.example.app

import org.scalatra._

class MyScalatraServlet extends ScalatraServlet
```

click on the javax servlet dependency and accept the rewrite, then this happens:

```diff
- //> using scala 2.13
+ //> using dep "javax.servlet:javax.servlet-api:4.0.1"
 //> using dep "org.scalatra::scalatra:3.0.0-M4"
 //> using dep "javax.servlet" % "javax.servlet-api" % "4.0.1"

 package com.example.app

 import org.scalatra._

 class MyScalatraServlet extends ScalatraServlet
```

if I add some empty lines at the top of the file then this happens:

```diff
+ //> using dep "javax.servlet:javax.servlet-api:4.0.1"



 //> using scala 2.13
 //> using dep "org.scalatra::scalatra:3.0.0-M4"
 //> using dep "javax.servlet" % "javax.servlet-api" % "4.0.1"

 package com.example.app

 import org.scalatra._

 class MyScalatraServlet extends ScalatraServlet
```

**Expected behaviour**
only change the line affected

**Comment by MaciejG604** [comment]
Rewriting the dependency format is a Code Action introduced in Metals, I'll clsoe this issue and reopen it in Metals repo. @bishabosha which Metals version are you using?

**Comment by bishabosha** [comment]
ok, thanks, its Metals 0.11.12

**Comment by bishabosha** [comment]
I tried in 0.11.12+155-4b9454ac-SNAPSHOT and it seems to be fixed
