### ISSUE TITLE
scala-cli downloads JVM temurin 17 with no need (I already have preinstalled JDK 20 and JDK 17)

### ISSUE THREAD

**Issue by unkarjedy** [VirtusLab/scala-cli#2268]
Scala CLI 1.0.1
Mac 13.2.1 (22D68)

1. Have a fresh machine with multiple JDKs installed 
(I have 5 JDK installed in `~/Library/Java/JavaVirtualMachines`)
\
NOTE: ensure you don't have "adoptium" / "temurin" installed in coursier locations 
(which is the case for new scala-cli users without prior interaction with scala cli or coursier
Delete these directories:
`~/Library/Caches/Coursier/v1/https/github.com/`
`~/Library/Caches/Coursier/arc/https/github.com/`

2. Install scala-cli.
I installed it via brew command
`brew install Virtuslab/scala-cli/scala-cli`

3. Run `scala-cli` in the terminal

Notice that `scala-cli` downloads "JVM temurin:17".
However, right after downloading it starts REPL with JDK 20, which was preinstalled on my machine.
Downloading JVM was redundant.

When I initially noticed the issue, it was especially annoying because I was on a train with slow internet.
It took me a while to download the JVM just finding out it is not needed.

-----

```txt
 ls -l ~/Library/Java/JavaVirtualMachines
 rm -frd ~/Library/Caches/Coursier/v1/https/github.com/
 rm -frd ~/Library/Caches/Coursier/arc/https/github.com/ 
 scala-cli
 scala-cli --version
 java -version
 
```

<img width="623" alt="image" src="https://github.com/VirtusLab/scala-cli/assets/3989292/8d1627e8-f83e-45f1-9259-821681d20867">

**Comment by unkarjedy** [comment]
Related:
https://github.com/VirtusLab/scala-cli/pull/2253
https://github.com/VirtusLab/scala-cli/issues/1379
https://github.com/VirtusLab/scala-cli/issues/2244

**Comment by lwronski** [comment]
Hi @unkarjedy,  can you run the following command and attach output into issue?

```
 echo 'println(s"""JAVA_HOME:${System.getenv("JAVA_HOME")}\njava.home: ${sys.props.get("java.home")}""")' | scala-cli _.sc
```

**Comment by unkarjedy** [comment]
@lwronski 
```
dmitrii.naumenko@NVC00622 .sbt %  echo 'println(s"""JAVA_HOME:${System.getenv("JAVA_HOME")}\njava.home: ${sys.props.get("java.home")}""")' | scala-cli _.sc
[warn]  JVM that is hosting bloop is older than the requested runtime. Please run command `bloop exit`, and then use `--jvm` flag to restart Bloop
[warn] OsLibc.defaultJvm
[warn] [current bloop jvm] /Users/dmitrii.naumenko/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_aarch64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
[warn]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
JAVA_HOME:null
java.home: Some(/Users/dmitrii.naumenko/Library/Java/JavaVirtualMachines/openjdk-20.0.1/Contents/Home)
```

BTW this warning is quite annoying:
>[warn]  JVM that is hosting bloop is older than the requested runtime. Please run command `bloop exit`, and then use `--jvm` flag to restart Bloop

Guess it might also be related to this issue with JDK detecten

**Comment by lwronski** [comment]
@unkarjedy 

> However, right after downloading it starts REPL with JDK 20, which was preinstalled on my machine.

Definitely, this is a bug in `scala-cli`. ScalaCLI should use the Java it manages internally. We'll address this issue.

> Guess it might also be related to this issue with JDK detecten

ScalaCLI detect JDK by searching for `JAVA_HOME` in env variables. If it's not set, ScalaCLI downloads the JVM. Hence, if you set `JAVA_HOME` in your env to at least version 17, it will use that and not downloading.

**Comment by unkarjedy** [comment]
@lwronski 
>ScalaCLI detect JDK by searching for JAVA_HOME in env variables. 
If it's not set, ScalaCLI downloads the JVM. 
Hence, if you set JAVA_HOME in your env to at least version 17, it will use that and not downloading.

Have you considered using `/usr/libexec/java_home` on Mac OS in case `JAVA_HOME` is not set?
https://stackoverflow.com/questions/15826202/where-is-java-installed-on-mac-os-x/15826712#15826712
https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos/24657630#24657630

**Comment by lwronski** [comment]
> Have you considered using /usr/libexec/java_home on Mac OS in case JAVA_HOME is not set?
https://stackoverflow.com/questions/15826202/where-is-java-installed-on-mac-os-x/15826712#15826712
https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos/24657630#24657630

@unkarjedy, Thank you for your suggestion. I think this could be added to ScalaCLI, and I don't see any objection. I will implement it.

**Comment by lwronski** [comment]
@unkarjedy Thanks for reporting. In the next release, ScalaCLI should read `JAVA_HOME` from `/usr/libexec/java_home`. Moreover, the `repl` will no longer download Java 17 when running without sources.
