### ISSUE TITLE
Actionable Diagnostics from compiler not visible

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#2307]
**Version(s)**
1.0.2

**Describe the bug**

Actions reported by the compiler are not visible with metals 1.0.0 and scala cli

**To Reproduce**
If I use scala `3.3.2-RC1-bin-20230723-5afe621-NIGHTLY` version, and write the following code in VS Code and metals 1.0.0

```scala
//> using scala 3.3.2-RC1-bin-20230723-5afe621-NIGHTLY
def foo(): Int = 23

def test: Int = foo
//              ^^^ error: missing parentheses
```

I'll get a compile error, however I'll have no "quick fixes" to turn `foo` => `foo()`

but if I run the same with sbt 1.9.2, (and sbt bloopInstall) then I'll have quick fixes.

**Expected behaviour**
I should have the same quick fixes as with bloop + sbt

**Comment by tgodzik** [comment]
Thanks for reporting! I think that requires https://github.com/VirtusLab/scala-cli/pull/2284 which wasn't released yet and also a bump in the Bloop fork. I will look into that

**Comment by tgodzik** [comment]
Looks like it's working on the newest nightly. :tada: @lwronski @MaciejG604 do you have time to write a test for it?

**Comment by MaciejG604** [comment]
On it!
