### ISSUE TITLE
TASTy version should depend on the Scala version

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#232]
Scala 3.1.0 has a new TASTy version, however this makes using scala-cli unusable for 3.1.0 as it is hard coded to expect the same tasty version as Scala 3.0.0 (i.e. 28.0-0)

here is a good test file: (run with `scala-cli -S 3.1.0 tastyVersion.sc`)
```scala
import dotty.tools.tasty.TastyFormat.*

val isPreview =
  if ExperimentalVersion > 0 then
    s" (preview $ExperimentalVersion)"
  else
    ""

val tastyVersion = s"$MajorVersion.$MinorVersion$isPreview"

println(s"TASTy version is $tastyVersion")

```

currently the renaming step causes a crash due to unexpected TASTy:
```scala
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
Exception in thread "main" scala.build.tastylib.UnpickleException: TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0.
```

**Comment by romanowski** [comment]
Fixed (partially) in `0.0.7` release. We still lack support for Snapshot versions of the compiler

**Comment by alexarchambault** [comment]
I think we can just get rid of the minor version check in our `tasty-lib` module. We only change some simple names in TASTy files, nothing more, and leave everything else as is (treating it as just `Array[Byte]`). Just checking the major version should be enough for us. (I have some developments doing that locally… I can push that earlier than later if that's absolutely needed.)

**Comment by romanowski** [comment]
This is still a problem for a non-stable version of scala (e.g. snapshots)

**Comment by tpasternak** [comment]
Not really sure what would be the correct way to fix it. IMO the safest way would be to disable the tasty post processor when snapshot scalac is used. @romanowski what do you think?

**Comment by romanowski** [comment]
I am fine with that we can also use what we have and just ignore the version check.

**Comment by tpasternak** [comment]
For snapshot versions I think it's not that uncommon to edit tasty format

**Comment by tpasternak** [comment]
For snapshots, it works since b2c95eb9d3e9
