### ISSUE TITLE
NIT messages about starting and downloading Bloop printed in reverse order

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#2352]
**Version(s)**
`1.0.4`

**Describe the bug**
When Scala CLI needs to download and start a new Bloop version, it prints that it starts Bloop, then it prints that it downloads it. This feels odd - Scala CLI actually first downloads Bloop, then starts it.

**To Reproduce**
Exit Bloop server, remove some of its JARs from your local cache, and compile some code with Scala CLI:
```text
$ scala-cli bloop exit
Stopped Bloop server.
$ rm -rf ~/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/github/alexarchambault/bleep/bloop-backend_2.12
$ scala-cli compile -e 'object Foo'
Starting compilation server
Downloading compilation server 1.5.9-sc-1
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
```

**Expected behaviour**
The "Starting compilation server" and "Downloading compilation server" messages should be printed in a reverse order ("Downloading", then "Starting").

**Comment by tgodzik** [comment]
Will be available after the next release of bloop-core
