### ISSUE TITLE
JAVA_OPTS / JDK_JAVA_OPTIONS not respected

### ISSUE THREAD

**Issue by edmcman** [VirtusLab/scala-cli#2354]
**Version(s)**
1.0.4

**Describe the bug**
I have my Java proxies set in `JAVA_OPTS` and `JDK_JAVA_OPTIONS`, but scala-cli seems to ignore or reset them.  I had to put the arguments on the scala-cli command line for them to work.

I first used scala-cli through the metals project, and it (metals) failed because scala-cli couldn't download any files.  In cases like this, where the user is not even aware that they are using scala-cli, it would be nice if scala-cli would use the standard environment variables for proxies.

I'm not really sure if this is a bug or just a feature request... I think it depends on whether the current behavior is intentional.

**To Reproduce**
`env JAVA_OPTS='-Dhttp.proxy=4.4.4.4 ...' JDK_JAVA_OPTIONS='-Dhttp.proxy=4.4.4.4 ...' scala-cli`

**Expected behaviour**
I expected the proxies in `JAVA_OPTS` or `JDK_JAVA_OPTIONS` to be used.

**Comment by MaciejG604** [comment]
Scala CLI indeed does not analyze those environment variables, so this mechanism could be added.

However, as of now, Scala CLI offers some other ways to specify Java properties:
- a local properties file with a name `.scala-jvmopts` residing in the directory where `scala-cli` is called
- using config to set properties globally: `scala-cli --power config java.properties '-Dhttp.proxy=4.4.4.4 ...'`

**Comment by edmcman** [comment]
@MaciejG604 Once I realized the problem was in scala-cli, I didn't have much problem figuring out how to set the Java properties, thanks to scala-cli's very clear documentation.  But because I was using Metals, which under the hood uses scala-cli, I was not even aware that I was using scala-cli until I asked the Metals devs for help.  I think all the current mechanisms that you list are not generic, and would require the user to *know* they are using scala-cli and react accordingly.

Also, if you have never been forced to use a proxy, it's a huge pain. Needing to configure individual applications to get them to work makes it even worse!
