### ISSUE TITLE
Package older scalafmt native image.

### ISSUE THREAD

**Issue by He-Pin** [VirtusLab/scala-cli#2374]
When I'm using `scala-cli fmt` in akka/akka on Windows 11, it can not download, because there is no older version's native image.

**Comment by tgodzik** [comment]
Thanks for reporting! We don't plan to support older versions especially that the version used by akka was released 4 years ago. An easy workaround would be to use scalafmt directly or run sbt, which has the sbt-scalafmt plugin added.
