### ISSUE TITLE
Default Scala versions are out of date

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#2394]
I noticed today that even though Scala 2.13.12 and Scala 3.3.1 are both out now, `scala-cli -S 2` still runs 2.13.11, and `scala-cli -S 3` still runs 3.3.0.

Is there some way we can expedite updating that when new Scala versions come out?

As the Scala 2 release manager, I'd be happy to add this to the [Scala 2 release steps](https://github.com/scala/scala-dev/blob/scala-dev/.github/ISSUE_TEMPLATE/release.md) if action from our end is needed.

One possibility would be simply be for me to open an issue in this repo whenever there's a new Scala 2 release, to remind y'all to do something. But I could also PR a change directly if you point me in the right direction.

Pardon if we've discussed this before and I'm not remembering. but let's not depend on my memory, let's enshrine something in the release steps. (And perhaps @Kordyjan could add something to the Scala 3 release steps.)

**Comment by SethTisue** [comment]
I hesitate to nag, but naturally all of us were swamped last week, because of Scala Days — can we return to this now...?

**Comment by lwronski** [comment]
I will discuss this issue internally and return with response tomorrow. Thank you for reporting this issue.

**Comment by tgodzik** [comment]
We decided that when using version such as `3` or `3.3` it should infer the latest version that meets the criteria:
```
3 -> 3.3.1
3.2 -> 3.2.2
etc.
```
The default version used by Scala CLI will be the last version we released with, since that is properly tested and we don't want to change the version for the users at a random time. We can bump the version and release at a later date since it's not really breaking anyones code.

**Comment by machadoit** [comment]
What is a bit confusing to me, is how does this fit the expectations of [SIP-46](https://github.com/scala/improvement-proposals/pull/46)? Maybe is something for later, but I was assuming that running `scala`, would use the latest installed Scala version.

For instance, using coursier and trying the `cs install scala-experimental` changed my `scala --version` from 3.3.1 to 3.3.0 which is a bit confusing.

**Comment by SethTisue** [comment]
>Is there some way we can expedite updating that when new Scala versions come out?

> As the Scala 2 release manager, I'd be happy to add this to the Scala 2 release steps if action from our end is needed.

> One possibility would be simply be for me to open an issue in this repo whenever there's a new Scala 2 release, to remind y'all to do something. But I could also PR a change directly if you point me in the right direction.

still wondering about these questions?

**Comment by tgodzik** [comment]
> What is a bit confusing to me, is how does this fit the expectations of https://github.com/scala/improvement-proposals/pull/46? Maybe is something for later, but I was assuming that running scala, would use the latest installed Scala version.

There will be separate artifact release with Scala 3, but that was postponed to 3.3.2. With that artifact the version will correspond to the installed version. So if you install `scala:3.3.0` you will have Scala 3.3.0 as the default and if you update to the latest version you will get the newest Scala version.

We don't want to change the defaults automatically since that might make people code stop compiling if the newest version would for example be 3.4.x or later.

**Comment by machadoit** [comment]
> still wondering about these questions?

The aim was to share the concerns on the scope of the solution https://github.com/VirtusLab/scala-cli/pull/2411 (should've probably asked on the PR itself my bad)

> (...) postponed to 3.3.2. With that artifact the version will correspond to the installed version.

Sounds great, thanks for clarifying!

**Comment by SethTisue** [comment]
> We decided that when using version such as 3 or 3.3 it should infer the latest version that meets the criteria:

> 3 -> 3.3.1
> 3.2 -> 3.2.2
> etc.

I don't think I understand the logic here of having "no version specified" mean "latest when this scala-cli was built", but having "no *patch* version specified" mean "latest on Maven Central"

I thought the policy would be "We don't want to change the defaults automatically" across the board.

So for example, @j-mie6 reported on Discord today that he had his students using `//> using scala 2.13`, but then 2.13.13 hit Maven Central and now all of his students' builds are likely broken, since at the moment tooling for 2.13.13 isn't published yet.

Am I asking/reporting this in the right place, or is there some more recent discussion?

**Comment by j-mie6** [comment]
Yeah, to provide some background, the CI I'm running when I had the run fail post 2.13.13 release is pulling 

```
curl -fL https://github.com/Virtuslab/scala-cli/releases/latest/download/scala-cli-x86_64-pc-linux.gz
```

We are set to `//> using scala 2.13`, and I had my build failing because of missing plugins for `scala-native` because it's pulling for `2.13.13`
