### ISSUE TITLE
Crash on EA version of JDK

### ISSUE THREAD

**Issue by SlowBrainDude** [VirtusLab/scala-cli#2397]
**Version(s)**
Scala CLI version: 1.0.4

**Describe the bug**
Calling Scala-CLI (`scala-cli -j system someCode.scala `) crashes with the following error:

```
Failed to parse output of 'bloop about':
bloop v1.5.9-sc-1

Using Scala v2.12.18 and Zinc v1.9.2
Running on Java JDK v17.0.9-ea (/usr/lib/jvm/java-17-openjdk-amd64)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center and the community.

Starting compilation server
Error: java.lang.RuntimeException: Fatal error, could not spawn Bloop: failed to parse output: 'bloop v1.5.9-sc-1

Using Scala v2.12.18 and Zinc v1.9.2
Running on Java JDK v17.0.9-ea (/usr/lib/jvm/java-17-openjdk-amd64)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center and the community.
```

**To Reproduce**
Install the current OpenJDK release on Debian Testing, which is currently an early-access version (for whatever reasons, IDK), or some other Java Runtime EA release.

Run Scala-CLI with that JDK (e.g. `-j system` flag).

**Expected behaviour**
Should not crash.

I've encountered this bug first in `bleep`. But just found out it affects also Scala-CLI.

There is already a patch prepared at https://github.com/scala-cli/bloop-core/pull/153. Could someone please have a look?

Thanks for making Scala-CLI! Looking forward to having it working again. :smile:

**Comment by tgodzik** [comment]
@lwronski I think the update was merged and we can close?

**Comment by lwronski** [comment]
> lwronski I think the update was merged and we can close?

Fixed in https://github.com/scala-cli/bloop-core/pull/153. @SlowBrainDude Thanks for fix! 
Changes from bloop included in https://github.com/VirtusLab/scala-cli/pull/2401.
