### ISSUE TITLE
move `scala-cli` to `homebrew/core` instead of using a tap

### ISSUE THREAD

**Issue by kraktus** [VirtusLab/scala-cli#2408]
Hello, thank you for your time maintaining `scala-cli`.

There is at first sight no reason to use a third-party-repository (brew tap), since licences are compatible and no tap dependencies are needed, instead of directly put the formula on [homebrew-core](https://github.com/Homebrew/homebrew-core).
Moving it to the core would improve support and trust in the installation process for MacOs users, knowing they benefit from homebrew community support and expertise to improve, debug and maintain formulas.

I'd be ready to help migrating if needed.

**Comment by MaciejG604** [comment]
Hi @kraktus, thanks for the input!
Right now we're in the process of making `scala-cli` available under the `scala` brew formula, so there's no reason to create additional `scala-cli`.

**Comment by kraktus** [comment]
Ok cool 👍
