### ISSUE TITLE
Fmt command should be aware of scala-fmt version from the configuration

### ISSUE THREAD

**Issue by MarcinAman** [VirtusLab/scala-cli#241]
- scala-cli should read the scalafmt version from the configuration file if it is not provided manually. If we are not doing it then the user is "greeted" with:
```
error: invalid Scalafmt version.

This Scalafmt installation has version '3.0.3' and the version configured in '/Users/maman/Documents/openaq-streamer/.scalafmt.conf' is '2.6.4'.
To fix this problem, add the following line to .scalafmt.conf:
```
version = '3.0.3'
```

NOTE: this error happens only when running a native Scalafmt binary.
Scalafmt automatically installs and invokes the correct version of Scalafmt when running on the JVM.
```
- Fmt command should have more scalafmt tags to choose from (eg. more tags pushed here: https://github.com/alexarchambault/scalafmt-native-image/releases)
- `--check` doesn't work because afaik it is not used anywhere

**Comment by jchyb** [comment]
Closed via #528
