### ISSUE TITLE
Constant recompilation and error when you have a mismatched JVM

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#2412]
**Version(s)**
1.0.4

**Describe the bug**
So this happened when in my code I decided to make the JVM version explicit. I was using 17 and then added the following using directive to my build:

```
//> using jvm 19
```

I didn't notice this until I had an error and saw it constantly disappearing and repairing.

![2023-09-21 11 07 50](https://github.com/VirtusLab/scala-cli/assets/13974112/05ac6f4c-a460-4890-840e-87275ea6e929)

When you look in the Metals logs you can finally see:

```
2023.09.21 11:11:39 INFO  BSP server: [warn] [current bloop jvm] /Users/ckipp/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_aarch64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
2023.09.21 11:11:39 INFO  BSP server: [warn]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023.09.21 11:11:39 INFO  BSP server: [warn]  JVM that is hosting bloop is older than the requested runtime. Please run command `bloop exit`, and then use `--jvm` flag to restart Bloop
2023.09.21 11:11:39 INFO  BSP server: [warn] COMMAND_LINE
2023.09.21 11:11:39 INFO  BSP server: [warn] [current bloop jvm] /Users/ckipp/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_aarch64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
2023.09.21 11:11:39 INFO  BSP server: [warn]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023.09.21 11:11:40 INFO  time: indexed workspace in 0.73s
2023.09.21 11:11:40 INFO  Disconnecting from scala-cli session...
2023.09.21 11:11:40 INFO  Shut down connection with build server.
2023.09.21 11:11:40 INFO  Cancelling compilation on scala-cli server
2023.09.21 11:11:40 INFO  Attempting to connect to the build server...
```

The tricky thing is that for a normal user, they will have no idea what is going on. Since even if you look in the Metals doctor it will be constantly refreshing as the build server reconnects, so you can't even see what the issue if it is listed there. When this happens there should be a better way to signify to the user what is happening. Maybe these warnings should be errors? Maybe on the Metals side these should be surfaced to the user?

Also note that even if the user sees this message and tries a `bloop exit` it won't fix the issue. Also trying a `scala-cli bloop exit` still doesn't fix the issue.  The only way I was able to fix the issue was switching my system jvm to 19, then killing everything, and then restarting.

**To Reproduce**
This might be hard to reproduce, but just have a minimal project, make sure bloop is started with 17, and then add in a using directive to use 19. You should see this behavior.

**Expected behaviour**
I'd expect a clear message surfaced to the user about how to fix the issue directly from within the editor.

**Comment by tgodzik** [comment]
This looks like both an issue with Metals and Scala CLI. On the Scala CLI side we should probably restart automatically, but I am not sure what is the issue on the Metals side and why we try to reconnect each time.
