### ISSUE TITLE
Pick the latest Scala version after installation

### ISSUE THREAD

**Issue by plokhotnyuk** [VirtusLab/scala-cli#2417]
![image](https://github.com/VirtusLab/scala-cli/assets/890289/66d1a2c3-ac18-415d-8b49-5268ae1bc8fd)

**Comment by lwronski** [comment]
Hi @plokhotnyuk 

I can reproduce the bug using Scala `3.3.0`, but it seems to work fine with `3.3.1`. Can you try using the newer version of Scala?

**Comment by plokhotnyuk** [comment]
It works fine with `scala-cli -S 3.3.1`, so it could be a feature request to pick the latest Scala version by default (at least after the installation).

**Comment by SethTisue** [comment]
that's https://github.com/VirtusLab/scala-cli/issues/2394 — the default Scala will remain what it was when scala-cli released, but after https://github.com/VirtusLab/scala-cli/pull/2411 you'll be able to say e.g. `-S 3` to ask for latest.
