### ISSUE TITLE
scala-cli depends on multiple versions of artifacts with conflicting cross-version suffixes

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#2421]
**Version(s)**
1.0.4

**Describe the bug**
org.virtuslab.scala-cli:cli_3:1.0.4 depends on multiple versions of artifacts with conflicting cross-version suffixes:
```
com.lihaoyi:geny _2.13, _3
org.scala-lang.modules:scala-collection-compat _2.13, _3
com.github.plokhotnyuk.jsoniter-scala:jsoniter-scala-core _3, _2.13
com.lihaoyi:sourcecode _3, _2.13
ai.kien:python-native-libs _3, _2.13
com.lihaoyi:os-lib _2.13, _3
```

**To Reproduce**
Navigate to:
https://central.sonatype.com/artifact/org.virtuslab.scala-cli/cli_3/dependencies
And select "Dependency Type: All". 

**Expected behaviour**

You should not depend on multiple versions of the same artifact with conflicting cross-version suffixes. When multiple versions of the same class are on the classpath the behavior is undefined / non-deterministic.

cc @toniogela

**Comment by TonioGela** [comment]
I'll add that using via scala-cli itself won't trigger the problem:

```scala
//> using scala 3.3.1
//> using dep org.virtuslab.scala-cli::cli::1.0.4

import scala.cli.ScalaCli

object testApp extends App:
  ScalaCli.main(Array("compile", "foo.scala"))
```

while adding the dependency in an sbt project like `"org.virtuslab.scala-cli" %% "cli" % "1.0.4"` won't work. A temporary fix is adding exclusion rules:

```scala
"org.virtuslab.scala-cli" %% "cli" % "1.0.4" excludeAll (
  ExclusionRule("com.lihaoyi:geny_2.13"),
  ExclusionRule("org.scala-lang.modules", "scala-collection-compat_2.13"),
  ExclusionRule(
    "com.github.plokhotnyuk.jsoniter-scala",
    "jsoniter-scala-core_2.13"
  ),
  ExclusionRule("com.lihaoyi", "sourcecode_2.13"),
  ExclusionRule("ai.kien", "python-native-libs_2.13"),
  ExclusionRule("com.lihaoyi", "os-lib_2.13")
)
```

**Comment by lwronski** [comment]
It seems that Mill miss version conflict detection. I can't find a plugin that allows users to set eviction rules, similar to what's available in SBT.
