### ISSUE TITLE
Not getting `test` or `debug test` options in VS Code with Metals

### ISSUE THREAD

**Issue by spamegg1** [VirtusLab/scala-cli#2422]
**Version(s)**
1.0.4

**Describe the bug**
Not sure if this is a Metals issue, or a Scala-cli issue...
I followed the [Cookbook](https://scala-cli.virtuslab.org/docs/cookbooks/vscode) to work with Scala-cli and VS Code.

Getting the `run | debug` buttons in `HelloWorld.scala`:
![run](https://github.com/VirtusLab/scala-cli/assets/4255997/3ec3c939-25b9-48fb-8918-2bf9cca6b249)

But not getting the `test | debug test` buttons in `MyTests.test.scala` file:
![test](https://github.com/VirtusLab/scala-cli/assets/4255997/8837c785-5a6d-4db2-a060-09e8b7105ef6)

**To Reproduce**
1. Create directory structure and files as described in the [Cookbook](https://scala-cli.virtuslab.org/docs/cookbooks/vscode):
![structure](https://github.com/VirtusLab/scala-cli/assets/4255997/a07ecd0a-5515-4c9b-b92a-9f34c1be3556)

2. Run in the root directory `scala-cli run .` successfully.
3. Run `code .` in the root directory.

**Expected behaviour**
`test | debug test` buttons should be there.

**Comment by kasiaMarek** [comment]
We don't actually use code lenses for tests. Those have run buttons instead:
![Screenshot 2023-10-04 at 17 27 27](https://github.com/VirtusLab/scala-cli/assets/26606662/36565d3c-524d-4628-8270-023e592bc58d)
Maybe you have somehow disabled the test explorer in VSCode?

**Comment by spamegg1** [comment]
I see what you mean by not using Code Lenses:
![code-lenses](https://github.com/VirtusLab/scala-cli/assets/4255997/64ca8343-a1b1-4f80-8622-6e4ab9190ae7)
In this case, the explanation in the Setting is misleading, it makes me think that Code Lenses *should* work? (like the below)

Then the question is, how do they have the `test/debug` buttons above the test in the Cookbook:
<img width="325" alt="cookbook" src="https://github.com/VirtusLab/scala-cli/assets/4255997/50d72646-110f-462f-b144-4f982b6415ab">


When I use Test Explorer, I don't get the green play buttons:
![test-explorer](https://github.com/VirtusLab/scala-cli/assets/4255997/78c94aed-b6e5-489b-a0a5-31d07592536d)


Just to be sure, test buttons in the gutter are enabled:
![gutter](https://github.com/VirtusLab/scala-cli/assets/4255997/d6b19fe7-f498-473f-8df8-9c8750c28ac2)


This is frustrating. There is some kind of magic going on that I don't understand.

**Comment by spamegg1** [comment]
I had to reset my VS Code installation, now it seems to work. I cannot reproduce the issue, so I'll let it go I guess... :angry:
