### ISSUE TITLE
"using file" directive fails with transitive dependencies

### ISSUE THREAD

**Issue by AlexITC** [VirtusLab/scala-cli#2425]
**Version(s)**

1.0.4

**Describe the bug**

`using file ...` directive allows specifying file dependencies but transitive dependencies do not work, for example:

- Compiling `A` fails when `A`  depends on `B` which depends on `C` 
- Compiling `A` works when `A` depends on `B` and `C` (this is not used), `B` depends on `C`.

**To Reproduce**

- Run `scala-cli A.scala`, which throws:

  ```
  [error] ./B.scala:6:5
  [error] Not found: C
  [error]     C.funC()
  [error]     ^
  ```

- `A.scala`:

  ```scala
  //> using file B.scala
  
  object A {
    def main(args: Array[String]): Unit = {
      println("Fun A")
      B.funB()
    }
  }
  ```

- `B.scala`:

  ```scala
  //> using file C.scala
  
  object B {
    def funB(): Unit = {
      println("Fun B")
      C.funC()
    }
  }
  ```

- `C.scala`:

  ```scala
  object C {
    def funC(): Unit = println("Fun C")
  }
  ```

**Expected behaviour**

`scala-cli A.scala` should work, still, we need to add `//> using file C.scala` to `A.scala` to get this example working.

**Comment by MaciejG604** [comment]
Indeed the transitive `using file` will not work. This is a deliberate action from our side. The main reason is that Scala CLI has agreed on a convention of keeping all directives in one file, preferably `project.scala`, chaining the `using file` directive breaks this convention and allows for very complicated project structures.

On the other hand, I suppose similar behavior can be achieved by specifying the correct list of inputs to the `scala-cli` command.

However, our documentation should mention that transitive `using file` is not supported. Also, there should be a warning when a configuration like that is used in the project.

**Comment by AlexITC** [comment]
> Indeed the transitive using file will not work. This is a deliberate action from our side

I wasn't aware that this was the intended design.

> The main reason is that Scala CLI has agreed on a convention of keeping all directives in one file, preferably `project.scala`

I'm yet to try this whether this works for my use case, I have a project with multiple entrypoints and I need to make sure that `scala-cli package` only includes the entrypoint I'm packaging instead of packaging the whole project, this is why I have been depending on the `using file` directive.

Thanks for explaining.

**Comment by MaciejG604** [comment]
If you encounter any problems be sure to ask a question on the [#scala-cli channel of the official scala discord server](https://discord.gg/CwQD6bzB) or report an issue if you find anything that could be improved or fixed.
