### ISSUE TITLE
Auto-magic shell one-liner installer

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/scala-cli#2427]
**Is your feature request related to a problem? Please describe.**
A one-liner installation option makes for a great README for the users, e.g.:

    ```bash
    $ curl -fsSL https://get.pulumi.com/ | sh
    ```

Real world example: https://github.com/pulumi/pulumi-java/tree/main#getting-started

**Describe the solution you'd like**
A shell script hosted at `https://get.scala-cli.virtuslab.org/` that automatically detects the version required by the user.

**Describe alternatives you've considered**
An alternative is to not do it and keep the 3-liner installation.

**Comment by tgodzik** [comment]
Thanks for reporting! We already have a one line installation method (it is shown as default for linux):
`curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh`

Is this what you would expect?

**Comment by pawelprazak** [comment]
Ah! Great, thank you, I've must have missed that 😅 

Only improvement then could be an "alias" from something shorter, e.g.:
`get.scala-cli.virtuslab.org` -> `https://virtuslab.github.io/scala-cli-packages/scala-setup.sh`

But this is a very tiny difference ;)
