### ISSUE TITLE
Get `Internal error: expected resolution to have been kept` when using packaging.provided

### ISSUE THREAD

**Issue by akizminet** [VirtusLab/scala-cli#2456]
**Version(s)**
1.0.4

**Describe the bug**
Use packaging.provided directive

Package file with: `scala-cli package project.scala` will fail with `Error: java.lang.RuntimeException: Internal error: expected resolution to have been kept`

It works when I manually provide the `--provided` flag  in command: `scala-cli package project.scala --provided 'org.apache.spark::spark.sql'` or when I remove `packaging.provided` directive

**To Reproduce**
```scala
//> using scala 2.12.15
//> using lib org.apache.spark::spark-sql:3.3.2
//> using lib org.apache.spark::spark-hive:3.3.2
//> using lib org.apache.spark::spark-sql-kafka-0-10:3.3.2
//> using packaging.packageType assembly
//> using packaging.provided org.apache.spark::spark-sql
//> using packaging.provided org.apache.spark::spark-hive

object Main extends App {
  println("Hello, World")
}
```

**Expected behaviour**
No exception

**Comment by Gedochao** [comment]
@akizminet 
Note: I believe that normally the correct `packageType` here would be `spark` (which represents assemblies with Spark deps).
It's okay to use `assembly`, as Spark support is still highly experimental, just raising awareness.
```scala
//> using packaging.packageType spark
```

The fix should be included in the next release.
