### ISSUE TITLE
scala-cli installed from scripts should be able to update its version

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#247]
When scala-cli is installed using installation scripts we do not offer automatic update mechanism. 

We can update scala-cli automatically or ask user to update if we detect that new version was released.

**Comment by lwronski** [comment]
Every 10 run / test / command calls we [check](https://github.com/VirtusLab/scala-cli/blob/04aad105d0cdae8cd9f5ec0c3ff7695ba8589cc6/modules/cli/src/main/scala/scala/cli/commands/Run.scala#L48), whether the scala-cli used is the newest one only if ScalaCLI was installed using an installation script. If scala-cli is outdated, we log that newer scala-cli is available and ask users to update.

It was merged and released In 0.0.8 version.
