### ISSUE TITLE
scala-cli stalls when awaiting every single result from a list of Futures.

### ISSUE THREAD

**Issue by cheapsolutionarchitect** [VirtusLab/scala-cli#2470]
**Version(s)**
scala-cli 1.0.2, 1.0.4, Java 11

**Describe the bug**

Running the code linked in "To Reproduce" stalls the execution until the timeouts are reached.

**To Reproduce**

Copy the code provided here https://scastie.scala-lang.org/c8icnGOiSAO6jOoewoFXHw into a file called paralleltest.sc and run it with scala-cli -S 2.13.10 paralleltest.sc

**Expected behaviour**

Running the code from the Scala 2.13.10 REPL or with sbt finishes the execution without stalling the process. This should be the same for scala-cli.

**Comment by SethTisue** [comment]
@MaciejG604 offhand, this seems like the sort of thing that #2033 should have prevented?

note that the same script succeeds in Scala 3

**Comment by MaciejG604** [comment]
Due to the usage of a strictly Scala 3 feature in the class wrapper (`export`), Scala 2 scripts can't use it and will still suffer from deadlocks when parallelism is used.

However, we may have a solution for that that seems to have been overlooked before.
