### ISSUE TITLE
--version flag does not exist for publish local

### ISSUE THREAD

**Issue by JD557** [VirtusLab/scala-cli#2485]
**Version(s)**
1.0.4

**Describe the bug**

When trying to publish a file without directives, scala-cli shows the following message:

```
The `publish-local` sub-command is experimental.
Please bear in mind that non-ideal user experience should be expected.
If you encounter any bugs or have feedback to share, make sure to reach out to the maintenance team at https://github.com/VirtusLab/scala-cli
Using directive publish.name not specified, using workspace directory name repro as default name
[error]  Missing organization for publishing, specify one with --organization or with a '//> using publish.organization' directive
[error]  Missing version for publishing, specify one with --version or with a '//> using publish.version' directive
```

However, if one adds the `--organization` and `--version` flags, scala-cli fails with:

```
Unrecognized argument: --version

To list all available options, run
  [redacted] publish local --help
```

**To Reproduce**

`scala-cli --power publish local test.sc` and `scala-cli --power publish local --organization my.org --version 0.0.1 test.sc` on any `test.sc` file with no directives.

**Expected behaviour**

Either the `--version` flag should exist (although I admit that the name is quite overloaded) or the error message should not recommend it.

**Comment by MaciejG604** [comment]
Indeed the `--version` flag does not exist since it has been refactored into `--project-version` in #2310 [[more precisely, here]](https://github.com/VirtusLab/scala-cli/pull/2310/commits/eafd736d04b4ded5dafabefeeb957610d1d496ee)

The error output however, is a bug, thank you for reporting it.
