### ISSUE TITLE
Weird error in REPL: bad constant pool index: 0

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/scala-cli#2509]
**Version(s)**
1.0.4

**Describe the bug**
Confusing and unexpected error in simplest REPL command.

**To Reproduce**
```
scala-cli
Welcome to Scala 3.3.0 (21, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val s = ""
error while loading AccessFlag,
class file /modules/java.base/java/lang/reflect/AccessFlag.class is broken, reading aborted with class java.lang.RuntimeException
bad constant pool index: 0 at pos: 5189
error while loading ElementType,
class file /modules/java.base/java/lang/annotation/ElementType.class is broken, reading aborted with class java.lang.RuntimeException
bad constant pool index: 0 at pos: 1220
2 errors found
```

**Expected behaviour**
To not see two errors, or at least get actionable error messages.

**Comment by pawelprazak** [comment]
I've updated `scala-cli` to `1.0.5` and it is fixed now:
```
scala-cli
Welcome to Scala 3.3.1 (21.0.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val s = ""
val s: String = ""

scala>
```

**Comment by SethTisue** [comment]
looks like a JDK 21 thing

note that 1.0.5 defaults to 3.3.1 — I think on 1.0.4, `scala-cli -S 3.3.1` would probably have worked for you

JDK 21 support landed in 3.3.1 with this PR https://github.com/lampepfl/dotty/pull/17536

https://github.com/lampepfl/dotty/pull/18618 will improve the error message you get, starting with 3.3.2, thanks to @bishabosha

**Comment by SethTisue** [comment]
it's a bit unusual that there was a fairly long delay between Scala 3.3.1 coming out and Scala-CLI 1.0.5 coming out with 3.3.1 as the default. there is some discussion at https://github.com/VirtusLab/scala-cli/issues/2394 about the prospect of avoiding such delays in the future

**Comment by pawelprazak** [comment]
Thank you for the context! Keep up the good work :)
