### ISSUE TITLE
pgp.secret-key-password is not created by --pgp-password

### ISSUE THREAD

**Issue by JD557** [VirtusLab/scala-cli#2562]
**Version(s)**
v1.0.6

**Describe the bug**

Running `scala-cli --power config --create-pgp-key --pgp-password MY_CHOSEN_PASSWORD` does not create the `pgp.secret-key-password`, [as mentioned in the documentation](https://scala-cli.virtuslab.org/docs/commands/publishing/publish-setup/#pgp-key-pair).

**To Reproduce**

Run `scala-cli --power config --create-pgp-key --pgp-password MY_CHOSEN_PASSWORD` followed by `scala-cli --power config pgp.secret-key-password`

**Expected behaviour**

`scala-cli --power config pgp.secret-key-password` should return the password (or the documentation should not mention it)

**Comment by MaciejG604** [comment]
The behaviour is correct and has been introduces in #1987, but indeed the documentation should be updated.
Thanks for pointing it out!
