### ISSUE TITLE
Improve the UX of the docs website

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#2592]
- [x] fix the search feature
- [x] add categories level for guides & cookbooks
- [x] shorten guides & cookbooks titles in the links tree
- [ ] generate sitemap & analyse it
- [ ] look for other improvements

**Comment by MaciejG604** [comment]
Some sections from Reference could probably be merged with Guides e.g.:
- [ ] `Reference > Proxy authentication` and `Guides > Repositories and HTTP Proxies`
- [ ] `Reference > Dependency format` and `Guides > Managing dependencies / Updating dependencies` 


Also `Under the hood` and `Guides > Internals` have some similiar elements
