### ISSUE TITLE
buildTarget/changed notification not sent when Scala version changes

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#2638]
**Version(s)**
1.1.0

**Describe the bug**
Metals depends on notifications from Scala CLI to know when it should request fresh information. When we save and compile file we do get the change notification if we changed for example compiler options but not when the Scala Version changed

**To Reproduce**

Open a project with:
```
//> using scala 3.3.1
```

Run metals doctor and see the correct version being used.

Now changed to:
```
//> using scala 3.3.0
```

run doctor again. You will see that the version is still 3.3.1

When checking BSP trace we see that no new notification is sent after the change to new Scala version.

**Expected behaviour**
Notification is sent to Metals and the version changes.

**Comment by Gedochao** [comment]
We seem to merely forward this from Bloop.
https://github.com/VirtusLab/scala-cli/blob/3dcfb3357d9c35bd71be27548e7e4e82fc6ef528/modules/build/src/main/scala/scala/build/bsp/BuildClientForwardStubs.scala#L13-L14

We likely should be sending it with our `BspClient`:
https://github.com/VirtusLab/scala-cli/blob/3dcfb3357d9c35bd71be27548e7e4e82fc6ef528/modules/build/src/main/scala/scala/build/bsp/BspClient.scala#L20

A good point to start looking where would be `BspImpl`
https://github.com/VirtusLab/scala-cli/blob/3dcfb3357d9c35bd71be27548e7e4e82fc6ef528/modules/build/src/main/scala/scala/build/bsp/BspImpl.scala#L45

The `BspClient` is initialised in here:
https://github.com/VirtusLab/scala-cli/blob/3dcfb3357d9c35bd71be27548e7e4e82fc6ef528/modules/build/src/main/scala/scala/build/bsp/BspImpl.scala#L463-L465

**Comment by tgodzik** [comment]
Bloop is unable to see that the project changed because the hash changed, so we need to handle it in Scala CLI

**Comment by tgodzik** [comment]
Weirdly enough this started to work, only problem is in single file metals https://github.com/scalameta/metals/issues/6755

I am not sure exactly why that is happening or why it fixed.

**Comment by Gedochao** [comment]
Seems the problem has been fixed, closing this.
