### ISSUE TITLE
Document how to create custom toolkits

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#2639]
**Is your feature request related to a problem? Please describe.**
The [toolkit guide](https://scala-cli.virtuslab.org/docs/guides/introduction/toolkit#other-toolkits) does not include an explanation on how to create a custom toolkit from scratch.

**Describe the solution you'd like**
An extra section in the doc describing how to create custom toolkits.

**Additional context**
Created out of https://github.com/VirtusLab/scala-cli/discussions/2637

**Comment by yadavan88** [comment]
In that doc section, it would be nice if the some of these info added:
- How to created custom toolkit and step to publish for usage?
- Difference between custom toolkit and default toolkit usage
- Some info on how custom toolkit differ from using a directive
- An example toolkit implementation if possible

**Comment by Gedochao** [comment]
> An extra section in the doc describing how to create custom toolkits.

I actually wonder whether it should be an extra section in the general Scala Toolkit doc, or whether we should have a separate advanced guide/cookbook on building custom toolkits.

**Comment by yadavan88** [comment]
@Gedochao Probably a separate guide might be better as this might not be interest to everyone using the toolkit. 
I would be happy to help with this, if someone can guide me on the process/step.

**Comment by Gedochao** [comment]
> @Gedochao Probably a separate guide might be better as this might not be interest to everyone using the toolkit. 

Agreed. It'd be good to linke to it from the existing Scala Toolkit guide, though, so that it's easy to find.

> I would be happy to help with this, if someone can guide me on the process/step.

@yadavan88 Awesome, sure!
The docs live under [the `./website/docs directory`](https://github.com/VirtusLab/scala-cli/tree/main/website/docs). 
The existing Scala Toolkit doc can be edited here: https://github.com/VirtusLab/scala-cli/blob/main/website/docs/guides/introduction/toolkit.md
I'd imagine a new custom toolkits guide should go to the advanced category here: https://github.com/VirtusLab/scala-cli/tree/main/website/docs/guides/advanced
When adding a new guide, be sure to add it to the index at https://github.com/VirtusLab/scala-cli/blob/main/website/docs/guides/intro.md

When doing docs-only changes, you can branch from `stable` and create a PR to `stable`, so that the changes get deployed to the website when they're merged and not with the next Scala CLI release.

Otherwise, refer to [CONTRIBUTING.md](https://github.com/VirtusLab/scala-cli/blob/main/CONTRIBUTING.md) for more general rules for contributions.
Let me know if you need help.

**Comment by yadavan88** [comment]
Thanks for the details @Gedochao 
I will create the new PR and let you know.

**Comment by yadavan88** [comment]
Hi @Gedochao 
I created a new [PR](https://github.com/VirtusLab/scala-cli/pull/2715) with the documentation for the custom toolkit. Please share your feedback.

Thanks
Yadu

**Comment by yadavan88** [comment]
Hi @Gedochao 
Thanks for merging the PR. I think something is wrong in the styles. https://scala-cli.virtuslab.org/docs/guides/advanced/custom-toolkit 
I created a [PR](https://github.com/VirtusLab/scala-cli/pull/2719) to fix this issue. Could you have a look?
