### ISSUE TITLE
Additional ways for specifying Scala version

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#2645]
**Is your feature request related to a problem? Please describe.**
It was suggested that maybe it would be useful to have additional `3.lts` and `3.next` to have up to date version for 3.3.x line and the  3.4.x+ one

**Describe the solution you'd like**
3.lts should lead to the current Scala 3 lts version and 3.next to the latest version.

**Describe alternatives you've considered**
Specify it manually.

**Additional context**

https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html

**Comment by Gedochao** [comment]
We might want to support `lts` and `next`, too (which generally would be the same as `3.lts` and `3.next`).
`next` should point to the most recent stable version.
We might also want informative messages for `2.13.lts`, `2.12.lts` etc. (there's no formal LTS for Scala 2, but users don't have to know that, so we should explain to them why those versions aren't valid identifiers)

**Comment by SethTisue** [comment]
Would `3.next` behave any differently from just `3`?

**Comment by tgodzik** [comment]
> Would `3.next` behave any differently from just `3`?

Not really. So maybe it doesn't make sense to add it?
