### ISSUE TITLE
scalac `-P` option is not passed to scalac from the CLI

### ISSUE THREAD

**Issue by earldouglas** [VirtusLab/scala-cli#2653]
**Version(s)**
1.1.0

**Describe the bug**
When trying to use the continuations compiler via scala-cli, the required `-P:continuations:enable` argument is not being passed scalac when provided to scala-cli via the CLI.

**To Reproduce**
```
scala-cli \
  --scala 2.12.2 \
  --compiler-plugin org.scala-lang.plugins:::scala-continuations-plugin:1.0.3 \
  --dependency org.scala-lang.plugins::scala-continuations-library:1.0.3 \
  -P:continuations:enable \
  myscript.sc
```

**Expected behaviour**
The code should compile and run, but compilation fails with `this code must be compiled with the Scala continuations plugin enabled`.  Running scala-cli with `-v -v` shows that the `-P` argument is not being passed to scalac.

**Workaround**
Setting the `-P` argument as a directive works correctly:

```
//> using option -P:continuations:enable
```

**Comment by SethTisue** [comment]
Note that `--server=false` doesn't improve the situation (I had hoped from #2621 it might)

**Comment by earldouglas** [comment]
Trying to force the argument with `--scalac-option -P:continuations:enable` also does not work.
