### ISSUE TITLE
plugin option added twice

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#2708]
**Version(s)**
1.1.2

**Describe the bug**
When using:
```
//project.scala
//> using plugin "org.virtuslab::besom-compiler-plugin:0.1.1-SNAPSHOT"
```
the plugin option is sometimes added twice, but it doesn't seem to reproduce always/

**Expected behaviour**
Plugin option is added once.

**Comment by Gedochao** [comment]
may be related to https://github.com/VirtusLab/scala-cli/issues/2621, as I never really got it working stably with Bloop... 🤔 
@tgodzik is it reproducible with `--server=false`?

**Comment by lbialy** [comment]
--server=false does not generate bloop's json files I'm afraid

**Comment by Gedochao** [comment]
> --server=false does not generate bloop's json files I'm afraid

@lbialy but it does pass plugin options to the compiler

**Comment by lbialy** [comment]
There never was any issue with compilation by scala-cli, the error crashes metals and metals only.

**Comment by lbialy** [comment]
Passed you a repro with minimization via slack.

**Comment by keynmol** [comment]
Tomasz suggests that this is what breaks Metals for me, diagnostics not being delivered.

```scala
//> using scala "3.3.3"
//> using options -Werror -Wunused:all -Wvalue-discard -Wnonunit-statement
//> using plugin "org.virtuslab::besom-compiler-plugin:0.2.2"
//> using dep "org.virtuslab::besom-core:0.2.2"
//> using dep "org.virtuslab::besom-aws:6.23.0-core.0.2"
//> using dep "org.virtuslab::besom-awsx:2.5.0-core.0.2"

import besom.*
import besom.api.aws, besom.api.awsx

@main def main = Pulumi.run {
  val bucket =
    // THIS IS AN ERROR        v  <---- over here
    aws.s3.Bucket("my-bucket", ws.s3.BucketArgs(forceDestroy = true))

  Stack.exports(
    bucketName = bucket.bucket
  )

}

```
![CleanShot 2024-03-28 at 09 25 06](https://github.com/VirtusLab/scala-cli/assets/1052965/90175895-536a-4396-aa11-57aa0804fb3c)

![CleanShot 2024-03-28 at 09 30 28@2x](https://github.com/VirtusLab/scala-cli/assets/1052965/ecbbcd0f-9858-44af-8e16-8d420961ef0e)

**Comment by lbialy** [comment]
Yeah, this is a massive pita for us. Two things actually trigger this.
Compiler plugin is one thing. Second is

//> using options -language:noAutoTupling

No idea if this is the same problem or a completely different one.

**Comment by pawelprazak** [comment]
> Yeah, this is a massive pita for us. Two things actually trigger this. Compiler plugin is one thing. Second is //> using options -language:noAutoTupling No idea if this is the same problem or a completely different one.

I've seen also this being trigerred by `-encoding:utf-8`

**Comment by tgodzik** [comment]
After merging https://github.com/VirtusLab/scala-cli/pull/3139 I think this should not happen again, we can revisit this in a couple of months to see it this happened for anyone

**Comment by lbialy** [comment]
I can test this immediately as besom compiler plugin breaks any scala-cli build, how can I download a nightly version of scala-cli?

**Comment by Gedochao** [comment]
> how can I download a nightly version of scala-cli?

@lbialy 
```bash
scala-cli --cli-version nightly
``` 

Or alternatively, just use artifacts from https://github.com/VirtusLab/scala-cli/releases/tag/nightly (just make sure the relevant changes were included there already)

**Comment by lbialy** [comment]
Confirmed this solves duplicate plugin problem, at least for main scope. Test scope shows "does not compile" without any actual compilation problems in cli.

**Comment by tgodzik** [comment]
Do you have reproduction we can use?

**Comment by lbialy** [comment]
no, not really, I just tested in besom core and besom examples, besom core has tests and uses another option that caused the same problem, the one that disables autotupling.
