### ISSUE TITLE
Ignore scala code blocks in markdown sources

### ISSUE THREAD

**Issue by grzegorz-bielski** [VirtusLab/scala-cli#2711]
**Is your feature request related to a problem? Please describe.**
I would like to ignore some of the scala snippets in Markdown document. 
Sometimes in blog posts or documentation it's useful to show an example that does not compile, but still compile the rest of the code. 

**Describe the solution you'd like**
I would like to be able to define a markdown code with `ignore` keyword which will instruct `scala-cli` to ignore this code block during compilation.

````
```scala ignore
println(a)
```
````
This seems consistent with [already existing](https://scala-cli.virtuslab.org/docs/guides/power/markdown/#scala-test-snippets) `test` and `reset` keywords.

**Describe alternatives you've considered**
Currently we can prevent compiling markdown source by removing `scala` from beginning of the markdown code block, but this also removes Scala-specific syntax highlighting added by external tools.

**Comment by sierikov** [comment]
It seems that the `ignore` keyword also already [exists](https://github.com/VirtusLab/scala-cli/blob/main/modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeBlock.scala#L30). And also works, please see the attached gif. Maybe we can update also the docs to include the `ignore` keyword.



![ignore-keyword](https://github.com/VirtusLab/scala-cli/assets/22551739/2b0f1647-6bb2-47ca-a557-ff98c1826e6b)
