### ISSUE TITLE
 I can't use cs

### ISSUE THREAD

**Issue by Kiti-Nomad** [VirtusLab/scala-cli#2729]
**Version(s)**
Ple
![bc4481eb-12b2-4fd9-8959-645a2f3c9a1a(1)](https://github.com/VirtusLab/scala-cli/assets/36234602/dd6fc0d2-21eb-49ca-8182-bd9cb00ab17e)
![{2439-x-381927816518}(1)](https://github.com/VirtusLab/scala-cli/assets/36234602/7cd59086-be71-40d5-8b6b-85de4104415c)
ase provide the version(s) of Scala CLI that is affected by this bug

**Describe the bug**

**To Reproduce**
Please provide us with steps on how to reproduce the bug. Code snippets (or link to the used codebase) and used commands are especially useful.

**Expected behaviour**

**Comment by Kiti-Nomad** [comment]
maybe i use vpn will work well

**Comment by SethTisue** [comment]
Would be nice if the error message were more informative — like, what artifact was it trying to fetch from where at the time.
