### ISSUE TITLE
Constant shutdown and restart of scala-cli build server when trying to add an import that doesn't exist.

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#274]
When using `scala-cli` as a build server in Metals and you try to add an import that has a version that doesn't exist, it seems to shut down the build server and restart it constantly. This ends up looking like this:

![2021-10-23 21 52 15](https://user-images.githubusercontent.com/13974112/138569791-8319f5ca-6e85-4307-8f7b-45c275e5114f.gif)

The bottom part of the screen is the BSP logs and it basically shows diagnostics being returned that it can't find the dependency, then there is a `build/shutdown`, and then immediately another `build/initialize` that just goes on and on.

You can reproduce this with the following file:

```
import $dep.`com.lihaoyi::requests:0.6.5` // <-- doesn't exist in Scala 3

object Main extends App  {
  println("hi")
}
```

Then the moment you comment it out, it stops.

**Comment by lwronski** [comment]
@ckipp01  Thanks for reporting bug, it should be fixed in the next version of scala-cli - [PR](https://github.com/VirtusLab/scala-cli/pull/319)
