### ISSUE TITLE
Incorrect diagnostics about unused imports when importing `$deps`

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#275]
### Issue

Today when porting a script I had over to use `scala-cli` I realized that it was giving warnings about unused imports when utilizing a `$dep` import. This happens both in the editor and when using `scala-cli run .` You can reproduce this with the following code snippet:

```scala
// using scala 2.13
// using option -Ywarn-unused

import $dep.`org.mongodb.scala::mongo-scala-driver:4.3.3`
import $dep.`com.outr::scribe-slf4j:3.6.1`

import org.mongodb.scala.MongoClient

object Main extends App {

  val client = MongoClient("someFakeUri")
}
```

In your editor you'll see:

<img width="558" alt="Screenshot 2021-10-24 at 15 52 09" src="https://user-images.githubusercontent.com/13974112/138597361-6036cc76-6e6e-406b-8502-6a004e06e0a2.png">

And the same when you run it:

```
❯ scala-cli run .
Compiling project (Scala 2.13.6, JVM)
[warn] ./WakaFetch.scala:4:1: Unused import
[warn] import $dep.`org.mongodb.scala::mongo-scala-driver:4.3.3`
[warn] ^^^^^^^^^^^^^
```

### Expectation

I'd expect this not to warn since I'm using it.

Btw, I'm having tons of fun with this. This is great.

**Comment by MaciejG604** [comment]
Support for `$ivy` and `$dep` ammonite imports has been removed. (See #1678) So this issue doesn't apply anymore.
