### ISSUE TITLE
native-image package behaves as expected if source file extension is ".scala", but produces a broken binary if source  extension is ".sc"

### ISSUE THREAD

**Issue by philwalk** [VirtusLab/scala-cli#2761]
**Version(s)**
$ scala-cli --version
Scala CLI version: 1.1.4-SNAPSHOT
Scala version (default): 3.4.0

**Describe the bug**
When creating a `--graal` package, the result depends on the filename extension of the source file.
Packaging the following source files with the `--native-image` option compiles native binaries with no error messages, but only the  source with `.scala` extension actually seems to call the `main` method and print the expected message to the console.
```
# file name: Hello.scala
object Hello {
  def main(args: Array[String]): Unit =
    println("Hello Scala")
}
# file name: helloSc.sc
object HelloSc {
  def main(args: Array[String]): Unit =
    println("Hello Sc")
}
```
**To Reproduce**

<details>
<summary>Compiler output with no errors, produces a working HelloScala.exe</summary>
<pre>
scala-cli --power package HelloScala.scala --graal -o HelloScala
[...]
 Version info: 'GraalVM 22.3.1 Java 17 CE'
 Java version info: '17.0.6+10-jvmci-22.3-b13'
 C compiler: cl.exe (microsoft, x64, 19.39.33519)
 Garbage collector: Serial GC
 1 user-specific feature(s)
Produced artifacts:
 C:\Users\philwalk\workspace\scala-cli\HelloScala.build_artifacts.txt (txt)
 C:\Users\philwalk\workspace\scala-cli\HelloScala.exe (executable)
Finished generating 'HelloScala' in 29.6s.
Wrote C:\Users\philwalk\workspace\scala-cli\HelloScala.exe, run it with
  .\HelloScala.exe
</pre>
</details>

<details>
<summary>Compiler output with no errors, produces a non-working HelloSc.exe</summary>
<pre>
scala-cli --power package HelloScala.sc --graal -o HelloSc
[...]
 Version info: 'GraalVM 22.3.1 Java 17 CE'
 Java version info: '17.0.6+10-jvmci-22.3-b13'
 C compiler: cl.exe (microsoft, x64, 19.39.33519)
 Garbage collector: Serial GC
 1 user-specific feature(s)
 - com.oracle.svm.polyglot.scala.ScalaFeature
Finished generating 'HelloSc' in 26.4s.
Wrote C:\Users\philwalk\workspace\scala-cli\HelloSc.exe, run it with
  .\HelloSc.exe
</details>

**Expected behaviour**
I haven't found anything in the documentation so far, but since no error message is printed, I would have thought that the 2 executable binaries would have comparable behavior.   It seems that for the file extension `'.sc'`, the main method never gets called.

**Comment by Gedochao** [comment]
This is the expected behaviour. 
```scala
// file: hello.sc
object HelloSc {
  def main(args: Array[String]): Unit =
    println("Hello Sc")
}
```
main methods in `*.sc` files aren't recognised, this is by design. 
The `HelloSc` object is inside of the script wrapper.
Take a look at the generated code.
```scala
final class hello$_ {
def args = hello_sc.args$
def scriptPath = """hello.sc"""
/*<script>*/
object HelloSc {
  def main(args: Array[String]): Unit =
    println("Hello Sc")
}
/*</script>*/ /*<generated>*//*</generated>*/
}

object hello_sc {
  private var args$opt0 = Option.empty[Array[String]]
  def args$set(args: Array[String]): Unit = {
    args$opt0 = Some(args)
  }
  def args$opt: Option[Array[String]] = args$opt0
  def args$: Array[String] = args$opt.getOrElse {
    sys.error("No arguments passed to this script")
  }

  lazy val script = new hello$_

  def main(args: Array[String]): Unit = {
    args$set(args)
    val _ = script.hashCode() // hashCode to clear scalac warning about pure expression in statement position
  }
}

export hello_sc.script as `hello`
```

The main class is inside of the `hello$_` wrapper, so there's no way it could be recognised. This is how Scala CLI scripts work.
```bash
scala-cli hello.sc
# Starting compilation server
# Compiling project (Scala 3.3.1, JVM (17))
# Compiled project (Scala 3.3.1, JVM (17))
```

**Comment by Gedochao** [comment]
Using a script, the hello world is simplified down to:
```scala
// file: fixed-hello.sc
println("Hello Sc")
```
So yes, those sources are treated differently.
```bash
scala-cli hello.sc
# Compiling project (Scala 3.3.1, JVM (17))
# Compiled project (Scala 3.3.1, JVM (17))
# Hello Sc
```

For more, please take a look at [the Scripts doc](https://scala-cli.virtuslab.org/docs/guides/scripting/scripts/).

**Comment by Gedochao** [comment]
> I haven't found anything in the documentation so far, but since no error message is printed, I would have thought that the 2 executable binaries would have comparable behavior. It seems that for the file extension '.sc', the main method never gets called.

@philwalk FYI here's the relevant doc on this known incompatibility with the old runner (and others)
https://scala-cli.virtuslab.org/docs/guides/introduction/old-runner-migration#main-class-in-a-sc-input

**Comment by philwalk** [comment]
> > I haven't found anything in the documentation so far, but since no error message is printed, I would have thought that the 2 executable binaries would have comparable behavior. It seems that for the file extension '.sc', the main method never gets called.
> 
> @philwalk FYI here's the relevant doc on this known incompatibility with the old runner (and others) https://scala-cli.virtuslab.org/docs/guides/introduction/old-runner-migration#main-class-in-a-sc-input

Thanks for the reference!

**Comment by philwalk** [comment]
btw, Thanks for a fantastic project!

While reading the documentation relevant to this issue, I found what might be errors, is the best way to address them to submit a documentation PR?

For example [this section](https://scala-cli.virtuslab.org/docs/guides/introduction/old-runner-migration#:~:text=Files%20with%20no%20extensions%20have%20been%20supported%20in%20the%202.13.x%20old%20runner%2C%20but%20not%20in%203.x.) states:
```
Files with no extensions have been supported in the 2.13.x old runner, but not in 3.x.
```
The `scala 3.x` script runner has always supported scripts with no file extensions.   It's needed if scala scripts are to shadow os binaries, and is useful in various other ways.



~~I'm trying to figure out how to migrate 1100+ scripts to scala3-3.5.x, with modifications that are confined to the `shebang` line.  The vast majority have the `.sc` extension.    In that regard, treating the filename extension as a runtime parameter is especially problematic.   Is there a command line option that tells `scala-cli` to pretend that the filename extension is ".scala"?~~

~~I can't easily rename these scripts is because it will break lots of other things, and I would have to restore everything to the way it was if I ever need to revert back to scala 3.4.x~~

I was able to port a script named `showArgs` from `scala 3.x` to `scala-cli` without renaming the file.
~~with 100% of the modifications restricted to the `shebang` line.~~

***scala 3***
```scala
#!/usr/bin/env -S scala
object ShowArgs {
  def main(args: Array[String]): Unit = {
    for ((a,i) <- args.zipWithIndex) {
      printf(s"arg %2d:[%s]\n",i,a)
    }
  }
}
```
***scala-cli***
script `showArgs`:
```scala
#!/usr/bin/env -S scala-cli shebang
ShowArgs.main(args)
object ShowArgs {
  def main(args: Array[String]): Unit = {
    for ((a,i) <- args.zipWithIndex) {
      printf(s"arg %2d:[%s]\n",i,a)
    }
  }
}
```
