### ISSUE TITLE
TASTy version warning is perplexing

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#2768]
just a UX thing, but could this warning message be improved?

![Screenshot_from_2024-03-02_20-19-10](https://github.com/VirtusLab/scala-cli/assets/161079/c17108b6-3cf0-4fc2-95ca-92fcc25dff4f)

is there something the user needs to know here? like about a feature that won't work properly as a result of this?

if there are no user-visible consequences of this, it could say nothing... or if there are user-visible consequences, is it possible to briefly say what they are?

I genuinely don't know what "cleans up source paths" might be referring to

**Comment by Gedochao** [comment]
Yeah... I will improve the warning message, but generally speaking, this pops up because Scala CLI v1.1.3 officially supports Scala up to 3.3.1, while this would pop up with 3.4.0. 
Should be cleaned up in Scala CLI v1.2.0 later this week.

**Comment by SethTisue** [comment]
I do see this warning more than average users, since I'm often testing Scala versions that haven't been released yet.
