### ISSUE TITLE
jsEsModuleImportMap reported as invalid directive

### ISSUE THREAD

**Issue by Quafadas** [VirtusLab/scala-cli#2791]
**Version(s)**
1.2.0

**Describe the bug**
```//> using jsEsModuleImportMap importmap.json```

This line is valid compiles runs and links, but it appears to get flagged by the BSP server somehow, as invalid, making it not the ideal experience. 
```Unrecognized directive: jsEsModuleImportMap with values: importmap.json```

**To Reproduce**
Add this line and import the build

**Expected behaviour**
No compile error reported.

**Comment by Quafadas** [comment]
I would obviously be happy to try and sort this myself - although I'd very much welcome a hint on where to start...

**Comment by Gedochao** [comment]
@Quafadas Maybe try to add a test reproducing this issue in https://github.com/VirtusLab/scala-cli/blob/main/modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala, and then work from there. If it only breaks in BSP, then we need a BSP-specific integration test.

I also assigned you to solving this.

**Comment by Quafadas** [comment]
Urgh... I have some $WORKarounds for $WORK. One of which was making it connect to the prior scala-cli BSP. 

Problem = User. Not bug - closing.
