### ISSUE TITLE
Insert missing pat-mat cases action changes wrong lines

### ISSUE THREAD

**Issue by ghostbuster91** [VirtusLab/scala-cli#2812]
**Version(s)**
1.2.0

**Describe the bug**
Given a following code:
```scala
//> using scala 3.3.3

enum Animal {
  case Cat(name: String)
  case Dog(name: String)
}

object Main {
  def foo(a: Animal) = {
    a match
      case Animal.Cat(name) => println(name)

  }
}
```
scala3 compiler reports pattern not exhaustive diagnostic together with an actionable item to fix it. Applying that actionable adds the missing case statement into an incorrect position. This works correctly when running from within an sbt project.

Result of application of the actionable:
```scala
//> using scala 3.3.3

enum Animal {
  case Cat(name: String)
  case Dog(name: String)
}

object Main {
  def foo(a: Animal) = {
    a match
      case Animal.Cat(name) => println(name)

  }
}

      case Animal.Dog(_) => ???
```

**To Reproduce**
Paste the snippet into `*.sc` file and import it.

**Expected behaviour**
I would expect the actionable to insert the missing case in the correct place as it does in case of sbt project.

**Comment by ghostbuster91** [comment]
Turned out this is due to calling file `*.sc` rather than `*.scala`. So the issue probably has to do more with worksheets in metals than scala-cli.

**Comment by tgodzik** [comment]
Looks like a legit issue with scripts also, not only worksheets
