### ISSUE TITLE
Store unexpected exceptions (or all of them?) somewhere inside .scala

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#282]
from @alexarchambault :

So that: we don't print the whole stack trace by default, but users can still report issues with the full stack trace, even in hard to reproduce cases.

**Comment by romanowski** [comment]
The idea would be to catch all non-fatal exceptions that we do not understand and prints only error message and steps to see whole stacktrace (similar to what sbt does). The full stack trace should be stored in a file inside the .scala directory with a randomized name.

https://github.com/VirtusLab/scala-cli/blob/master/modules/cli/src/main/scala/scala/cli/ScalaCli.scala#L92-L97 seems like a good place to to add this kid of logic (but this needs to be verified).

**Comment by tpasternak** [comment]
@romanowski I don't fully understand what are "non-fatal" exceptions in this context

Recoverable errors are usually handled within commands.

If a command leaks an exception, we may catch it in the place you pointed out, but these are rather "fatal" exceptions (non-recoverable)

**Comment by romanowski** [comment]
Ah, sorry. This task is about UX, so all non-cached earlier errors are presented in user friendly way to user, however full information (stack traced) is logged and can be inspected. 

The source of inspiration may be `sbt`: when task results in non-recoverable exception only Error kind and message are printed and full stack trace is hidden (but logged) with information how to see it all.

**Comment by tpasternak** [comment]
Sth like this?
![hidden-exception](https://user-images.githubusercontent.com/1066003/145000493-bea2c731-e14d-4332-abb7-1d74a0b0ecac.gif)

**Comment by tpasternak** [comment]
Fixed in #461
