### ISSUE TITLE
Can't pass -Xmx… to native launchers via --java-opt

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#283]
from @alexarchambault:

When running
```bash
scala-cli test src --java-opt "-Xmx1g"
```
it seems native-image assumes the `-Xmx1g` is for itself, and it seems it removes from the argument list.

(There are options to disable native-image messing with the options like this, coursier uses those.)

**Comment by tpasternak** [comment]
Not only `-X..` https://github.com/oracle/graal/blob/6773ebc7dcd59ec7185ba5f5db70b714aa43e108/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/option/RuntimeOptionParser.java#L81

**Comment by tpasternak** [comment]
ok, looks quite easy, we just need to run `native-image -H:-ParseRuntimeOptions`

**Comment by alexarchambault** [comment]
> ok, looks quite easy, we just need to run `native-image -H:-ParseRuntimeOptions`

There's this, except this prevents users from setting Java properties for the Scala CLI process itself, which can be handy for users relying on proxies in particular… This also prevents users from setting the Scala CLI process memory limits, via `-Xmx…` (although I'm not sure if that can be useful or if anyone does this).

As a workaround for the Java properties, we can add a hook in `scala.cli.ScalaCli.main`, doing a `args.takeWhile(_.startsWith("-D"))`, and calling `System.setProperty` itself.

For the memory settings, I don't know if there's a workaround, but it seems we can live without one.

**Comment by tpasternak** [comment]
~We don't need it for the properties, only the -`-Dgraal=` are filtered out~

**Comment by tpasternak** [comment]
right, -D are filtered out as well

**Comment by tpasternak** [comment]
#474

**Comment by tpasternak** [comment]
> scala.cli.ScalaCli.main, doing a args.takeWhile(_.startsWith("-D"))

This is very risky, as the user who runs `scli run app.sc --java-opts -Dfoo=bar` probably does not expect it's passed to the host vm. It's also not very hard to collide with host VM properties

**Comment by tpasternak** [comment]
ok, if we will do "takeWhile" then it would work, nvm
