### ISSUE TITLE
Add CLI option or command to "explain" config (in which file / at what position is each setting set) 

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#284]
from @alexarchambault 

Right now, [`BuildOptions`](https://github.com/VirtusLab/scala-cli/blob/4ae17a428933c0edc118a065838c236c255f719c/modules/build/src/main/scala/scala/build/options/BuildOptions.scala) is just a (set of) case class(es), whose fields are options or sequences. An important aspect of these case classes and fields is the `orElse` method defined on those case classes, allowing to "sum" options from various sources.

For an "explain" feature, we could replace those `Option`s and `Seq`s by custom types, like `CfgOption` and `CfgList`, that would behave like `Option` and `List`, but also retain the exact file and position of each setting, like
```scala
sealed trait CfgOption[+T]
case class CfgSome[+T](
  value: T,
  source: CfgSource,
  overrides: List[CfgSource]
)
case object CfgNone extends CfgOption[Nothing]

sealed trait CfgList[+T]
case class CfgCons[+T](
  value: T,
  source: CfgSource,
  tail: CfgList[T]
)
case object CfgNil extends CfgList[Nothing]
```

`CfgOption` would have an `orElse` like
```scala
def orElse(other: CfgOption[T]): CfgOption[T] =
  (this, other) match {
    case (a: CfgSome[T], b: CfgSome[T]) =>
      CfgSome(a.value, a.source, b.source :: b.overrides ::: a.overrides)
    case (a: CfgSome[T], CfgNone) => a
    case (CfgNone, b: CfgSome[T]) => b
    case (CfgNone, CfgNone) => CfgNone
  }
```

That way, every time we set a value in `BuildOptions` in the code, we would have to provide a `CfgSource`, giving the location where the option is set. And a `show-config` sub-command or an `--explain` option could use the `source` fields of `CfgSome` and `CfgList` to "explain" things.

**Comment by alexarchambault** [comment]
This has been fixed quite a long time ago (with `Positioned[_]`)
