### ISSUE TITLE
Allow separating scope of "using" directives in markdown files

### ISSUE THREAD

**Issue by MateuszKubuszok** [VirtusLab/scala-cli#2877]
**Is your feature request related to a problem? Please describe.**

I am using Scala CLI to show runnable examples in [the documentation](https://chimney.readthedocs.io/). Therefore, I would like to use Scala CLI for validating that these examples indeed compile.

The issue is that the documentation has to show code examples which work only with certain Scala version (and not always the same version), it might require showing the code example requires particular compiler flags, etc. This means that code examples would have to be split into different "scopes". Currently Scala CLI does not [provide such separation of "using" directives](https://scala-cli.virtuslab.org/docs/guides/power/markdown#using-directives-and-markdown-code-blocks):

> scala snippets inside of a Markdown input are not isolated. Each using directive applies to the whole project's context. A directive defined in a later snippet within the same source may override another defined in an earlier one.

Providing such isolation (it might require adding some keyword to the snippet) would unblock such testing.

**Describe the solution you'd like**

I'd like to be able to tell Scala CLI that 2 snippets inside the same markdown file are isolated and using directives from one should not leak nor override another. Similarly to how [`reset`](https://scala-cli.virtuslab.org/docs/guides/power/markdown#reset-scope-for-scala-snippets) works for the code within the snippets.

**Describe alternatives you've considered**

The alternative is that I would not rely on Scala CLI's ability to parse markdowns at all, and extract snippets into `.sc` files myself with a custom script.

**Additional context**

The examples that I am talking about are defined within https://github.com/scalalandio/chimney/tree/master/docs/docs. Additionally, I would need there the ability to ignore some snippets, or assume that snippets are showing errors, but that can be worked around manually.

**Comment by Gedochao** [comment]
> Additionally, I would need there the ability to ignore some snippets, or assume that snippets are showing errors, but that can be worked around manually.

@MateuszKubuszok We already have ignoring snippets with the `ignore` keyword, it's just not documented. To be tracked under:
- https://github.com/VirtusLab/scala-cli/issues/2711

Regarding the snippets showing errors, you could raise a feature request for that separately.

As for the feature request here, what you'd like is, as far as I understand, being able to declare separate snippets as separare Scala CLI projects, with different using directives, compiler options and all. That means separate modules, like in a proper build tool - and Scala CLI does not support (and neither does it mean to ever support) multi-module projects. 

Theoretically, your use case could be fulfilled by running those snippets as separate builds, one after another. That'd be pretty far from optimised performance-wise, but I suppose it'd fit the purpose... Might be worth a spike, if anyone is interested in implementing this. I'm not convinced if it's something we want, though...

**Comment by MateuszKubuszok** [comment]
> As for the feature request here, what you'd like is, as far as I understand, being able to declare separate snippets as separare Scala CLI projects, with different using directives, compiler options and all. That means separate modules, like in a proper build tool - and Scala CLI does not support (and neither does it mean to ever support) multi-module projects.


@Gedochao for now I solved my problem with [writing a library](https://github.com/MateuszKubuszok/scala-cli-md-spec/).

**Comment by Gedochao** [comment]
Since the use case seems to be covered well enough by a library, I don't think this will be worked on in the foreseeable future.
If someone wants to have a go at this, feel free to reopen.
Meanwhile, I'm closing this.
