### ISSUE TITLE
-with-compiler option does not include `scala3-staging_3` or `scala3-tasty-inspector_3` on the classpath

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#2879]
https://github.com/VirtusLab/scala-cli/blob/9a7fda1809808b2307e5092f3367769c7f7dcaa2/modules/options/src/main/scala/scala/build/options/BuildOptions.scala#L102-L113

^ see here. When the compiler is for scala 3, we should also add `dep"org.scala-lang::scala3-staging::${sp.scalaVersion}"` and `dep"org.scala-lang::scala3-tasty-inspector::${sp.scalaVersion}"`

This is an incompatibility with the current scala launcher.

**Comment by bishabosha** [comment]
@tgodzik @kasiaMarek @Gedochao this affects SIP-46 compatibility. (although a workaround for script users is to add `--dep "org.scala-lang::scala3-staging:$SCALA_VERSION"`, and ensure the version matches)

**Comment by tgodzik** [comment]
Thanks for checking this out! We will have to fix that after the long weekend then. @Gedochao is out and 1-3 no one is working in Poland.
