### ISSUE TITLE
Ensure all or most build options can be changed via CLI options and using directives

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#288]
Build options live [here](https://github.com/VirtuslabRnD/scala-cli/blob/cc67ab6914b8a6aa2817ffe59b986fda5fcdbeba/modules/build/src/main/scala/scala/build/options/BuildOptions.scala).

CLI options live in `*Options.scala` files [here](https://github.com/VirtuslabRnD/scala-cli/tree/cc67ab6914b8a6aa2817ffe59b986fda5fcdbeba/modules/cli/src/main/scala/scala/cli/commands).

Using directives are currently defined [here](https://github.com/VirtuslabRnD/scala-cli/blob/cc67ab6914b8a6aa2817ffe59b986fda5fcdbeba/modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala#L94-L203) (needs to be moved to a separate file).

**Comment by tpasternak** [comment]
~native opytions~
~js  options~ #492 
~java props~ #493

**Comment by tpasternak** [comment]
#492 #493
