### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#291]
from @alexarchambault 

We could build native images for the aarch64 architecture (aka ARM64 - that's the architecture of Raspberry Pi 4 for example).

GitHub actions has no aarch64 runners, so building those on the CI involves running docker containers with qemu emulation, like how this action does. coursier uses this action for example. It takes significantly longer to run (in the coursier CI, ~20 minutes for native workflows vs > 1h for emulated aarch64), so we may want to only run that on the master branch.

We may also want to build deb packages for aarch64, and publish an apt repo for it too, targeted at raspberry pi 4 users.

**Comment by kubukoz** [comment]
rel: https://github.com/actions/runner/issues/805 <- for github actions

**Comment by lwronski** [comment]
I am closing this issue as a duplicate of https://github.com/VirtusLab/scala-cli/issues/691.
