### ISSUE TITLE
Migrate from the custom M1 runner to the official Github one

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#2936]
**Version(s)**
v1.3.2

**Describe what needs to be done and why**
We are currently using our own custom MacOS M1 runner for `aarch64` jobs. We could and should migrate to the official M1 runner provided by GitHub. This would also enable us to run those jobs outside of the `main` branch, even on external contributor PRs.

**Requirements**
- [x] migrate `scala-cli` jobs to `macos-14`
- [x] implement a script verifying the architecture for MacOS builds (as there is no separate MacOS runner nametag for the new architecture, just a version descriptor)
- [x] migrate [`coursier-m1`](https://github.com/VirtusLab/coursier-m1) jobs to `macos-14`
- [x] migrate https://github.com/VirtusLab/scala-cli-setup jobs to `macos-14`

**Describe alternatives you've considered**
We could stay on the custom runner we are using, but this should make it easier to maintain long-term (as someone would be doing a big chunk of the maintenance for us from then on)

**Additional context**
- https://github.com/actions/runner-images/issues/9254
- https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by mkurz** [comment]
Maybe relevant?
- https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
