### ISSUE TITLE
Generate GraalVM native images from package sub-command

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#298]
It'd be great to have an option allowing to generate GraalVM native images. Ideally, it should allow one to pick a GraalVM version, decide whether it should be a Java 8 or Java 11 version of GraalVM.

coursier-jvm, that we use to download JVMs, already allows to automatically download and unpack GraalVM distributions.

The coursier helpers that we use to generate assemblies or standalone JARs should also allow to generate native images, but I'm not sure how well they work… It'd probably be better to just handle this ourselves, using coursier-jvm to download and unpack the GraalVM distributions.

It would also be interesting to ensure that this works fine along with `.deb` / `.rpm` / `.msi` / etc. generation (generating archives that don't depend on the JVM, MSI that automatically install Visual C++ redistributable, etc.)

**Comment by lwronski** [comment]
Fixed by https://github.com/VirtusLab/scala-cli/pull/773.
