### ISSUE TITLE
Split core and test sources

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#30]
For now, the exact same sources are used by all commands ( `compile`, `run`, `test`, …). We may not want to put the tests in the output of `package`, or of the upcoming `publish` command.

For that, we need to decide on a way to mark some sources as test-specific.

There could be several ways of doing that:
- assuming sources with the `.test.scala` extensions are tests,
- using a top-level directive, like
```scala
package something

tests

class MyTests extends munit.FunSuite {
  …
}
```
or
```scala
test package something

class MyTests extends munit.FunSuite {
  …
}
```
- with with the upcoming `using` syntax

**Comment by adpi2** [comment]
One thing I like in Rust is that I can put the tests in the main source files. Similarly, scala-cli could pre-process each source file to create 2 compilation units: one for main, and the other one for test.

Something like a `@test` annotation could be used on a top-level class or a top-level method.

**Comment by alexarchambault** [comment]
> Similarly, scala-cli could pre-process each source file to create 2 compilation units: one for main, and the other one for test.

The only practical issue I see in implementing this is that the CLI is currently Scala-version agnostic: we don't depend on scalac 2 or dotty, so we can't use their parsers to pre-process files.

For now, we have `import $ivy` support using scalaparse (from fastparse) to parse the first lines of each file. scalaparse is supposed to only support the Scala 2 syntax, but we're only using it to parse the first directives (packages, imports), so I guess we should be able to make it work with Scala 3-specific syntax with very little work (I don't know if it's fine with the `import something.*` syntax for example).

But maybe the scalameta parser could help here? (cc @tgodzik)
