### ISSUE TITLE
Scala Native 0.5 multithreading switch

### ISSUE THREAD

**Issue by plokhotnyuk** [VirtusLab/scala-cli#3001]
There is no any option to enable/disable multi-threading when compiling with `--native`

CLI options like `--native-multithreading enable` and `--native-multithreading disable` could be helpful to control the output of Scala Native 0.5+ compiler

It could help for faster troubleshooting of issues related to multi-threading and for reducing of CPU usage and memory footprint in single-threaded applications.

**Comment by LeeTibbert** [comment]
Yes, good to see a PR to provide this capability.

I am doing some SN library work and it will be incredibly useful & devo time-saving to have this capability.
It means that I do not have to go and edit my local .sbt file between runs (and remember in the middle of 
complex debugging sessions how I had last set it).

Thanks to all who brought this about.
