### ISSUE TITLE
package --js not regenerating for script .sc

### ISSUE THREAD

**Issue by 3xau1o** [VirtusLab/scala-cli#3007]
**Version(s)**
scala-cli 1.4.0

**Describe the bug**
Watch, regenerate js works only if the file is an scala with main methods, when the file is an .sc script the file never updates when using `-w -f` with `package`

**To Reproduce**
add file  `src/test.sc`
```scala
//> using platform scala-js

println("test")
```
generate js
` scala-cli --power package -f -w src/test.sc --js --js-mode dev`

run the file with node output should be `"test"`
```node ./test.js```

update print in test.sc
```scala
println("new test")
```

you'll see 
![image](https://github.com/VirtusLab/scala-cli/assets/19735362/390a39b3-b4d6-4b62-8064-da0d3d71c52a)

run js again output should be `"new test"` however is still `"test"`
```node ./test.js```

**Expected behaviour**
Changing a script file when running `package` with watch and overwrite force, should regenerate the js with the new changes

**Comment by Gedochao** [comment]
Fixed in https://github.com/VirtusLab/scala-cli/pull/3218
