### ISSUE TITLE
can not use explict repo in offline mode when coursier cache has only POM file

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#3021]
**Version(s)**
1.4.0 (problematic in scala 3.5.0-RC3 release when installing from `cs install scala:3.5.0-RC3`)

**Describe the bug**
in offline mode, If the coursier cache is only partially populated by POM, and no jar file (such is the state after running the `cs install` command) - then any explicitly added local repository is ignored and classpath resolution fails

**To Reproduce**
follow steps in https://github.com/coursier/coursier/issues/3024

**Expected behaviour**
I have passed an explicit repo in offline mode, I expect to resolve the classpath from there, the fact that coursier complains underneath is a leaky abstraction.

**Comment by Gedochao** [comment]
Known workarounds:
- remove the Scala compiler pom from Coursier cache (or just purge the cache)
- pass an empty directory in the `COURSIER_CACHE` env variable
