### ISSUE TITLE
scala-cli eagerly sets `-release` / `-java-output-version`, which prevents compiling on new Java versions

### ISSUE THREAD

**Issue by lrytz** [VirtusLab/scala-cli#3115]
`scala-cli compile` always sets `-release N` (aka `-java-output-version` on Scala 3) where N is the Java version.

This prevents compiling on a Java version which is not yet known to the compiler:

```
➜ sandbox cat A.scala
class A { java.io.IO.print(1) }

➜ sandbox scala compile --server=false -S 3 A.scala
23 is not a valid choice for -java-output-version
  scalac -help  gives more information
Compilation failed
```

I can manually set an older `-release` version, but then new API is not available:

```
➜ sandbox scala compile --server=false -S 3 A.scala -O -release -O 22
-- [E008] Not Found Error: /Users/luc/code/scala/scala13/sandbox/A.scala:1:18 --
1 |class A { java.io.IO.print(1) }
  |          ^^^^^^^^^^
  |          value IO is not a member of java.io
1 error found
Compilation failed
```

Invoking the compiler manually works, the compiler writes the classfile using the default version 52 (corresponds to Java 8):

```
➜ sandbox java -cp $(cs fetch -p org.scala-lang::scala3-compiler:3.5.0) dotty.tools.dotc.Main -usejavacp A.scala
➜ sandbox asm A.class && cat A.asm
// class version 52.0 (52)
// access flags 0x21
public class A {

  // compiled from: A.scala
...
```

@Gedochao mentioned that the flag might have been added due to some interaction with bloop (cc @kasiaMarek, @tgodzik)

**Comment by kasiaMarek** [comment]
The flag is not added for bloop, bloop handles adding this flag on its own. It is added when `server=false`. 
https://github.com/VirtusLab/scala-cli/blob/052ed4d6f1c227c575e544effcfaf4a3dd7ef851/modules/build/src/main/scala/scala/build/Build.scala#L865-L867

Probably we could avoid adding it if scala compiler jdk matches required jdk, but checking the jvm version for simple compiler seems to be missing an implementation:
https://github.com/VirtusLab/scala-cli/blob/052ed4d6f1c227c575e544effcfaf4a3dd7ef851/modules/build/src/main/scala/scala/build/compiler/SimpleScalaCompiler.scala#L23-L24

**Comment by lrytz** [comment]
Ah, I'm indeed using `--server=false`

> bloop handles adding this flag on its own

So is also setting `-release`? Then maybe it was done for consistency with bloop?

What is the "required jdk" you mention?

**Comment by kasiaMarek** [comment]
> What is the "required jdk" you mention?

I just mean the one Scala CLI calculates from options like `jvm xx`.
