### ISSUE TITLE
missing `--javac-option` similar to `-scalac-option`

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#315]
We also need to add test like this one https://github.com/VirtusLab/scala-cli/blob/ae511207f2ef4408c3a0a4f12f280a402bae686a/modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala#L208-L225

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/VirtusLab/scala-cli/pull/567 (by https://github.com/VirtusLab/scala-cli/pull/567/commits/fd3410aa277ad872272f9dba3b4a2e534c0f5cc8 in particular), that added `--javac-plugin` and `--javac-option`.
