### ISSUE TITLE
Cookbook: tests with scalatest

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#326]
A short cookbook that will show how to define tests using ScalaTest. I should cover 2 different test files and test utils.

An example test using [Munit](https://github.com/VirtusLab/scala-cli/blob/master/examples/scalatest/MyTests.scala)

**Comment by SethTisue** [comment]
duplicate of #323

**Comment by lwronski** [comment]
Thanks, so I will close this issue.
