### ISSUE TITLE
Scala cli should allow to create preloaded docker container

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#328]
Currently, with docker image is created we do not preload all of its dependencies for assembly so we can reuse that.

**Comment by lwronski** [comment]
It should already work in `scala-cli`. There was added `--standalone` flag, which enforces to preload all of the dependencies, this flag is automatically set to `true` if someone wants to package applications into docker image.
#139

**Comment by SethTisue** [comment]
I've been assigned this ticket for the spree tomorrow, but it sounds like it's already done and the ticket should be closed?
