### ISSUE TITLE
`publish` to Maven Central failing despite correct Sonatype conf

### ISSUE THREAD

**Issue by mattlianje** [VirtusLab/scala-cli#3314]
**Describe the bug**
- Trying to publish a snapshot to Maven Central like this via my [project.scala](https://github.com/mattlianje/flowers/blob/master/cli/project.scala) using `scala-cli publish .` after going through `publish-setup`.
- I hit this:
```
Please bear in mind that non-ideal user experience should be expected.
If you encounter any bugs or have feedback to share, make sure to reach out to the maintenance team at https://github.com/VirtusLab/scala-cli
Publishing io.github.mattlianje:flowers_3:0.1.0-SNAPSHOT
 ✍️  Signed 4 files
 ✔ Computed 16 checksums
 🚚 Wrote 24 files

Uploading files failed!
Possible causes:
- incorrect Sonatype credentials
- incorrect Sonatype server was used, try 'central'
 -> consult publish subcommand documentation
```
- Step taken:
     - generated a PGP key pair using `scala-cli --power config --create-pgp-key --pgp-password MY_CHOSEN_PASSWORD`
     - set creds with `scala-cli --power config publish.credentials s01.oss.sonatype.org env:SONATYPE_USER env:SONATYPE_PASSWORD`
     - Double and triple checked creds with `scala-cli config --dump` (below) also confirmed I am using `central-s01`:
     ```
      "publish": {
    "credentials":  [{"host":"s01.oss.sonatype.org","user":"value:mattlianje","password":"value:***"}],
    "user": {
      "email":    "matthieu.court@protonmail.com"
    }
  }
  ```

**Version(s)**
```
scala-cli --version
Scala CLI version: 1.5.4
Scala version (default): 3.5.2
```

**Comment by Gedochao** [comment]
Likely a duplicate of https://github.com/VirtusLab/scala-cli/issues/2771

**Comment by mattlianje** [comment]
@Gedochao Many thanks!
