### ISSUE TITLE
Using directive for Scala Js options

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#332]
Scala CLI allows configuring following [options for Scala JS:](https://github.com/VirtusLab/scala-cli/blob/master/modules/cli/src/main/scala/scala/cli/commands/ScalaJsOptions.scala)

- jsVersion
- jsModuleKind
- jsDom

We are missing using directives parser for them similar to [one for JavaOptions](https://github.com/VirtusLab/scala-cli/blob/master/modules/build/src/main/scala/scala/build/preprocessing/directives/UsingJavaOptionsDirectiveHandler.scala).

**Comment by sjrd** [comment]
Also worth pointing out that even the "options for Scala.js" that scala-cli seems to handle are missing several options of Scala.js itself:
https://github.com/scala-js/scala-js/blob/master/linker-interface/shared/src/main/scala/org/scalajs/linker/interface/StandardConfig.scala
including important ones like `esFeatures` and `moduleSplitStyle`.

**Comment by romanowski** [comment]
Per https://github.com/VirtusLab/scala-cli/discussions/531 we should also include `jsHeader` option.

**Comment by lwronski** [comment]
Closed #332 via #539
