### ISSUE TITLE
Using directive to configure Java Properties

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#334]
Scala CLI allows to configure Java properties using `javaProp` paramter.

We are missing using directives parser for them similar to [one for JavaOptions](https://github.com/VirtusLab/scala-cli/blob/master/modules/build/src/main/scala/scala/build/preprocessing/directives/UsingJavaOptionsDirectiveHandler.scala) - maybe even add it to that file directly.

**Comment by asjad02** [comment]
#493  implementation done :)
