### ISSUE TITLE
Support for generating IntelliJ/VSCode project folders, and JVM remote debugging

### ISSUE THREAD

**Issue by benwbooth** [VirtusLab/scala-cli#345]
Hi,

Thanks for this great project. There is some prior art for Scala script running ([Ammonite](https://cgithub.com/com-lihaoyi/Ammonite), [TSK](https://github.com/tsk-tsk/tsk-tsk)). TSK has the ability to produce project files that can be used to import the script into IntelliJ and VSCode for autocompletion and JVM remote debugging. I think the ability to easily connect an IDE to a script for development and debugging would be very useful.

It looks like scala-cli already creates a project-like folder to feed to bloop in `~/.scala`. However the current generated source alters the line numbers in order to inject the `args` variable. It would be good if the generated source code did not alter the source line numbers in order to make breakpoints work more predictably when remote JVM debugging. 

Maybe scala-cli could generate .idea and .vscode files in the src-generated folder and add a command to easily allow the user to launch those IDEs and import the script as a project? And another command could be used to launch a remote debugging session with the user's chosen IDE?

Even better would be an actual command-line debugger for scala (there used to be one [here](https://index.scala-lang.org/ensime/scala-debugger/scala-debugger-api/1.0.0?target=_2.11) but it appears to be dead). But that's probably outside the scope of this project.

Thanks agani!

**Comment by Gedochao** [comment]
Instead of generating `.idea` and `.vscode` files, we are now supporting a more generic solution in `BSP`.
It is also possible to rely on the `BSP` server for debugging.
Please let us know if you run into problems, I'm closing this ticket.
