### ISSUE TITLE
Unit tests for project configuration

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#362]
https://github.com/VirtusLab/scala-cli/pull/361 shows that our integration test suite isn't perfect and we need more finer-grain unit tests to verify if various configuration options are working correctly.

**Comment by lwronski** [comment]
IMO we can close it issue. Now, we have classes `TestInputs.scala` which is used for unit test, for example [here](https://github.com/VirtusLab/scala-cli/blob/cd31509822841f85efc531643ed8f605c6b63455/modules/build/src/test/scala/scala/build/tests/BuildOptionsTests.scala#L364).
