### ISSUE TITLE
scala-cli browse attempts to download JDK

### ISSUE THREAD

**Issue by bs76** [VirtusLab/scala-cli#365]
when `scala-cli browse *.scala` is run, it first attempts to download JDK:

```
~/w/s/abcd ❯❯❯ scala-cli browse *.scala
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz
```

despite the fact java already is installed and in path:
```
~/w/s/abcd ❯❯❯ which java
/usr/bin/java
~/w/s/abcd ❯❯❯ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
~/w/s/abcd ❯❯❯ 


```
Using `--java-home` avoids downloading the JDK. 

IMHO another JDK *should not* be downloaded, unless explicitly requested

**Comment by romanowski** [comment]
Hi @bs76, does this manifests on other commands (like run, compile)?

**Comment by bs76** [comment]
No, other commands (run,compile) work as expected -- no JDK download attempt, default java is used

**Comment by tpasternak** [comment]
It's because we're enforcing jvm v8 in order to run metabrowse, cc @alexarchambault

**Comment by kubukoz** [comment]
Metabrowse is now gone, shall we close this?

**Comment by tgodzik** [comment]
Yep, makes sense!
