### ISSUE TITLE
Diagnostics being published for `.scala/.../src_generated` instead of source

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#368]
I haven't been able to nail down when this happens, but it's been happening semi-frequently now for me where in certain projects diagnostics weren't getting published to the editor (Metals). When taking a closer look at the BSP logs I noticed that the diagnostics were getting published, but not for the actual uri of my file, but of the generated sources.

```
[Trace - 09:42:40 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/site/src/.scala/project_d476da5045/src_generated/main/Main.scala"
  },
  "buildTarget": {
    "uri": "file:/Users/ckipp/Documents/scala-workspace/site/src/.scala/?id\u003dproject_d476da5045"
  },
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 43,
          "character": 42
        },
        "end": {
          "line": 43,
          "character": 42
        }
      },
      "severity": 1,
      "source": "bloop",
      "message": "missing parameter type for expanded function\nThe argument types of an anonymous function must be fully known. (SLS 8.5)\nExpected type was: (?, ?) \u003d\u003e ?"
    }
  ],
  "reset": true
}
```

I'd expect diagnostics to never be reported for these sources. I assume that scala-cli is supposed to map this back to the position of the original source file, but for some reason this isn't happening here.

**Comment by lwronski** [comment]
@ckipp01  Thanks for reporting
 
In version 0.0.9 I saw similar behaviour, that diagnostics were published for `.scala/.../src_generated` instead of source.

I can't reproduce this problem in the latest version of Scala CLI `0.1.0`, can you check if you still have the same problem?

**Comment by ckipp01** [comment]
I haven't hit on it at all for quite some time, even on 0.0.9. Feel free to close this and I'll just come back to it if I hit on it again.
