### ISSUE TITLE
Add using directive for --main-class

### ISSUE THREAD

**Issue by fourth44** [VirtusLab/scala-cli#370]
Many command-line flags can be set with 'using' directives, but --main-class cannot.
It would be nice to have a default main-class (similar to how a META-INF/manifest.mf with main class is set).
I think the command-line flag --main-class is too technical for the intended users of my small apps (i.e. colleagues). I would like to keep a small number of related 'apps' in a single project, each with different command-line arguments, but where one should be the default.

**Comment by przemek-pokrywka** [comment]
I think that the --main-class option (and the proposed related directive) should only be necessary if there was ambiguity regarding which class is scala-cli to pick.

I think that the best way to resolve the ambiguity is to first check if the scala file only contains one class with the main method.

I think that in most cases a single file will contain at most one such class. Then nobody would need to specify the flag, nor the directive, a win situation.

The proposed directive would then be only useful if a single file contained two or more classes with the main method.

**Comment by fourth44** [comment]
My example is a small project with 3 main programs in multiple files, which share some bootstrapping code, but one of the main methods is the one to be used in 90% of cases. It's to much hassle to put the shared code in a library. I could use scala-cli to build the assembly fat jar and have my use case via 'java -jar' etc, where the main class can also be overridden, but I don't see any reason why the main-class in mainifest.mf should _not_ have a using directive equivalent. (I intend to use scala-cli not only on single-file projects but run it on directories with a small number of files).

**Comment by przemek-pokrywka** [comment]
I agree, a main class directive would make perfect sense for assembly jars.

**Comment by przemek-pokrywka** [comment]
Regarding the local usage, whenever I had a multi file project (DoThis.scala, DoThat.scala), I would rather put different main methods to distinct files, for easier calling:

scala-cli DoThat.scala

And have scala-cli figure out, that I want to use the main method from the given file.

That would be more convenient for me than having to define a main method directive.

**Comment by romanowski** [comment]
My thinking initially was similar to @przemek-pokrywka - using directive for the main method is not needed since people will put the only a single main method in their projects. However, I ended up with multiple projects since then with 2 or more main methods I think we should have such directive.

For anyone interested in picking this up. directive for main classes should be similar to one for [Java Options](https://github.com/VirtusLab/scala-cli/blob/master/modules/build/src/main/scala/scala/build/preprocessing/directives/UsingJavaOptionsDirectiveHandler.scala)

**Comment by fourth44** [comment]
I'll make a PR.
