### ISSUE TITLE
using resource "./my-file" does not add the file to the classpath

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#395]
It seems that the `resource` directive has no effect on the classpath.

~~~ scala
// using resource "./foo.txt"
// using scala 3.1.0

import scala.io.Source

@main def run() =
  Source.fromInputStream(getClass.getResourceAsStream("/")).getLines().foreach(println)
~~~

~~~ text
$ ls
foo.txt  using-resource.scala
~~~

~~~ text
$ scala-cli using-resource.scala 
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
run.class
run.tasty
using$minusresource$package.class
using$minusresource$package.tasty
using$minusresource$package$.class
~~~

Note that `foo.txt` is not part of the resources.

Expectation: `foo.txt` is listed as a resource.

**Comment by tpasternak** [comment]
Hey, I'm not sure if I understand this correctly, but it looks like calling `getClass.getResourceAsStream(path)` takes the first classpath entry containing a resource matching `path`. If you pass "/" there, what matches anything, it will just take the first classpath entry no matter what it is. 

I'm not sure if we can do anything to handle this. I'd recommend to use `getClass.getClassLoader.getResources("")` if you want to look for resources in all cp paths.

**Comment by tpasternak** [comment]
@julienrf  I'm closing this as for now. If you think it can/should be somehow fixed in Scala CLI, please let us know and feel free to reopen this issue.

**Comment by adpi2** [comment]
@julienrf is right when saying that `using resource "./foo.txt"` has no effect on the classpath. That comes from a limitation of the JVM where `-cp ./foo.txt` has no effect either. The class path of the JVM can only contain folders or jar files, not individual resource file.

To fix the issue that @julienrf describes, scala-cli would need to copy the `./foo.txt` file in an empty folder and add that folder to the classpath. I wish it would be supported but it is up to the scala-cli team to decide.

**Comment by tpasternak** [comment]
@adpi2 that's good idea. @romanowski @alexarchambault what do you think?

**Comment by tpasternak** [comment]
The other way is to keep the current behavior and rename directive to `resourceDir`

**Comment by adpi2** [comment]
> The other way is to keep the current behavior and rename directive to resourceDir

Indeed that would be less confusing in the actual behavior

**Comment by alexarchambault** [comment]
I agree with renaming that directive to something like `resourceDir` to make it less confusing.

**Comment by alexarchambault** [comment]
About reading the resource and class path stuff, maybe we should copy the content of these resource directories to the class directory (which is `.scala/project_940fb43dce-a16ef5413a/classes/main` on my machine for example), rather than adding resource directories to the class path. That way, things like `getClass.getResource` would work.

I believe this is what sbt and Mill do (IIRC, `getClass.getResource` finds resources of the class' module with sbt and Mill, as expected).

**Comment by julienrf** [comment]
I do believe that supporting `using resource <file>` makes sense. It is quite common to use an `application.conf` or a `logback.xml`.

But maybe it’s fine to move them to a `resources` subdirectory and write `// using resources "./resources"`.

**Comment by tpasternak** [comment]
https://github.com/VirtusLab/scala-cli/pull/412 Ok, the command will be renamed in the next version

**Comment by tpasternak** [comment]
For handling resource files - it's more complex but, maybe we can do it. Probably not right now

**Comment by lwronski** [comment]
Hi, currently, we don't have plans to support accepting resources as single files; users can only pass directories. I'll be closing this issue for now. If there's significant demand for this feature in the future, please let us know.
