### ISSUE TITLE
Unable to use using directives (in comments) with shebang

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#397]
~~~ scala
// using scala 3.1.0
// using lib eu.timepit::refined:0.9.27

import eu.timepit.refined.*

@main def run() = println("Hello!")
~~~

~~~ text
$ scala-cli shebang.scala
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
Hello!
~~~

And then:

~~~ diff
+ #!/usr/bin/env scala-cli
// using scala 3.1.0
// using lib eu.timepit::refined:0.9.27

import eu.timepit.refined.*

@main def run() = println("Hello!")
~~~

~~~ text
$ ./shebang.scala
Compiling project (Scala 3.0.2, JVM)
[error] ./shebang.scala:5:8: Not found: eu
[error] import eu.timepit.refined.*
[error]        ^^
Error compiling project (Scala 3.0.2, JVM)
~~~

The scala version is wrong and the dependency is missing.

I guess this is because `// using` directives are valid only if they are at the very top of the file?

**Comment by tpasternak** [comment]
Hey @julienrf thank you for reporting this. At the moment, we support shebangs only in script files (extension `.sc`). In the Script files you may also write top-level expressions, so the following code is valid:

```
#!/usr/bin/env scala-cli
// using lib "com.lihaoyi::os-lib:0.7.8"
import os._
val n = 1
```

**Comment by julienrf** [comment]
Thank you for your response! Are there other differences between `.sc` files and `.scala` files?

**Comment by julienrf** [comment]
OK, I just found the answer here: https://scala-cli.virtuslab.org/docs/guides/scripts. I confirm that renaming my file worked (I also had to remove a `package` clause).

Do you think it would make sense to support shebang on .scala files as well?

**Comment by tpasternak** [comment]
> Do you think it would make sense to support shebang on .scala files as well?

I'm not sure, @alexarchambault what do you think?

**Comment by SethTisue** [comment]
> Do you think it would make sense to support shebang on .scala files as well?

Scala 2 allows it, so I think scala-cli should as well (at least, unless specific arguments against it are brought forth).

**Comment by julienrf** [comment]
FYI, my interest in getting support of shebang on .scala files is that .scala files use exactly the same language as regular Scala projects (unlike .sc file, which don’t have the same semantics nor syntax).

**Comment by romanowski** [comment]
My personal take is that regular `.scala` files should also be allowed to have shebang. Of course, there is little sense of having shebang without a main method but this is something for limiting department.
