### ISSUE TITLE
ScalaCLI not use the newest version of scala as default

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#401]
`@main def run() = println("Hello!")`

```
$ scala-cli Main.scala
Compiling project (Scala 3.0.2, JVM)
Compiled project (Scala 3.0.2, JVM)
Hello
```

Expected:

ScalaCLI should use the newest stable version of `scala`

```
$ scala-cli Main.scala
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
Hello
```

**Comment by julienrf** [comment]
I might be hijacking this issue, but I think scala-cli should warn if there is no `using scala` directive in the project, and indicate which Scala version it is using.

Basically, programs that don’t define a Scala version are not portable. It is fine for run-and-scratch programs, but not outside of that scope.
