### ISSUE TITLE
Cannot run gist with resource file

### ISSUE THREAD

**Issue by adpi2** [VirtusLab/scala-cli#405]
## Steps

```
> scala-cli compile  https://gist.github.com/adpi2/9eaf82c559a7a24ab658ea7844cf84e3
[error] 9eaf82c559a7a24ab658ea7844cf84e3-master/day1.run.scala:2:4: Can't reference paths from sources from 9eaf82c559a7a24ab658ea7844cf84e3-master/day1.run.scala
```

## Problems

Scala-cli refuses to compile the `advent-of-code-2020-day1.scala` because of the `// using resource "./"` directive.

## Expectation

It should compile the `advent-of-code-2020-day1.scala` file and add the `input` file to its classpath.

## Notes

As an alternative I tried to open the `input` file as a file rather than a resource but there was another problem reported in https://github.com/VirtusLab/scala-cli/issues/404

**Comment by lwronski** [comment]
Thanks for reporting @adpi2
  
In the next version, we added support for resources in github gists. It was done in this [PR](https://github.com/VirtusLab/scala-cli/pull/415).
