### ISSUE TITLE
Docker Image for JVM platform contains fixed JVM 8 by default

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#413]
This causes runtime failure, if a user builds. code to jvm 11

so the app in image built with `scala-cli package --docker --jvm 11` will fail to start

https://github.com/tpasternak/scala-cli/blob/shebang-args/modules/cli/src/main/scala/scala/cli/commands/Package.scala#L355

**Comment by alexarchambault** [comment]
We should probably change that depending on `--jvm`. At least default to openjdk 8 / 11 / 17 images, picking a version higher than or equal to the one of the JVM passed via `--jvm` when possible.

We might also check if there are specific docker images for specific JVMs (zulu, graalvm, etc.), although that looks a bit like an overkill…

**Comment by tpasternak** [comment]
It's now bumped to jvm 11, closing for now https://github.com/VirtusLab/scala-cli/blob/2294fbfe9d3e90929df6c7e00215110bd3901e2d/modules/cli/src/main/scala/scala/cli/commands/Package.scala#L356
