### ISSUE TITLE
Unify naming convention for using directives and command line options

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#414]
Should we have 
```
using resourceDir .
```
or 
```
using resource-dir .
```
?

**Comment by SethTisue** [comment]
I was surprised to see `kebab-case`, since kebab case never appears anywhere else in Scala. If these are considered part of the language, I'd expect `camelCase`.

**Comment by Gedochao** [comment]
We should be using camel case in all our using directives.
It seems that the only `java-opt` doesn't abide this rule.
