### ISSUE TITLE
Website is very intensive on CPU

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#436]
I am running the website on Safari Version 15.1 (17612.2.9.1.20)

using MacBookPro15,1 with 8 core i9 2.3GHz

the CPU usage is full across the website, this impacts me because drop down lists in the sidebar of the documentation takes about 3 seconds to animate the drop down

If I never load the front page, and instead only go to the overview, (https://scala-cli.virtuslab.org/docs/overview/) then the animations remain smooth

**Comment by romanowski** [comment]
@bishabosha we switch from `svg` to `gif` and we see good improvement. Please let us know if you still think that our website is still too taxing on CPU.

**Comment by bishabosha** [comment]
Thank you for the quick fix, this definitely solved my problem
