### ISSUE TITLE
The build configuration, project structure etc. to be accessible from within the user code

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#464]
Having an option to access the directory structure (to access e.g. .tasty files) or configuration for the build would be really useful in some situations (e.g. accessing the library or scala version at runtime).

Adding it by default is not a good idea but I think we can have a using directive (e.g.`using build-config`) that will activate this feature (adding an object, resources etc. to the classpath or generating a  source or using a library).

The provided API in many places should be optional since e.g. build structure only make sense if run from scala-cli, not from packaged application.

**Comment by MaciejG604** [comment]
Fixed by BuildInfo in #2249
