### ISSUE TITLE
More modern jdk

### ISSUE THREAD

**Issue by francisdb** [VirtusLab/scala-cli#488]
I was watching the [DevInsideYou cast on scala-cli](https://youtu.be/c5lBokinwas) and the first thing I see being installed is JDK8. The current LTS is 17 and might be a bit too new for the Scala ecosystem but 11 has been around for a long time now.

https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by tpasternak** [comment]
Hey @francisdb, thanks for reporting this!

If there's no JVM installed on the machine, then it indeed downloads JVM8. It can be modified with `--jvm` option.

Nevertheless I agree we probably should consider update to JVM11 or JVM17, @lwronski  @alexarchambault  @romanowski  what do you think?

**Comment by tpasternak** [comment]
Done in #516
