### ISSUE TITLE
diffucult to understand which version of scala-cli I have or if it is the latest or if I need to update or if I have duplicates on path 

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#543]
* scala-cli should accept --version and version and perhaps also empty -v:
* if I run `scala-cli about` I'm not getting the real version 
(I have 0.0.9 but below `about` is showing something else 0.0.0+274-... so user is confused if it is the latest version or not)
* can scala-cli let me know if there is a new version to install?
* can scala-cli update itself?
```
$ scala-cli --version
Unrecognized argument: --version

$ scala-cli -v
No inputs provided (expected files with .scala or .sc extensions, and / or directories).

$ scala-cli version
version: not found

$ scala-cli about
Scala CLI version 0.0.0+274-gb0d66b5-SNAPSHOT (latest-274-b0d66b)

$ curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   667  100   667    0     0   2744      0 --:--:-- --:--:-- --:--:--  2744
100 36.7M  100 36.7M    0     0  23.2M      0  0:00:01  0:00:01 --:--:-- 29.2M
Scala-cli 0.0.9 is already installed and up-to-date.
```

**Comment by lwronski** [comment]
Hi @bjornregnell 
Thanks for reporting, it seems that you manually added `scala-cli (0.0.0+274-gb0d66b5-SNAPSHOT)` to the `PATH` some time ago. And I hypothesize that you have` scala-cli` twice on the PATH.

`curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh` adds a new entry to the `.profile` file like that: `export PATH="$PATH:/root/.cache/scalacli/local-repo/bin/scala-cli`. 

Installation scripts add `scala-cli` to the end of the `PATH`, so if there are two scala-cli on the PATH, the first will be run.
Please check if you have `scala-cli` twice on the PATH, if you have it remove the first appearance.

This can be confusing so I think that `scala-cli `should report if someone has multiple scala-cli on PATH.

**Comment by bjornregnell** [comment]
AHA! Many thanks @lwronski ! Yes I had both scala-cli installed using apt and script and things in .profile. It worked after cleaning up .profile and purging my apt package that installed to /usr/local/bin, but it would be really nice if scala-cli could give me some hints of what I have on my machine, and what I need to do to update/clean up the installation, as it is easy to forget if installed twice etc.  Also a hint on **`source ~/.profile` or logout/login" would be good after running the install script so that beginners know that it might not work directly.

When putting this in the hands of 200 students you'll get all sorts of combinations of double installation :)

**Comment by lwronski** [comment]
This hint is printed only when the `scala-cli` added new entry to  `~/.profile` file such as:

`export PATH="$PATH:/root/.cache/scalacli/local-repo/bin/scala-cli`

and then you can see log:

```
Successfully installed scala-cli 0.0.9
Profile file(s) updated.
To run scala-cli, log out and log back in, or run 'source ~/.profile'
```

**Comment by bjornregnell** [comment]
I think we can take inspiration from sdkman here, which includes the following functionality:
* report on available updates; scala-cli could report both on updates available for itself and for the scala tools it installs
It has a kind of "bulletin" that gives news on recent versions available.

Also I think it would be good if scala-cli:
* reports on duplicates on path
* allow scala-cli --version
* reports if I have the latest version when running the version or about command, something like (latest version) or (there is a later version: <how to install it>)
* reports if there are multiple installs and duplicates on path etc
* give help if user tries to install in several different ways; e.g. if you do package install before curl install -- ask if you want to do this and ask to remove the other or something sane
