### ISSUE TITLE
Scala CLI should be able to report actionable diagnostics

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#558]
Scala CLI can report warnings / errors over CLI and BSP (so it is displayed in Metals). The idea is that some of those diagnostics to contain actionable part to fix the problem. For example, warnings about the deprecated syntax of using directives can provide a way to just change the syntax with one command or one click. 

The IDE/BSP part would most likely needs changes in BSP protocol so this issue should over only command line part. Based on the results of this task we should plan and discuss a solution that will work also with Metals.

**Comment by lwronski** [comment]
The mechanism was implemented in `scala-cli` and Metals. If users want to enable actionable diagnostics, they must run `scala-cli config actions true`. A  actionable diagnostic is generated that provides suggestions that can be applied to your code, as has already been done in Metals.

https://user-images.githubusercontent.com/46607934/203530949-1e7a19ff-ac09-417f-ad7f-396f344e725e.mov

Future work is tracked [here](https://github.com/VirtusLab/scala-cli/issues/1542).
