### ISSUE TITLE
Investigate proper integration with Intellij

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#560]
Scala CLI works quite well with Metals, however, integration with Intellij is not perfect. 

We should investigate what works and what does not, update documentation and make a plan how to improve the situation - ideally working with the Intellij Scala Plugin team.

**Comment by Gedochao** [comment]
I consider the investigation done for now, so I'm closing this ticket.
The individual problems should be tracked in their respective tickets:
 - https://github.com/VirtusLab/scala-cli/issues/946
 - https://github.com/VirtusLab/scala-cli/issues/1060
 - https://github.com/VirtusLab/scala-cli/issues/1153
