### ISSUE TITLE
`using scala 3-nightly`

### ISSUE THREAD

**Issue by KacperFKorban** [VirtusLab/scala-cli#571]
Scala-CLI allows defining the following using directive:

```scala
using scala "3"
```

which sets the Scala version to the latest stable version.

It would be a great improvement to be able to define a using directive like:

```scala
using scala 3-nightly
```

which would set the Scala version to the latest nightly.

**Comment by bjornregnell** [comment]
This woiuld be nice! It would also be cool to be able to do this via the `-S` and similar options like:
```
scala-cli . -S 3.nightly
```
or similar.

**Comment by SethTisue** [comment]
It would cool if Scala 2 support were included as well.

scala-runners has this; `scala -2.13.head` runs the latest nightly, and `scala -2.13.next` runs the most recent community-build-validated nightly.

**Comment by ghost** [comment]
Should the option be 3-nightly or 3.nightly?

**Comment by bjornregnell** [comment]
I vote for:
`//> using scala "3.nightly"`  

It would also be useful to enable an explicit specific nightly version if you want to be sure the thing doesn't change, like in:
`//> using scala "3.1.3-RC1-bin-20220126-8ae2962-NIGHTLY"`
(but that's perhaps already possible?)

**Comment by SethTisue** [comment]
> it's perhaps already possible

Scala 3 nightlies are published to Maven Central, so I would expect that to just work without any extra ceremony.

Scala 2 nightlies require a custom resolver, so something like `//> using scala "2.13.7-bin-072e68e"` works but you must pass `--repository https://scala-ci.typesafe.com/artifactory/scala-integration/` on the command line, as per #107.

**Comment by bjornregnell** [comment]
> works but you must pass --repository ...

It would be nice if Scala 2 was as simple as Scala 3 and I guess it would be possible to detect that a nightly version is asked for and behind the scenes automatically provide the ceremony? In that way `scala-cli` would provide a more regular UX.

**Comment by ghost** [comment]
#643

**Comment by SethTisue** [comment]
Thank you @zmerr!!

**Comment by ghost** [comment]
@SethTisue You’re very welcome! If only you knew what I put @lwronski @alexarchambault and @romanowski through, with endless hickups, to get it finally working😅
