### ISSUE TITLE
scala version discovery: allow scala-cli to help me discover available scala versions + more helpful err message when wrong verison

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#574]
Currently:
```
$ scala-cli . -S 3.4.5
Error downloading org.scala-lang:scala3-compiler_3:3.4.5
  not found: /home/bjornr/.ivy2/local/org.scala-lang/scala3-compiler_3/3.4.5/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.4.5/scala3-compiler_3-3.4.5.pom
  not found: /home/bjornr/.cache/scalacli/local-repo/v0.0.9/org.scala-lang/scala3-compiler_3/3.4.5/ivys/ivy.xml

```
But it would be cool if scala-cli could help me with what versions are available, e.g. when giving wrong or empty arg to the `-S` option. That way the above message could be complemented with info that is easy for beginners to grok.

It seems like coursier can do this so delegate to a sort of the output of:
```
cs complete org.scala-lang:scala3-compiler_3:
```

**Comment by bjornregnell** [comment]
related to https://github.com/VirtusLab/scala-cli/issues/571

**Comment by bjornregnell** [comment]
This is an enhancement proposal.

**Comment by romanowski** [comment]
@bjornregnell thank you for your improvement ideas, I agree it would be really nice if scala-cli could provide such detailed error messages. After the `0.1` release,  we are going to work on more actionable feedback so this may be a good occasion to take a look at this issue.

**Comment by zmerr** [comment]
This is related to issue #543 and issue #698 and PR #663
