### ISSUE TITLE
Better UX from multiple main methods

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#583]
I have a project I'm working on that purposefully has multiple main methods. It's used for teaching, so it's useful to have a bunch of examples all with main methods that are super easy for the user to choose between. However, right now if there are multiple main classes you'll see the following:

```
❯ scli run .
Found several main classes: One, Two, Three
```

This then forces the user to look up how to pass in a main method and then re-do the command. I propose that this be improved to a more interactive experience. Imagine the process starting the same way, but instead of it just ending with a message you're instead met with:

```
❯ scli run .
Found several main classes. Which would you like to run?
[1] One
[2] Two
[3] Three
```
Then after choosing the option you want, it runs. This would allow for much better UX for project that have multiple main methods.

**Comment by lwronski** [comment]
Hi @ckipp01, Thanks for reporting
from the next version of Scala CLI `0.1.6` it will be available interactive mode.

To use it user has to pass `-i` or `--interactive` to enable interactive mode.
```
scala-cli --cli-version nightly -i  Hello.scala
Compiling project (Scala 3.1.2, JVM)
Compiled project (Scala 3.1.2, JVM)
Found several main classes. Which would you like to run?
[0] hello.Two
[1] hello.Three
[2] hello.One
2
Hello from One object
```

in the above snippet, I used `--cli-version nightly` to use the latest nightly build of Scala CLI. You can find more detail [here](https://scala-cli.virtuslab.org/docs/commands/basics/#scala-cli-version).
