### ISSUE TITLE
`format --check` just formats your code

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#588]
**Version(s)**

0.10.0

**Describe the bug**

When trying to check your sources for formatting with `scala-cli --check` it just formats your code.

**To Reproduce**

_If you have some code like this_
```scala
//> using scala "3.1.1"

@main def Main(args: String*): Unit =
            throw new Exception
```

_A format file like this_
```
version = "3.3.3"
runner.dialect = scala3
```

And you run `scala-cli --check` it just formats your code.

**Expected behaviour**
I'd expect this to behave **exactly** like it does with scalafmt. For example on the same code when I try scalafmt cli I get:

```
❯ scalafmt --check
--- a/Users/ckipp/Documents/scala-workspace/scala-cli-test/Main.scala
+++ b/Users/ckipp/Documents/scala-workspace/scala-cli-test/Main.scala
@@ -3,2 +3,2 @@
 @main def Main(args: String*): Unit =
-            throw new Exception
+  throw new Exception
error: --test failed
```

The output of `scala-cli format --check` should be the same.

**Comment by romanowski** [comment]
`--check` is  broken for Scala 2 and default scalafmt config - basically it is not implemented properly on our side.

**Comment by ckipp01** [comment]
> `--check` is broken for Scala 2 and default scalafmt config - basically it is not implemented properly on our side.

Ahh sorry I didn't realize this was a duplicate!

**Comment by romanowski** [comment]
Do not worry, your report is much more detailed ;)
