### ISSUE TITLE
Don't compile test target when you package

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#589]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use Scala 3 and produce a native image via Scala Native. While my code can do that, the testing framework I'm using isn't published for Scala Native. When trying to publish my image it won't publish because of a test dependency.

**Describe the solution you'd like**
I'm not sure this behavior is expected, and I'm not 100% sure if this even needs to be, but I think it'd be nice to not have the package command rely on the test compilation. This would unlock more code bases to be able to produce a native image for example like I'm trying to.

**Describe alternatives you've considered**
Move my code into different directories and try to only point the package command towards them.

**Comment by alexarchambault** [comment]
That looks like an oversight after some recent refactoring, we should fix that.
