### ISSUE TITLE
Host `scala-setup.sh` for multiple versions

### ISSUE THREAD

**Issue by ybasket** [VirtusLab/scala-cli#597]
**Is your feature request related to a problem? Please describe.**
We're using `scala-cli` happily in CI (GitHub Actions), installing it by executing `https://virtuslab.github.io/scala-cli-packages/scala-setup.sh` at the beginning of the workflow. As there's no way of specifying the version, we'll always end up with the latest version of `scala-cli`, breaking builds in case of incompatible changes like the `using` directive ones in `0.1.0`.

**Describe the solution you'd like**
It would be cool if there were install scripts hosted by version so that one could reliably install the same version. Example:
`https://virtuslab.github.io/scala-cli-packages/0.1.0/scala-setup.sh`. The current URL could still point to the latest as many users (esp non-CI) would prefer that.

**Describe alternatives you've considered**
For CI, one could bake in `scala-cli` into a docker container and leverage that, but this is not always desirable. Also, the suggested solution would allow to create a GitHub action that installs a specific version and published that on the marketplace, helping the adoption of `scala-cli`.

**Comment by alexarchambault** [comment]
@ybasket You can already specify the specific version you'd like to install with
```bash
$ ./scala-setup.sh --version 0.0.9
```

Wouldn't that work for you? Plus looking at the commit hash, you could also somehow "pin" the script when you download it (using the commit hash rather than `master`).

**Comment by ybasket** [comment]
> @ybasket You can already specify the specific version you'd like to install with
> 
> ```shell
> $ ./scala-setup.sh --version 0.0.9
> ```
> 
> Wouldn't that work for you? Plus looking at the commit hash, you could also somehow "pin" the script when you download it (using the commit hash rather than `master`).

Yes, that works indeed, I missed that option. Thank you!
