### ISSUE TITLE
Setting -source:future causes warning

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#607]
#525 was fixed in 0.1.0, but this is something of a special case of it where the flag isn't an exact duplicate.

When I add this to my script:

```
//> using option "-source:future"
```

I get:

```
Compiling project (Scala 3.1.1, JVM)
Warning: Flag -source set repeatedly
```

I guess scala-cli is passing `-source` itself, but I don't know what it's passing or why.

**Comment by lwronski** [comment]
Hi @SethTisue 
Thanks for reporting, unfortunately I can't reproduce bug. 

```
$ cat hello.sc 
//> using option "-source:future"

println("Hello")
$ scala-cli about
Scala CLI version 0.1.0 (v0.1.0)
$ scala-cli hello.sc 
Compiling project (Scala 3.1.1, JVM)
Compiled project (Scala 3.1.1, JVM)
Hello
```

Did you run only one scala file? What arguments did you pass to `scala-cli`?

**Comment by SethTisue** [comment]
I'm not able to reproduce it on 0.1.1 🤷
