### ISSUE TITLE
Error in the test command's doc page

### ISSUE THREAD

**Issue by artemkorsakov** [VirtusLab/scala-cli#621]
**Error in the test command's doc page**

On the page https://scala-cli.virtuslab.org/docs/commands/test we have the following recomendation:

> A source file is treated as test source if: the file name ends with .test.scala

We also have example file: `a.test.scala`.

But later we see the following:

> As a rule of thumb, we recommend naming all of your test files with the `.tests.scala` suffix.

What is the right option? How can we name our test files? With the `.test.scala` suffix or with the `.tests.scala` suffix?

**Comment by romanowski** [comment]
Thank you for reporting, `a.test.scala` is a proper name for a test file, I will fix the doc.

**Comment by lwronski** [comment]
Closed [#623](https://github.com/VirtusLab/scala-cli/pull/623).
