### ISSUE TITLE
using_directives stop parsing too early

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#637]
Currently happening with `0.1.0`

Passed a file such as
```scala scala-cli
//> using scala "2.13.6" "2.12.15"
//> using lib "com.lihaoyi::pprint:0.7.1"

object Foo {
  def main(args: Array[String]): Unit =
    pprint.log(args.toSeq)
}
```

it seems directive parsing silently stops right after `"2.13.6"`, and silently ignores the `using lib` directive:
```text
$ scala-cli Foo.scala
Compiling project (Scala 2.13.6, JVM)
[error] ./Foo.scala:6:5: not found: value pprint
[error]     pprint.log(args.toSeq)
[error]     ^^^^^^
Error compiling project (Scala 2.13.6, JVM)
Compilation failed
```

**Comment by alexarchambault** [comment]
The missing comma right after `"2.13.6"` seems to be an issue, but Scala CLI should nonetheless report an error about the malformed using directive.

**Comment by romanowski** [comment]
#561 is a wider issue that covers such case but let's keep both since this one has a nice reproduction.

**Comment by lwronski** [comment]
In ScalaCLI `0.1.4` it throws following error: 
```
lwronski@VL-D-0317 scala-demo % scala-cli Hello.scala
[error] ./Hello.scala:1:26: Expected new line after the using directive, in the line; but found string literal: 2.12.15
[error] //> using scala "2.13.6" "2.12.15"
[error] 
```
For me it is good enough, so IMO we can close this issue.  cc @romanowski
