### ISSUE TITLE
Scala-cli's bloop instance isn't working properly and interferes with original one.

### ISSUE THREAD

**Issue by kpodsiad** [VirtusLab/scala-cli#640]
**Version(s)**

Scala CLI version `0.1.0` (v0.1.0)

**Describe the bug**

As a Metals user, I have Bloop instance running in the background almost all of the time. Yesterday was the first time I've tried to use scala-cli `0.1.0` (which uses its own bloop instance) and I was surprised that Metals cannot auto-connect to the scala-cli as a build server. The next thing I discovered is that scala-cli doesn't work because it can't start its own bloop instance, namely every command such as `run` or `compile` doesn't work and yields:
```shell
Bloop daemon status: not running
Starting Bloop 1.4.19 at /Users/kpodsiadlo/Library/Caches/ScalaCli/bloop/daemon using JVM /Users/kpodsiadlo/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home/bin/java
Error: java.lang.Exception: Server didn't start
For more details, please see '/Users/kpodsiadlo/software/scala-cli-sample/.scala-build/stacktraces/1644385522-808445731027933856.log'
``` 
The content of the `1644385522-808445731027933856.log` is:
```scala
java.lang.Exception: Server didn't start
  scala.build.blooprifle.internal.Operations$.$anonfun$startServer$2(Operations.scala:153)
  scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:12)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
  com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

**_I managed to successfully run scala-cli only after I manually killed the "normal" bloop instance._**

However, after that I encountered another problem - Metals won't be able to start the original Bloop for their own purposes. So in order to get Bloop started I had to manually kill scala-cli's Bloop instance. 

Recently I've been observing many Metals users having trouble with connecting to the Bloop in Metals and I'm afraid that it's not a coincidence that it started after scala-cli `0.1.0` release. I hope not, but I experienced the same issues as users on my own, something isn't right :/

**To Reproduce**
1. Start with Bloop instance running in the background (may be one started by Metals)
2. Check if scala-cli is working
2a. Try to run scala-cli command such as `run` or `compile`
2b. Alternatively, open scala-cli project and wait for Metal aren't able to connect to the build server
3. Kill Bloop manually
4. Scala-cli starts working

**Expected behaviour**
scala-cli's bloop instance doesn't interfere with original one

**Comment by kpodsiad** [comment]
Actually, I might have found what's causing the issue. I have custom settings defined in bloop.json and one of them enables debugging at a specific port and apparently scala-cli's bloop is reading those settings.
```shell
(base) ➜  ~ cat ~/.bloop/bloop.json
{
  "javaOptions": ["-Xmx8G", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5030,quiet=y"]
}
```

But this raises more questions:
- One of known bloop limitation, or a feature is `There can only be one bloop server instance running per machine`. I understand the reasons why scala-cli has its own bloop instance, but reading common settings may lead to bugs like in my case. 
- Should scala-cli honor the `~/.bloop/bloop.json`? Many Bloop users tweak those settings e.g. increasing `Xms` and `Xmx` setting to boost Bloop in big repositories. Scala-cli on the contrary is designed to work with small projects, should it apply those settings?

**Comment by alexarchambault** [comment]
We should probably stop reading `~/.bloop/bloop.json` in Scala CLI, yeah.
