### ISSUE TITLE
Scala CLI does not compute root project properly

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#646]
**Version(s)**

`0.1.0`

**Describe the bug**

With the following directory structure:

```
.
├── a
│   └── A.scala
└── b
    └── B.scala
```

When runnning `scala-cli a/A.scala b/B.scala` the `.scala-build` and `.bap` directories are generated in `a` instead of `cwd` (current directory).

I also think that Scala CLI should expose a command line option to manually provide a project root, mainly to generate `.bsp` directory in the right place.

**Comment by lwronski** [comment]
If you want to change manually bsp directory, you can pass following parameter:
`$ scala-cli setup-ide . --bsp-directory .bsp`
