### ISSUE TITLE
Generate BSP discovery file

### ISSUE THREAD

**Issue by adpi2** [VirtusLab/scala-cli#65]
The [BSP discovery file](https://build-server-protocol.github.io/docs/server-discovery.html) `.bsp/scala-cli.json` would enable any BSP server to connect to scala-cli. More concretely it would enable IntelliJ to import a scala-cli project.

It should contain something like:
```json
{"name":"scala-cli","version":"0.0.0+274-gb0d66b5-SNAPSHOT","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["scala-cli","bsp"]}
```

This file could be generated systematically or by a dedicated command: `scala-cli bsp-config`.

**Comment by alexarchambault** [comment]
@adpi2 The `setup-ide` command should do that.
