### ISSUE TITLE
Invalid `canWrite` check

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#656]
https://github.com/VirtusLab/scala-cli/blob/6efbefb1d864c0ee36156f9ac8489d0e14ee54c4/modules/build/src/main/scala/scala/build/Inputs.scala#L129

`scala-cli` checks if the directory is writable, but it's doing it incorrectly. If file permissions are `000`, then even the owner can't write to it. On the other hand, if it is `777` then anyone (so non-owners) are allowed to write to it.

**Comment by lwronski** [comment]
Hi @tpasternak, Thanks for reporting. I'am able to reproduce this in docker 

```
root@ff0006f18c02:/# chmod 777 home/
root@ff0006f18c02:/# useradd -m scalacli
root@ff0006f18c02:/# su scalacli
$ pwd
/home
$ ./scala-cli setup-ide . -v -v -v 
Wrote /home/scalacli/.cache/scalacli/virtual-projects/fb/project-69d7a7ad/.bsp/scala-cli.json
```

If you want to change manually bsp directory, you can pass following parameter:
`$ scala-cli setup-ide . --bsp-directory .bsp`

**Comment by alexarchambault** [comment]
We don't only check that the directory is writable, we also want to ensure that it's owned by the current user. So that a different user who also has write rights wouldn't clash with the current one (only one of them, the owner of the directory, is going to write files in the current directory).

**Comment by alexarchambault** [comment]
But maybe we just shouldn't write `.bsp` directories if they land under `/home/scalacli/.cache/scalacli`.

**Comment by tpasternak** [comment]
Ok, I understand, how about users in a group owning the directory. What is more, metals is (I think) not aware of .bsp folders in .cache/scalacli. So maybe it would be better just to explicitely fail in case scala-cli setup-ide is called by a non-owner
