### ISSUE TITLE
Add `buildTarget/javacOptions` endpoint

### ISSUE THREAD

**Issue by adpi2** [VirtusLab/scala-cli#66]
This is needed by IntelliJ because scala-cli pretends it supports the java extension:
![image](https://user-images.githubusercontent.com/13123162/126782718-e17c5b71-70a3-4ba0-87da-65405b3fffbd.png)

The `buildTarget/javacOptions` specification is defined [here](https://build-server-protocol.github.io/docs/extensions/java.html).

**Comment by adpi2** [comment]
This issue is blocked until https://github.com/scalacenter/bloop/pull/1397 is released

**Comment by alexarchambault** [comment]
> This is issue is blocked until scalacenter/bloop#1397 is released

Using a nightly should be fine I think, like `1.4.8-83-27d9d739`.
