### ISSUE TITLE
Poor formatting in scalacli on Windows command prompt

### ISSUE THREAD

**Issue by mhammons-ledger** [VirtusLab/scala-cli#661]
**Version(s)**

0.1.1

**Describe the bug**

The output of scalacli is poor on windows command prompt. This is not a fact of life of using the windows command prompt in windows 10, as the output is perfect when you enter repl mode. It's just the help dialogs and other such things that scalacli handles directly that are poorly formatted. 

![image](https://user-images.githubusercontent.com/95632425/154450580-74e0f2fb-d7a6-47ae-9072-8287cd018d71.png)

![image](https://user-images.githubusercontent.com/95632425/154450505-764c8043-4e9a-4a03-99fc-d295be0d7dce.png)

**To Reproduce**

Install and run scalacli on windows 10, using the windows terminal.

**Expected behaviour**
I'm guessing by the output that scalacli is using ascii that windows10 command prompt doesn't support. I'm guessing jline does detection of this stuff and adapts its output automatically, which is why the repl has proper formatting and color output, but scalacli help prompt doesn't.

**Comment by alexarchambault** [comment]
@mhammons-ledger Do you know how long is your `PATH` environment variable? (`echo %PATH%`) https://github.com/VirtusLab/scala-cli/pull/675 should fix the activation of ANSI output for too long PATHs.
