### ISSUE TITLE
Regression: can't use Scala 3.1.2-RC1

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#687]
this was working before I upgraded to 0.1.2

```
% scala-cli repl -S 3.1.2-RC1
[error]  Cannot find matching Scala version for '3.1.2-RC1'
You can only choose one of the 3.x, 2.13.x, and 2.12.x. versions.
The latest supported stable versions are 3.1.1, 2.13.8, 2.12.15.
In addition, you can request the latest Scala 2 and Scala 3 nightly versions by passing 2.nightly, and 3.nightly arguments respectively.
Specific Scala 2 or Scala 3 nightly versions are also accepted.
```

the same happens if I try to use 2.13.0-RC1

**Comment by ghost** [comment]
My fault! Now it is wrongly assuming that any non-nightly version should be a full stable one!

**Comment by SethTisue** [comment]
one weird thing is that `-S 2.13.0-M1` works. not regressing on that could be part of a test, I guess

**Comment by ghost** [comment]
It’s because the way we currently detect if something is stable is to just check if it contains `NIGHTLY` or `-RC`. So `-S 2.13.0-M1` passes the filter. So thanks for reporting this special case. If there are any other special cases that you think should be covered, it would be nice if you can report under this thread!

**Comment by SethTisue** [comment]
I guess you already know what Scala 2 nightly version numbers don't have either `NIGHTLY` or `-RC` — they have `-bin-` and a SHA. Can't think of anything else. (We used to do `-pre-` nightlies when bincompat wasn't frozen yet, but Scala 2 bincompat is now permanently frozen, so while it's not terribly important to support those now quite old nightlies, for completeness you might add `-pre` alongside `-bin`.)

**Comment by ghost** [comment]
Thank you very much! Please feel free to add any other special case you encounter, until the next release🙂!

**Comment by SethTisue** [comment]
related, this doesn't work: `scala-cli repl -S 2.13.9-bin-de73fdb` (and same for a 2.12.x nightly, e.g. `scala-cli repl -S 2.12.16-bin-5d9240a`) unless I add `--repository https://scala-ci.typesafe.com/artifactory/scala-integration`. Not sure, design-wise, if I should be expecting that the resolver would be automatically added for me, based on detection of a non-stable version number?

**Comment by romanowski** [comment]
I think @SethTisue  has a point, we can add a resolver for any non-stable version of Scala.

**Comment by ghost** [comment]
@romanowski I wonder what might be causing it….

**Comment by ghost** [comment]
Are all scala versions that have alphabet letters in their names non-stable? @SethTisue

**Comment by SethTisue** [comment]
Yes.

**Comment by zmerr** [comment]
Just to make sure, I am implementing it correctly, is `3.1.2-RC1-bin-20220125-a83a0a7-NIGHTLY` the full version for `3.1.2-RC1`?

**Comment by ghost** [comment]
> Probably, scala-cli did not support versions such as 2.13.0-RC1 in the past.
> But maybe we could support them by disabling the “runner” for them.
> There should be a command-line option to disable the runner

From @alexarchambault

**Comment by ghost** [comment]
@SethTisue is support for `-S 2.13.0-M1` currently needed?

**Comment by SethTisue** [comment]
> is support for -S 2.13.0-M1 currently needed?

It would be useful. I would use it.

I admit there's not a huge audience for running old milestones and RCs like that. But anyone doing bug triage or investigating the history of a bug might like to run an old milestone or RC to help find out when some behavior changed or regressed — that kind of thing.

**Comment by ghost** [comment]
@SethTisue Thanks for letting us know! We are now working to solve the issue for you!

**Comment by SethTisue** [comment]
I don't understand Alex's remarks — what does it mean to "disable the runner"?

**Comment by ghost** [comment]
passing `--runner=false` as a command option!
But it won’t work on 0.1.2 because this release is failing it at the version resolution stage!

**Comment by SethTisue** [comment]
But what does `--runner=false` do? There's no documentation for `--runner` in `website/docs/reference/cli-options.md`

**Comment by ghost** [comment]
@SethTisue it’s currently a hidden option! We would try to add better documentation!
