### ISSUE TITLE
developer doc question

### ISSUE THREAD

**Issue by mtk** [VirtusLab/scala-cli#708]
you wrote:

>Generate Metals configuration files
>./mill mill.contrib.Bloop/install
>Then run the command "Metals: Connect to build server".
>
>(Recommended over the Metals import project functionality.)

how does one do this using emacs + lsp + metals-emacs?

**Comment by tgodzik** [comment]
The question seem to have gone unnoticed, sorry about it! This should work the same with metals-emacs. The command should be accessible from emacs. We should also suggest import automatically.
