### ISSUE TITLE
REPL arguments not being recognized

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#738]
**Version(s)**

0.1.2
**Describe the bug**

I'd like to pass flags into the REPL, however this seems to have no effect.

**To Reproduce**

For example,  try `scala-cli repl --scala 3.nightly -Xshow-phases`. This starts up the REPL when it should print out the phases. I thought maybe I could do `scala-cli repl --scala 3.nightly -- -Xshow-phases`, but this also seems to behave the same.

**Expected behaviour**
I'd expect this to print out the phases.

**Comment by SethTisue** [comment]
This seems to have regressed:

```
% scala-cli about
Scala CLI version 0.1.3
% scala-cli repl --scala 3.nightly -Xshow-phases
Welcome to Scala 3.2.0-RC1-bin-20220308-29073f1-NIGHTLY-git-29073f1 (17.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                    
scala> 
```

I also tried it with `-Yrepl-class-based:false`:

```
% scala-cli repl --scala 2.nightly -Yrepl-class-based:false
Welcome to Scala 2.13.9-bin-9312709 (OpenJDK 64-Bit Server VM, Java 17.0.2).
Type in expressions for evaluation. Or try :help.

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> settings.Yreplclassbased
val res0: scala.tools.nsc.Settings#BooleanSetting = -Yrepl-class-based = true
```
