### ISSUE TITLE
Make jvm used to run in docker  selectable when package  --docker option being used 

### ISSUE THREAD

**Issue by nmehitabel** [VirtusLab/scala-cli#746]
**Is your feature request related to a problem? Please describe.**
I want to be able to specify the java version used for a docker package when it is run. I have a small utility that calls google ZetaSql formatter which won't run under openjdk-17 so I would like to be able to specify the java version runtime when building the docker package.

**Describe the solution you'd like**
A `--docker-jvm` flag or similar that operates to specify the java version that will be used when the container runs.
 
**Describe alternatives you've considered**
Either I could go back to a version of scala-cli that defaults to java 11 or use a different build tool.

**Comment by alexarchambault** [comment]
The `--docker-from` option should allow to pick a base image, like `openjdk:11`, or anything else that puts `java` in the `PATH`. This ought to work:
```text
$ scala-cli package --docker --docker-from openjdk:11 …
```

**Comment by nmehitabel** [comment]
Many thanks. That was it.
