### ISSUE TITLE
Support for printing help from scala compiler

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#753]
**Is your feature request related to a problem? Please describe.**

Scala CLI should print help message from scala compiler like `scalac -help`. It can be added new flag to print help from compiler.

**Comment by SethTisue** [comment]
`scalac -Xshow-phases` is also like this:

```
% /usr/local/scala/scala-2.13.8/bin/scala -Xshow-phases
    phase name  id  description
    ----------  --  -----------
        parser   1  parse source into ASTs, perform simple desugaring
         namer   2  resolve names, attach symbols to named trees
...
```
but:

```
% scala-cli compile -S 2.13.8 -Xshow-phases
No inputs provided (expected files with .scala or .sc extensions, and / or directories).
```

**Comment by SethTisue** [comment]
similarly, `scalac -X` and `scalac -Y` and `scalac -V` and `scalac -W` print help for just those subcategories of flags
