### ISSUE TITLE
Bloop doesn't start: IOException java not such file or directory

### ISSUE THREAD

**Issue by benkio** [VirtusLab/scala-cli#757]
**Version(s)** 0.1.2

**Describe the bug**

When running a simple example store [here](https://gist.github.com/benkio/baa4fe1d50751cd602c4175f1bb39f4d) I encounter this error:

```
[benkio@nixos:~/temp]$ scala-cli compile TableReservationSystem.sc
Bloop daemon status: not running
Starting Bloop 1.4.19 at /home/benkio/.local/share/scalacli/bloop/daemon using JVM /home/benkio/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35/bin/java
Error: java.io.IOException: Cannot run program "/home/benkio/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35/bin/java" (in directory "/home/benkio/.local/share/scalacli/bloop"): error=2, No such file or directory
For more details, please see '/home/benkio/temp/.scala-build/stacktraces/1646573019-12945047684502775367.log'

[benkio@nixos:~/temp]$ scala-cli --version
0.1.2

[benkio@nixos:~/temp]$ ls /home/benkio/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35/bin/
jar*	    javadoc*   jdb*	   jhsdb*   jmap*      jrunscript*  jstatd*
jarsigner*  javap*     jdeprscan*  jimage*  jmod*      jshell*	    keytool*
java*	    jcmd*      jdeps*	   jinfo*   jpackage*  jstack*	    rmiregistry*
javac*	    jconsole*  jfr*	   jlink*   jps*       jstat*	    serialver*
```

**To Reproduce**

Just donload the gist at https://gist.github.com/benkio/baa4fe1d50751cd602c4175f1bb39f4d and run
`scala-cli compile file.sc`

**Expected behaviour**
It should run fine as the scastie version here: https://scastie.scala-lang.org/urJPRXNTQGuwhcLCFAtJMQ

**Comment by nmehitabel** [comment]
If you are running on Nixos which it looks like then it's the running of unpatched binaries issue. I have the same problem on my set up (it runs fine on another machine that is linux with nix).

**Comment by benkio** [comment]
Yes, I'm on NixOs unstable.
Then I just have to wait until it's solved by upgrading to a new version/binaries in the nixos channels?
(BTW it could be helpful in case someone else encounter the same error these days)

**Comment by nmehitabel** [comment]
Apologies I should have been more clear. It is a problem, of sorts, in running a non-nixos prebuilt binary that is downloaded (which is what the scala-cli program appears to do to run the operation described by the arguments)  and then trying to run that via nixos which won't accept it - see [nixos wiki](https://nixos.wiki/wiki/Packaging/Binaries). There seem to be a few ways of trying to accommodate this but I have not attempted any of these in this case yet.

**Comment by benkio** [comment]
I see, but I expected this: 
https://github.com/kubukoz/scala-cli.nix 
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/build-managers/scala-cli/default.nix#L61
to include such tricks :smile: 
Shall I migrate/link this issue there?

**Comment by nmehitabel** [comment]
I have found a solution. For compilation you need to use the `--bloop-jvm` option to point to your system jvm which needs to be 17 and it seems that after the first time of doing that things will work ok. See [project](https://github.com/nmehitabel/zetafmt) for flake based simple example.

**Comment by benkio** [comment]
I'll try ASAP

**Comment by benkio** [comment]
Tried right now, specifying the jvm id as bloop jvm option solves the problem!!!
I close the issue then.
Here the shell output for reference  

```
[benkio@nixos:~/temp]$ scala-cli compile TableReservation.sc 
Bloop daemon status: not running
Starting Bloop 1.4.19 at /home/benkio/.local/share/scalacli/bloop/daemon using JVM /home/benkio/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35/bin/java
Error: java.io.IOException: Cannot run program "/home/benkio/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35/bin/java" (in directory "/home/benkio/.local/share/scalacli/bloop"): error=2, No such file or directory
For more details, please see '/home/benkio/temp/.scala-build/stacktraces/1648383902-9060340931562694713.log'

[benkio@nixos:~/temp]$ scala-cli --version && which java && java --version
0.1.2
/home/benkio/.nix-profile/bin/java
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-nixos)
OpenJDK 64-Bit Server VM (build 17.0.1+12-nixos, mixed mode, sharing)

[benkio@nixos:~/temp]$ scala-cli compile TableReservation.sc --bloop-jvm='system|17'
Compiling project (Scala 3.1.1, JVM)
Compiled project (Scala 3.1.1, JVM)

[benkio@nixos:~/temp]$ 
```

PS: when you run `scala-cli compile --help` the option `--bloop-jvm` doesn't appear. Adding it is worth considering
