### ISSUE TITLE
Bloated output on fat jars

### ISSUE THREAD

**Issue by JD557** [VirtusLab/scala-cli#778]
**Version(s)**

0.1.2

**Describe the bug**

Fat jars created with `scala-cli package --assembly` are much larger than the ones generated with `sbt assembly`.

This appears to be because scala-cli is packaging scalac, some protobuf code, some scala-js code and some code from scala-cli.

Comparing a simple Hello World:

```scala
object Hello extends App {
  println("Hello World")
}
```

The jar generated by `sbt assembly` takes **~6.9MB**, with the following directories when extracted:
```
25M	./scala
8.0K	./META-INF
26M
```

Meanwhile, the jar generated by `scala-cli package --assembly` takes **~26MB**, with the following directories when extracted:
```
29M	./scala
4.3M	./org
128K	./google
38M	./dotty
540K	./xsbti
9.4M	./com
244K	./META-INF
81M	.
```

**To Reproduce**

Package the provided hello world with `scala-cli package --assembly` and `sbt assembly` (from [sbt-assembly](https://github.com/sbt/sbt-assembly)) and compare the results.

**Expected Result**

I would expect the results to be closer to each other.

**Comment by lwronski** [comment]
From ScalaCLI `0.1.5` was removed pretty-stack traces from classpath, so transitive dependency to the compiler in 3.0 (through tasty-inspector) isn't available.

Therefore the size of the assembly package was reduced to **~6.9MB**:

```
lwronski$ cat Hello.scala 
object Hello extends App {
  println("Hello World")
}
lwronski$ scala-cli package --assembly Hello.scala
lwronski$ ls -lh Hello.jar 
-rwxr-xr-x  1 lwronski  wheel   6.9M May  4 17:23 Hello.jar
```
