### ISSUE TITLE
jsSourceMaps are not emitted.

### ISSUE THREAD

**Issue by markehammons** [VirtusLab/scala-cli#779]
**Version(s)**

0.1.2

**Describe the bug**

When told to emit js source maps, scala cli does not

**To Reproduce**

```scala
//> using jsEmitSourceMaps "true"

import org.scalajs.dom
import dom.html


@main def main() = 
  val container = dom.document.querySelector("#container")
  val content = dom.document.createElement("div")
  content.classList.add("content")
  content.textContent = "This is the glorious text-content!"

  container.appendChild(content)
```

`scala-cli package scalajs-file.scala --js --js-emit-source-maps --dependency org.scala-js::scalajs-dom::2.1.0`

No js source maps emitted.

**Expected behaviour**
Source maps should be produced alongside the js file.

**Comment by lwronski** [comment]
@markehammons Thanks for reporting,  There was a problem that scala-cli didn't copy `*.map` files to destination directory.
#784 should fix it

**Comment by markehammons** [comment]
Thanks, really glad to hear that it will be fixed so soon.
