### ISSUE TITLE
"Server didn't start" error on attempt to use scala-cli

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/scala-cli#846]
**Version(s)**

0.1.2

**Describe the bug**

I setup a scala-cli project and I was working with it without any issues. Then, after couple days (I wasn't touching anything related to programming) I tried to work on this project again and I was getting this stacktrace when I tried to run `scala-cli .` `scala-cli compile .` and `scala-cli bloop start`. Note that it happened on Windows.

```
java.lang.Exception: Server didn't start
  scala.build.blooprifle.internal.Operations$.$anonfun$startServer$2(Operations.scala:142)
  scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:12)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
  com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:140)
```

I found possibly related issue https://github.com/VirtusLab/scala-cli/issues/599 but it was not the case for me. I have java 17

```
$ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
also JAVA_HOME was defined to this java. 

I couldn't fix it at all. Then next day (after system reboot) it worked correctly on the first attempt.

**To Reproduce**

I can't reproduce this yet :/

**Expected behaviour**
scala-cli works

**Comment by alexarchambault** [comment]
I think we can close this for now. The upcoming Scala CLI version will suggest to run `scala-cli bloop output` in such a case, which should give more details about what's going on. We can re-open this issue with users' `scala-cli bloop output` result, if that's still a problem.
