### ISSUE TITLE
Missing education.gif on https://scala-cli.virtuslab.org/education/ and more

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#856]
**Version(s)**

Scala-cli home page at 2022 April 6.

**Describe the bug**

There is currently a gif missing on these pages:
https://scala-cli.virtuslab.org/education/
https://scala-cli.virtuslab.org/scripting/
https://scala-cli.virtuslab.org/prototyping/
https://scala-cli.virtuslab.org/projects/
showing just a placeholder name of a missing animation, like this:

![image](https://user-images.githubusercontent.com/3601817/161971344-a3d32bd4-141e-472e-8f0c-6832ea069987.png)

**Expected behaviour**
There should be a gif.

**Comment by lwronski** [comment]
Hi @bjornregnell, thanks for reporting, it should be fixed now by #874
