### ISSUE TITLE
Allow using a library from github, similar to what sbt can do

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#857]
**Is your feature request related to a problem? Please describe.**

Not all libraries are published on maven, some are only on github or other places. Currently scala-cli cannot depend on a repo outside of maven (if I have understood it correctly?).

**Describe the solution you'd like**

I'd like to be able to depend on a jar released on GitHub (and elsewhere) In a similar way as `sbt` allows for this, for example (sbt syntax):
```
libraryDependencies += "tabby" % "tabby" % "0.2.3" from 
  s"https://github.com/bjornregnell/tabby/releases/download/v$tabbyVer/tabby_3-0.2.3.jar"
```
it would be very useful if the `using` directive of `scala-cli` could point to a `jar` on the net.

**Additional context**
This should, if implemented, be documented with a simple example here: 
https://scala-cli.virtuslab.org/docs/guides/dependencies/

**Comment by armanbilge** [comment]
See also https://github.com/VirtusLab/scala-cli/issues/775 regarding https://jitpack.io/ which is a similar solution in this space :)

**Comment by bjornregnell** [comment]
Yeah, adding the idea of resolvers etc is another elaboration of this. But in the first round I'd be happy with just being able to depend on a jar via an url as that will cover the basics for those who have published their libs using sbt package and upload the jar as e.g. a github release.

**Comment by armanbilge** [comment]
Ah, if you are looking for resolvers, I believe scala-cli already supports that as "repositories".
https://scala-cli.virtuslab.org/docs/reference/cli-options#--repository

https://jitpack.io/ is _much_ more than a resolver. It means anyone can publish their GitHub repo, without even having to make a jar and uploading it. jitpack.io does all of that automatically for you.

**Comment by bjornregnell** [comment]
If I understand it correctly, the "repo" thing in scala-cli requires that there is a pom and all that. The sbt-jar-from-an-url thing "just works". (And thanks for info on jitpack - I hadn't seen that before.) @armanbilge

**Comment by armanbilge** [comment]
@bjornregnell I reckon this "just works" as well :)

```scala
//> using scala "3.1.1"
//> using repository "jitpack"
//> using lib "com.github.bjornregnell:tabby:0.2.3"

import tabby.Grid

@main def main = println(Grid("a", "b", "c")(1, 2, 3))
```

What I'm hoping is that scala-cli will enable "publishing" via jitpack.io. So you can define your build using scala-cli (instead of sbt) and jitpack.io will still know how to build it and serve it.

**Comment by bjornregnell** [comment]
>l I reckon this "just works" as well :)

Wow - it really "just works" like a charm! Many thank's @armanbilge for making me aware of this - I didn't realize that jitpack does its thing even without me doing anything else :)

(But even with this option, it would be useful if scala-cli could allow a jar dependency directly from e.g. github without the need for jitpack, as this is yet another (meta-)depedency...)

**Comment by bjornregnell** [comment]
> What I'm hoping is that scala-cli will enable "publishing" via jitpack.io. So you can define your build using scala-cli (instead of sbt) and jitpack.io will still know how to build it and serve it.

That's a new interesting feature request for scala-cli (if not already issued).

**Comment by armanbilge** [comment]
- https://github.com/VirtusLab/scala-cli/issues/775
