### ISSUE TITLE
New `.nightly` support retrieves wrong (too-old) versions

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#867]
```
% scala-cli repl -S 2.12.nightly
Welcome to Scala 2.12.16-bin-586302a (OpenJDK 64-Bit Server VM, Java 17.0.2).
Type in expressions for evaluation. Or try :help.
```

but scala/scala@586302a is from November 2021

similar for 2.13:

```
% scala-cli repl -S 2.13.nightly
Welcome to Scala 2.13.9-bin-9312709 (OpenJDK 64-Bit Server VM, Java 17.0.2).
```

scala/scala@9312709 is a couple months old (it's from February 2022)

finally Scala 3:

```
% scala-cli repl -S 3.nightly
Welcome to Scala 3.2.0-RC1-bin-20220308-29073f1-NIGHTLY-git-29073f1 (17.0.2, Java OpenJDK 64-Bit Server VM).
```

20220308 was a month ago.

fyi @zmerr

**Comment by romanowski** [comment]
Hi @SethTisue, the problem is caused by the combination of Coursier selecting latest release based only on versions and Scala 2.x snapshots using ` 2.major.minor-bin-hash` versioning scheme. With that, we end up picking a release from the latest mayor/minor that by accident has the biggest hash when compared lexicographically. 

I am not sure if there is a blessed way to get the upload time from Artifactory / Maven Central so maybe Scala 2 can just change the versioning scheme for nightlies (Scala 3 puts date in the version, e.g. `3.2.0-RC1-bin-20220308-29073f1-NIGHTLY-git-29073f1`)

**Comment by ghost** [comment]
Hey @SethTisue  Thank you so much for reporting this problem. I am so sorry that this feature is not working correctly. After further consultation with the team, we would try to fix the functionality for you.

**Comment by romanowski** [comment]
It seems that we should not base our computation on the versioning only since we may pull the release or have problems when once nightly would be released with the wrong version. We (I mean @lwronski ) will try to implement a mechanism to compute nightly based on git history in the Scala repos.

**Comment by SethTisue** [comment]
here's bash code that does it, in case it's helpful for coming up with a Scala version.

multiple Scala wrappers for accessing the GitHub API seem to exist; https://github.com/47degrees/github4s, for example, appears to be actively maintained, but I haven't compared alternatives

```bash
#!/usr/bin/env bash

# cribbed from https://github.com/dwijnand/scala-runners

shopt -s extglob # for extended pattern matching operators, like `+([0-9])`

die() { echo "$*"; exit 1; }
checkExec() { type -f "$1" &> /dev/null || die "$1 command required"; }
checkHub() {
  checkExec hub
  if [ ! -f "${HOME}/.config/hub" ]; then
    echo "No hub config found (at ~/.config/hub).  Triggering hub to prompt you for credentials."
    hub api
  fi
}
jq() { checkExec jq && command jq "$@"; }
hub() { checkHub && command hub "$@"; }

getScalaHead() {
  local base_version refInfo sha
  base_version=$(getScalaBaseVersion "heads/$1")
  [ $? -eq 0 ] || die "$base_version"
  refInfo=$(hub api "repos/scala/scala/git/ref/heads/$1")
  [ $? -eq 0 ] || die "$refInfo"
  sha=$(jq -r '.object.sha' <<< "$refInfo")
  [ $? -eq 0 ] || die "$sha"
  echo "$base_version-${sha:0:7}"
}

getScalaBaseVersion() {
  local build_sbt base_version cross
  build_sbt=$(hub api -H "Accept: application/vnd.github.v3.raw" "repos/scala/scala/contents/build.sbt?ref=$1")
  [ $? -eq 0 ] || die "$build_sbt"
  base_version=$(grep -E '(baseVersion in Global|Global / baseVersion\b)' <<< "$build_sbt" | sed 's/.*"\(.*\)".*/\1/')
  cross=$(grep -q -E '\d+\.\d+.0' <<< "$base_version" && echo "-pre" || echo "-bin")
  echo "$base_version$cross"
}

case "$1" in
    2.12.x) branch=2.12.x ;;
    2.13.x) branch=2.13.x ;;
    *) branch=2.13.x ;;
esac

echo $(getScalaHead $branch)
```
