### ISSUE TITLE
"No Scala version" error does not help when quotes are missing in using scala directive, improve error message or help rewrite

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#869]
**Is your feature request related to a problem? Please describe.**
It is easy to forget, esp. for a beginner, the quotes around the version as in:
```
//> using scala 3.1.1
```
Currently the error message does not help very much, and can really make your head scratch if you have forgotten or missed that quotes are necessary:
```
$ scala-cli run .
[error]  No Scala version provided to using scala directive
```

**Describe the solution you'd like**
It would be very helpful with an explicit hint in the error message, something similar to this proposal:
```
$ scala-cli run .
[error]  The Scala version should be quoted as in:
//> using scala "3.1.1"
```
The error detection could even ask if quotes should be inserted and the file be rewritten with inserted quotes -- that would be awesome. But at least a better error message would help a lot.
```
$ scala-cli run .
[error]  The Scala version should be quoted. 
Do you want your using scala directive be re-written to:
//> using scala "3.1.1"
Y/n?
```

**Comment by lwronski** [comment]
@bjornregnell Thank you for reporting. I will close it because from scala-cli `1.0.0`, it is no longer mandatory to pass double quotes for values in the using directive:

```
$ cat hello.sc
//> using scala 3.1.1
$ scala-cli hello.sc
Compiling project (Scala 3.1.1, JVM)
Compiled project (Scala 3.1.1, JVM)
```

**Comment by bjornregnell** [comment]
Nice! A much better solution from UX perspective to not require quotes!
