### ISSUE TITLE
"./mill --repl" fails in freshly cloned VirtusLab/scala-cli repo

### ISSUE THREAD

**Issue by mtk** [VirtusLab/scala-cli#902]
% gh repo clone VirtusLab/scala-cli
Cloning into 'scala-cli'...
remote: Enumerating objects: 26997, done.
remote: Counting objects: 100% (26997/26997), done.
remote: Compressing objects: 100% (6851/6851), done.
remote: Total 26997 (delta 13522), reused 26228 (delta 13132), pack-reused 0
Receiving objects: 100% (26997/26997), 23.95 MiB | 24.43 MiB/s, done.
Resolving deltas: 100% (13522/13522), done.
% cd scala-cli
% ./mill --repl
JVM temurin:17 not found in index: JVM temurin not found
Loading...
Compiling /home/mtk/tmp/scala-cli/(console)
/home/mtk/tmp/scala-cli/(console):7: reference to build is ambiguous;
it is imported twice in the same scope by
import build._
and import ammonite.predef.build
  build.millSelf.get,
  ^
/home/mtk/tmp/scala-cli/(console):8: reference to build is ambiguous;
it is imported twice in the same scope by
import build._
and import ammonite.predef.build
  build.millDiscover,
  ^
Compilation Failed

**Comment by lwronski** [comment]
Hello @mtk, Thanks for reporting 
If you want to run `repl` using `VirtusLab/scala-cli repo` you should run following command:
```
./mill -i scala repl
```

After the special keyword `scala`, you can pass the same commands and arguments as for scala-cli, for example:
```
./mill -i scala run Hello.scala -S 3
```

**Comment by mtk** [comment]
i responded via email but it doesn't show up here.  the work around you gave runs the scala REPL via the services of scala-cli with the help of mill.  but "mill --repl" is supposed to run the ammonite REPL after building & loading the specified build (in this case, the build description for scala-cli) so that you can examine the build objects/definitions at run time.

**Comment by lwronski** [comment]
@mtk Thanks for explanation, I have never used `./mill --repl` before. 

I think I found a workaround, you can find my changes [here](https://github.com/VirtusLab/scala-cli/commit/2a23bcd56c7934cb28ae1a8ee2207a910266d29f).

There is a problem, that we have object named as `build` and it is making a collision with some method from ammonite import `ammonite.predef.build`. So compiler throws the following error:
```
it is imported twice in the same scope by
import build._
and import ammonite.predef.build
build.millSelf.get
```

To avoid it, I changed object name from `build` to `clibuild`.

**Comment by lwronski** [comment]
Hi @mtk, It was already fixed in #916. Now, it should work `./mill --repl` in the freshly VirtusLab/scala-cli repo

**Comment by mtk** [comment]
hi, lukasz.  your suggestion starts a scala repl with the help of a
mill/scala-cli.  that isn't what "mill --repl" does.  it is supposed to
start an ammonite session with the build objects compiled/loaded and thus
accessible for interactive exploration.

/mark

**Comment by lwronski** [comment]
Hi @mtk, Can you describe some example in more detail which doesn't work but should?
