### ISSUE TITLE
Add doc command to generate documentation via underlying scaladoc

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#942]
**Is your feature request related to a problem? Please describe.**
It would be really nice to be able to generate documentation without having to switch to sbt or install the scala binaries manually.

**Describe the solution you'd like**
Let `scala-cli doc .` generate documentation for the code in the current dir, for example written to a dir named `doc` or similar.

**Additional context**
This would mean that scala-cli needs to install and call scaladoc. There are also various options to scaladoc that somehow should be possible to control from `scala-cli doc`

**Comment by romanowski** [comment]
Hi @bjornregnell, scala-cli is able to generate scaladoc (javadoc) jars however this is a part of publishing so it is still experimental and we do not publicize it that much. 

```
scala-cli package --doc -o docs.jar .
```

This will create javadoc (scaladoc) jar in `docs.jar`. Is that sufficient for now? In long term, we will create a `doc` command but we are also thinking about integration with `mdoc` or static sites in `scaladoc` 3.x or similar tool so `doc` can be used to generate microsite for a library.

**Comment by bjornregnell** [comment]
Aha, good to know @romanowski ! Although mdoc integration sounds nice, ordinary scaladoc generation seems like a feature of more "hygienic" nature, so one option is to release that basic capability first through `scala-cli doc` and later extend it with more cool stuff, i.e. let `scala-cli doc` delegate to `scala-cli package --doc` as a start, if relevant. 

>  Is that sufficient for now?

The current scaladoc generates a static site, and that is how I used it with my students last year (they have one lab where they should provide docs). Is `scala-cli  package --doc` currently able to generate a static site as well, with the index.html and all that js stuff, perhaps by just unpacking the jar?

**Comment by lwronski** [comment]
Hi @bjornregnell,
Yes, the currently generated doc jar contains a static site as well, just unpacking the jar and you can see HTML files.
```
lwronski$ scala-cli package Hello.scala --doc
lwronski$ unzip Hello.jar -d doc
lwronski$ ls doc                
META-INF		_empty_.html		favicon.ico		hljs			index.html		scaladoc.version	styles
_empty_			docs			fonts			images			inkuire-db.json		scripts			webfonts

```

**Comment by bjornregnell** [comment]
So one easy fix for now is that the scala-cli package --doc commant could give a hint on how to unpack the jar to get the site **with some helpful message printed**? People might be used to the sbt doc behavior where the site is not jarred but available uncompressed in target, and it is perhaps not obvious that the jar contains the static site...

**Comment by lwronski** [comment]
I agree, that there should be a user-friendly option for generating documentation.

Instead of giving hint how to extract the jar, it wants to add a new flag/command that will generate the documentation
I'm trying to do it in #991
