### ISSUE TITLE
java.nio.file.InvalidPathException for some ASCII-letters in file names (including Swedish and German letters) 

### ISSUE THREAD

**Issue by bjornregnell** [VirtusLab/scala-cli#960]
**Version(s)**

```
$ scala-cli version
0.1.4
```

**Describe the bug**

Scala-cli cannot handle non-english letter in file-names. It is not just code files, all files in subdirs with some "strange" letter will render .e.g. `--watch` to be interrupted.

**To Reproduce**

```
$ cat test-åäöÅÄÖ.scala 
@main def hej = println("Swedish letters: ÅÄÖ åäö")

$ scala-cli run .
Error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: test-????????????.scala
For more details, please see '/home/bjornr/tmp/scala-cli-test/.scala-build/stacktraces/1651511081-13184133857077976718.log'

```

**Expected behaviour**
Filenames with special characters should be legal, at least ASCII-letters such as `ÅÄÖåäö`.

**Comment by bjornregnell** [comment]
similar to https://github.com/VirtusLab/scala-cli/issues/591

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/VirtusLab/scala-cli/pull/966.
