### ISSUE TITLE
Downloading dependency error

### ISSUE THREAD

**Issue by swuecho** [VirtusLab/scala-cli#967]
**Version(s)**

0.1.2

**Describe the bug**

❯ scala-cli --scala 2.13.8  GenCaseClassFromDDL.scala  
Downloading 3 dependencies and one internal dependency
[error] ./GenCaseClassFromDDL.scala:1:16: Error downloading org.postgresql:postgresql_2.13:42.2.8
[error]   not found: /Users/hwu/.ivy2/local/org.postgresql/postgresql_2.13/42.2.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/postgresql/postgresql_2.13/42.2.8/postgresql_2.13-42.2.8.pom
[error]   not found: /Users/hwu/Library/Caches/ScalaCli/local-repo/v0.1.2/org.postgresql/postgresql_2.13/42.2.8/ivys/ivy.xml
[error] //> using lib "io.getquill::quill-codegen-jdbc:3.10.0"
[error]                ^
[error] ./GenCaseClassFromDDL.scala:2:16: Error downloading org.postgresql:postgresql_2.13:42.2.8
[error]   not found: /Users/hwu/.ivy2/local/org.postgresql/postgresql_2.13/42.2.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/postgresql/postgresql_2.13/42.2.8/postgresql_2.13-42.2.8.pom
[error]   not found: /Users/hwu/Library/Caches/ScalaCli/local-repo/v0.1.2/org.postgresql/postgresql_2.13/42.2.8/ivys/ivy.xml
[error] //> using lib "org.postgresql::postgresql:42.2.8"
[error]                ^

**To Reproduce**
```
//> using scala "2.13.8"
//> using lib "io.getquill::quill-codegen-jdbc:3.10.0"
//> using lib "org.postgresql::postgresql:42.2.8"

import io.getquill.codegen.jdbc.SimpleJdbcCodegen
import io.getquill.codegen.model.SnakeCaseNames
import org.postgresql.ds.PGSimpleDataSource


object Hello extends App {
  val pgDataSource = new PGSimpleDataSource()
  pgDataSource.setURL(
  "",
)
pgDataSource.setUser("tan")
pgDataSource.setPassword("123456")
val gen = new SimpleJdbcCodegen(pgDataSource, "net.bestqa") {
    override def nameParser =  SnakeCaseNames
}
  gen.writeFiles("src/main/scala/net/bestqa")
}
```

**Comment by swuecho** [comment]
https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.8/ is a valid path

https://repo1.maven.org/maven2/org/postgresql/postgresql_2.13/42.2.8/postgresql_2.13-42.2.8.pom is not.

**Comment by lwronski** [comment]
Hi @swuecho, thanks for reporting

I think you should use one colon if you want to use java dependency, something like this:
```
//> using scala "2.13.8"
//> using lib "io.getquill::quill-codegen-jdbc:3.10.0"
//> using lib "org.postgresql:postgresql:42.2.8"

import io.getquill.codegen.jdbc.SimpleJdbcCodegen
import io.getquill.codegen.model.SnakeCaseNames
import org.postgresql.ds.PGSimpleDataSource


object Hello extends App {
  val pgDataSource = new PGSimpleDataSource()
  pgDataSource.setURL(
  "",
)
pgDataSource.setUser("tan")
pgDataSource.setPassword("123456")
val gen = new SimpleJdbcCodegen(pgDataSource, "net.bestqa") {
    override def nameParser =  SnakeCaseNames
}
  gen.writeFiles("src/main/scala/net/bestqa")
}
```

**Comment by swuecho** [comment]
Thanks! works now.

**Comment by swuecho** [comment]
https://github.com/VirtusLab/scala-cli/pull/974
